change function names
Multi-line description of commit,
feel free to be detailed.

diff --git a/bin/ghe-backup b/bin/ghe-backup
--- a/bin/ghe-backup
+++ b/bin/ghe-backup
@@ -66,21 +66,20 @@ trap 'rm -rf src dest1 dest2' EXIT
 mkdir -p src
 touch src/testfile
 if ! ln -s /data/does/not/exist/hooks/ src/ >/dev/null 2>&1; then
-  logError "Error: the filesystem containing $GHE_DATA_DIR does not support symbolic links." 1>&2
-  logError "Git repositories contain symbolic links that need to be preserved during a backup." 1>&2
+  log_error "Error: the filesystem containing $GHE_DATA_DIR does not support symbolic links. \nGit repositories contain symbolic links that need to be preserved during a backup." 1>&2
   exit 1
 fi
 
 if ! output=$(rsync -a src/ dest1 2>&1 && rsync -av src/ --link-dest=../dest1 dest2 2>&1); then
-  logError "Error: rsync encountered an error that could indicate a problem with permissions," 1>&2
-  logError "hard links, symbolic links, or another issue that may affect backups." 1>&2
+  log_error "Error: rsync encountered an error that could indicate a problem with permissions," 1>&2
+  log_error "hard links, symbolic links, or another issue that may affect backups." 1>&2
   echo "$output"
   exit 1
 fi
 
 if [ "$(ls -il dest1/testfile | awk '{ print $1 }')" != "$(ls -il dest2/testfile | awk '{ print $1 }')" ]; then
-  logError "Error: the filesystem containing $GHE_DATA_DIR does not support hard links." 1>&2
-  logError "Backup Utilities use hard links to store backup data efficiently." 1>&2
+  log_error "Error: the filesystem containing $GHE_DATA_DIR does not support hard links." 1>&2
+  log_error "Backup Utilities use hard links to store backup data efficiently." 1>&2
   exit 1
 fi
 rm -rf src dest1 dest2
@@ -115,9 +114,9 @@ trap 'cleanup' EXIT
 trap 'exit $?' INT # ^C always terminate
 
 if [ -h ../in-progress ]; then
-  logError "Error: detected a backup already in progress from a previous version of ghe-backup." 1>&2
-  logError "If there is no backup in progress anymore, please remove" 1>&2
-  logError "the $GHE_DATA_DIR/in-progress file." 1>&2
+  log_error "Error: detected a backup already in progress from a previous version of ghe-backup." 1>&2
+  log_error "If there is no backup in progress anymore, please remove" 1>&2
+  log_error "the $GHE_DATA_DIR/in-progress file." 1>&2
   exit 1
 fi
 
@@ -130,16 +129,16 @@ if [ -f ../in-progress ]; then
     # will clean up the failed backup.
     unlink ../in-progress
   else
-    logError "Error: A backup of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
-    logError "If PID $pid is not a process related to the backup utilities, please remove" 1>&2
-    logError "the $GHE_DATA_DIR/in-progress file and try again." 1>&2
+    log_error "Error: A backup of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
+    log_error "If PID $pid is not a process related to the backup utilities, please remove" 1>&2
+    log_error "the $GHE_DATA_DIR/in-progress file and try again." 1>&2
     exit 1
   fi
 fi
 
 echo "$GHE_SNAPSHOT_TIMESTAMP $$" > ../in-progress
 
-logInfo "Starting backup of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION in snapshot $GHE_SNAPSHOT_TIMESTAMP"
+log_info "Starting backup of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION in snapshot $GHE_SNAPSHOT_TIMESTAMP"
 
 # Perform a host connection check and establish the remote appliance version.
 # The version is available in the GHE_REMOTE_VERSION variable and also written
@@ -163,18 +162,18 @@ echo "$GHE_BACKUP_STRATEGY" > strategy
 bm_init > /dev/null
 
 ghe-backup-store-version  ||
-logWarn "Warning: storing backup-utils version remotely failed."
+log_warn "Warning: storing backup-utils version remotely failed."
 
-logInfo "Backing up GitHub settings ..."
+log_info "Backing up GitHub settings ..."
 ghe-backup-settings || failures="$failures settings"
 
-logInfo "Backing up SSH authorized keys ..."
+log_info "Backing up SSH authorized keys ..."
 bm_start "ghe-export-authorized-keys"
 ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-authorized-keys' > authorized-keys.json ||
 failures="$failures authorized-keys"
 bm_end "ghe-export-authorized-keys"
 
-logInfo "Backing up SSH host keys ..."
+log_info "Backing up SSH host keys ..."
 bm_start "ghe-export-ssh-host-keys"
 ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-ssh-host-keys' > ssh-host-keys.tar ||
 failures="$failures ssh-host-keys"
@@ -183,45 +182,45 @@ bm_end "ghe-export-ssh-host-keys"
 ghe-backup-mysql || failures="$failures mysql"
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-  logInfo "Backing up MSSQL databases ..."
+  log_info "Backing up MSSQL databases ..."
   ghe-backup-mssql 1>&3 || failures="$failures mssql"
 
-  logInfo "Backing up Actions data ..."
+  log_info "Backing up Actions data ..."
   ghe-backup-actions 1>&3 || failures="$failures actions"
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.minio.enabled'; then
-  logInfo "Backing up Minio data ..."
+  log_info "Backing up Minio data ..."
   ghe-backup-minio 1>&3 || failures="$failures minio"
 fi
 
 commands=("
-logInfo \"Backing up Redis database ...\"
+log_info \"Backing up Redis database ...\"
 ghe-backup-redis > redis.rdb || printf %s \"redis \" >> \"$failures_file\"")
 
 commands+=("
-logInfo \"Backing up audit log ...\"
+log_info \"Backing up audit log ...\"
 ghe-backup-es-audit-log || printf %s \"audit-log \" >> \"$failures_file\"")
 
 commands+=("
-logInfo \"Backing up Git repositories ...\"
+log_info \"Backing up Git repositories ...\"
 ghe-backup-repositories || printf %s \"repositories \" >> \"$failures_file\"")
 
 commands+=("
-logInfo \"Backing up GitHub Pages artifacts ...\"
+log_info \"Backing up GitHub Pages artifacts ...\"
 ghe-backup-pages || printf %s \"pages \" >> \"$failures_file\"")
 
 commands+=("
-logInfo \"Backing up storage data ...\"
+log_info \"Backing up storage data ...\"
 ghe-backup-storage || printf %s \"storage \" >> \"$failures_file\"")
 
 commands+=("
-logInfo \"Backing up custom Git hooks ...\"
+log_info \"Backing up custom Git hooks ...\"
 ghe-backup-git-hooks || printf %s \"git-hooks \" >> \"$failures_file\"")
 
 if [ "$GHE_BACKUP_STRATEGY" = "rsync" ]; then
   commands+=("
-  logInfo \"Backing up Elasticsearch indices ...\"
+  log_info \"Backing up Elasticsearch indices ...\"
   ghe-backup-es-rsync || printf %s \"elasticsearch \" >> \"$failures_file\"")
 fi
 
@@ -239,7 +238,7 @@ fi
 
 # git fsck repositories after the backup
 if [ "$GHE_BACKUP_FSCK" = "yes" ]; then
-  logInfo "Running git fsck on repositories ..."
+  log_info "Running git fsck on repositories ..."
   ghe-backup-fsck $GHE_SNAPSHOT_DIR || failures="$failures fsck"
 fi
 
@@ -255,7 +254,7 @@ if [ -z "$failures" ]; then
   ghe-prune-snapshots
 fi
 
-logInfo "Completed backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP at $(date +"%H:%M:%S")"
+log_info "Completed backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP at $(date +"%H:%M:%S")"
 
 # Exit non-zero and list the steps that failed.
 if [ -z "$failures" ]; then
@@ -263,12 +262,12 @@ if [ -z "$failures" ]; then
 else
   steps="$(echo $failures | sed 's/ /, /g')"
   ghe_remote_logger "Completed backup from $(hostname) / snapshot $GHE_SNAPSHOT_TIMESTAMP with failures: ${steps}."
-  logError "Error: Snapshot incomplete. Some steps failed: ${steps}. "
+  log_error "Error: Snapshot incomplete. Some steps failed: ${steps}. "
   exit 1
 fi
 
 # Detect if the created backup contains any leaked ssh keys
-logInfo "Checking for leaked ssh keys ..."
+log_info "Checking for leaked ssh keys ..."
 ghe-detect-leaked-ssh-keys -s "$GHE_SNAPSHOT_DIR" || true
 
 # Make sure we exit zero after the conditional
diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -90,11 +90,11 @@ start_cron () {
   echo "Starting cron ..."
   if $CLUSTER; then
     if ! ghe-ssh "$GHE_HOSTNAME" -- "ghe-cluster-each -- sudo service cron start"; then
-      logWarn "* Warning: Failed to start cron on one or more nodes"
+      log_warn "* Warning: Failed to start cron on one or more nodes"
     fi
   else
     if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo service cron start"; then
-      logWarn "* Warning: Failed to start cron"
+      log_warn "* Warning: Failed to start cron"
     fi
   fi
 }
@@ -105,7 +105,7 @@ cleanup () {
   fi
 
   if $ACTIONS_STOPPED && ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-    logInfo "Restarting Actions after restore ..."
+    log_info "Restarting Actions after restore ..."
     # In GHES 3.3+, ghe-actions-start no longer has a -f (force) flag. In GHES 3.2 and below, we must provide the
     # force flag to make sure it can start in maintenance mode. Use it conditionally based on whether it exists
     # in the --help output
@@ -129,7 +129,7 @@ cleanup () {
 cleanup_cluster_nodes() {
   uuid="$1"
   if [ -z "$uuid" ]; then
-    logInfo "Node UUID required."
+    log_info "Node UUID required."
     exit 2
   fi
 
@@ -171,7 +171,7 @@ GHE_RESTORE_SNAPSHOT=$(basename "$GHE_RESTORE_SNAPSHOT_PATH")
 export GHE_RESTORE_SNAPSHOT
 
 # Detect if the backup we are restoring has a leaked ssh key
-logInfo "Checking for leaked keys in the backup snapshot that is being restored ..."
+log_info "Checking for leaked keys in the backup snapshot that is being restored ..."
 ghe-detect-leaked-ssh-keys -s "$GHE_RESTORE_SNAPSHOT_PATH" || true
 
 # Figure out whether to use the tarball or rsync restore strategy based on the
@@ -199,7 +199,7 @@ export CLUSTER
 
 # Restoring a cluster backup to a standalone appliance is not supported
 if ! $CLUSTER && [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
-  logError "Error: Snapshot from a GitHub Enterprise cluster cannot be restored to a standalone appliance. Aborting." >&2
+  log_error "Error: Snapshot from a GitHub Enterprise cluster cannot be restored to a standalone appliance. Aborting." >&2
   exit 1
 fi
 
@@ -211,7 +211,7 @@ fi
 # Figure out if this appliance is in a replication pair
 if ghe-ssh "$GHE_HOSTNAME" -- \
   "[ -f '$GHE_REMOTE_ROOT_DIR/etc/github/repl-state' ]"; then
-  logError "Error: Restoring to an appliance with replication enabled is not supported. Please teardown replication before restoring." >&2
+  log_error "Error: Restoring to an appliance with replication enabled is not supported. Please teardown replication before restoring." >&2
   exit 1
 fi
 
@@ -247,8 +247,8 @@ fi
 
 # Log restore start message locally and in /var/log/syslog on remote instance
 START_TIME=$(date +%s)
-logInfo 'Start time:' $START_TIME
-logInfo "Starting restore of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION from snapshot $GHE_RESTORE_SNAPSHOT"
+log_info 'Start time:' $START_TIME
+log_info "Starting restore of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION from snapshot $GHE_RESTORE_SNAPSHOT"
 ghe_remote_logger "Starting restore from $(hostname) with backup-utils v$BACKUP_UTILS_VERSION / snapshot $GHE_RESTORE_SNAPSHOT ..."
 
 # Keep other processes on the VM or cluster in the loop about the restore status.
@@ -275,7 +275,7 @@ update_restore_status "restoring"
 # Make sure the GitHub appliance is in maintenance mode.
 if $instance_configured; then
   if ! ghe-maintenance-mode-status "$GHE_HOSTNAME"; then
-    logError "Error: $GHE_HOSTNAME must be put in maintenance mode before restoring. Aborting." 1>&2
+    log_error "Error: $GHE_HOSTNAME must be put in maintenance mode before restoring. Aborting." 1>&2
     exit 1
   fi
 fi
@@ -287,7 +287,7 @@ RELEASE_VERSION=$(ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --get core.package-vers
 # mismatches in the secrets needed for Actions which ultimately results in Actions not working properly. Note: xargs is to remove whitespace
 ACTIONS_ENABLED_IN_BACKUP=$(git config -f $GHE_RESTORE_SNAPSHOT_PATH/settings.json --bool app.actions.enabled | xargs)
 if [[ $ACTIONS_ENABLED_IN_BACKUP != true ]] && ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-    logError "Restoring a backup with Actions disabled onto an appliance with Actions enabled is not supported." >&2
+    log_error "Restoring a backup with Actions disabled onto an appliance with Actions enabled is not supported." >&2
     exit 1
 fi
 
@@ -298,19 +298,19 @@ if [ -d "$GHE_RESTORE_SNAPSHOT_PATH/mssql" ] || [ -d "$GHE_RESTORE_SNAPSHOT_PATH
     ac_db_ghe=$(echo 'ghe-mssql-console -y -n -q "SELECT name FROM sys.databases" | grep -i "ArtifactCache" | wc -l | tr -d " "' | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
     ac_db_snapshot=$(find "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/mssql/" -maxdepth 1 -name 'ArtifactCache*.bak' | wc -l | tr -d " ")
     if [[ $ac_db_ghe -gt 0  &&  $ac_db_snapshot -eq 0 ]]; then
-      logError "$GHE_HOSTNAME has Actions Cache service enabled but no Actions Cache data is present in snapshot to restore. Aborting" \
+      log_error "$GHE_HOSTNAME has Actions Cache service enabled but no Actions Cache data is present in snapshot to restore. Aborting" \
       "\n""Please disable Actions cache service in $GHE_HOSTNAME and retry" \
       "\n""To disable Actions Cache service run as admin: ghe-actions-cache-disable" 1>&2
       exit 1
     fi
     if [[ $ac_db_ghe -eq 0  &&  $ac_db_snapshot -gt 0 && ! $RESTORE_SETTINGS ]]; then
-      logError "$GHE_HOSTNAME has Actions Cache service disabled but the snapshot is attempting to restore data for the service. Aborting." \
+      log_error "$GHE_HOSTNAME has Actions Cache service disabled but the snapshot is attempting to restore data for the service. Aborting." \
       "\n""Please enable Actions cache service in $GHE_HOSTNAME and retry" \
       "\n""To enable Actions Cache service run as admin: ghe-actions-cache-enable" 1>&2
       exit 1
     fi
   else
-    logError "$GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting." \
+    log_error "$GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting." \
      "\n""Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@$RELEASE_VERSION/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled" 1>&2
     exit 1
   fi
@@ -320,10 +320,10 @@ fi
 bm_init > /dev/null
 
 ghe-backup-store-version  ||
-logWarn "Warning: storing backup-utils version remotely failed."
+log_warn "Warning: storing backup-utils version remotely failed."
 
 # Stop cron and timerd, as scheduled jobs may disrupt the restore process.
-logInfo "Stopping cron and github-timerd ..."
+log_info "Stopping cron and github-timerd ..."
 if $CLUSTER; then
   if ! ghe-ssh "$GHE_HOSTNAME" -- "ghe-cluster-each -- sudo service cron stop"; then
     ghe_verbose "* Warning: Failed to stop cron on one or more nodes"
@@ -375,7 +375,7 @@ fi
 
 # Restore UUID if present and not restoring to cluster.
 if [ -s "$GHE_RESTORE_SNAPSHOT_PATH/uuid" ] && ! $CLUSTER; then
-  logInfo "Restoring UUID ..."
+  log_info "Restoring UUID ..."
   cat "$GHE_RESTORE_SNAPSHOT_PATH/uuid" |
   ghe-ssh "$GHE_HOSTNAME" -- "sudo sponge '$GHE_REMOTE_DATA_USER_DIR/common/uuid' 2>/dev/null"
   ghe-ssh "$GHE_HOSTNAME" -- "sudo systemctl stop consul" || true
@@ -400,64 +400,64 @@ else
 fi
 
 if is_external_database_target_or_snapshot && $SKIP_MYSQL; then
-  logInfo "Skipping MySQL restore."
+  log_info "Skipping MySQL restore."
 else
-  logInfo "Restoring MySQL database from ${backup_snapshot_strategy} backup snapshot on an appliance configured for ${appliance_strategy} backups ..."
+  log_info "Restoring MySQL database from ${backup_snapshot_strategy} backup snapshot on an appliance configured for ${appliance_strategy} backups ..."
   ghe-restore-mysql "$GHE_HOSTNAME" 1>&3
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-  logInfo "Stopping Actions before restoring databases ..."
+  log_info "Stopping Actions before restoring databases ..."
   # We mark Actions as stopped even if the `ghe-actions-stop`
   # fails to ensure that we cleanly start actions when performing cleanup.
   ACTIONS_STOPPED=true
   ghe-ssh "$GHE_HOSTNAME" -- 'ghe-actions-stop' 1>&3
 
-  logInfo "Restoring MSSQL databases ..."
+  log_info "Restoring MSSQL databases ..."
   ghe-restore-mssql "$GHE_HOSTNAME" 1>&3
 
-  logInfo "Restoring Actions data ..."
+  log_info "Restoring Actions data ..."
   ghe-restore-actions "$GHE_HOSTNAME" 1>&3
-  logWarn "* WARNING: Every self-hosted Actions runner that communicates with the restored GHES server must be restarted or reconfigured in order to continue functioning."
-  logWarn "           See https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners for more details on how to reconfigure self-hosted Actions runners."
+  log_warn "* WARNING: Every self-hosted Actions runner that communicates with the restored GHES server must be restarted or reconfigured in order to continue functioning."
+  log_warn "           See https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners for more details on how to reconfigure self-hosted Actions runners."
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.minio.enabled'; then
-  logInfo "Restoring MinIO data ..."
+  log_info "Restoring MinIO data ..."
   ghe-restore-minio "$GHE_HOSTNAME" 1>&3
 fi
 
 commands=("
-logInfo \"Restoring Redis database ...\"
+log_info \"Restoring Redis database ...\"
 ghe-ssh \"$GHE_HOSTNAME\" -- 'ghe-import-redis' < \"$GHE_RESTORE_SNAPSHOT_PATH/redis.rdb\" 1>&3")
 
 commands+=("
-logInfo \"Restoring Git repositories ...\"
+log_info \"Restoring Git repositories ...\"
 ghe-restore-repositories \"$GHE_HOSTNAME\"")
 
 commands+=("
-logInfo \"Restoring Gists ...\"
+log_info \"Restoring Gists ...\"
 ghe-restore-repositories-gist \"$GHE_HOSTNAME\"")
 
 commands+=("
-logInfo \"Restoring GitHub Pages artifacts ...\"
+log_info \"Restoring GitHub Pages artifacts ...\"
 ghe-restore-pages \"$GHE_HOSTNAME\" 1>&3")
 
 commands+=("
-logInfo \"Restoring SSH authorized keys ...\"
+log_info \"Restoring SSH authorized keys ...\"
 ghe-ssh \"$GHE_HOSTNAME\" -- 'ghe-import-authorized-keys' < \"$GHE_RESTORE_SNAPSHOT_PATH/authorized-keys.json\" 1>&3")
 
 commands+=("
-logInfo \"Restoring storage data ...\"
+log_info \"Restoring storage data ...\"
 ghe-restore-storage \"$GHE_HOSTNAME\" 1>&3")
 
 commands+=("
-logInfo \"Restoring custom Git hooks ...\"
+log_info \"Restoring custom Git hooks ...\"
 ghe-restore-git-hooks \"$GHE_HOSTNAME\" 1>&3")
 
 if ! $CLUSTER && [ -d "$GHE_RESTORE_SNAPSHOT_PATH/elasticsearch" ]; then
   commands+=("
-  logInfo \"Restoring Elasticsearch indices ...\"
+  log_info \"Restoring Elasticsearch indices ...\"
   ghe-restore-es-rsync \"$GHE_HOSTNAME\" 1>&3")
 fi
 
@@ -470,10 +470,10 @@ fi
 # all releases of cluster
 if $CLUSTER || [ "$(version $GHE_REMOTE_VERSION)" -ge "$(version 2.12.9)" ]; then
   if [[ "$GHE_RESTORE_SKIP_AUDIT_LOGS" = "yes" ]]; then
-    logInfo "Skipping restore of audit logs."
+    log_info "Skipping restore of audit logs."
   else
     commands+=("
-     logInfo \"Restoring Audit logs ...\"
+     log_info \"Restoring Audit logs ...\"
     ghe-restore-es-audit-log \"$GHE_HOSTNAME\" 1>&3")
   fi
 
@@ -488,14 +488,14 @@ else
 fi
 
 # Restart an already running memcached to reset the cache after restore
-logInfo "Restarting memcached ..." 1>&3
+log_info "Restarting memcached ..." 1>&3
 echo "sudo restart -q memcached 2>/dev/null || true" |
   ghe-ssh "$GHE_HOSTNAME" -- /bin/sh
 
 # Prevent GitHub Connect jobs running before we've had a chance to reset
 # the configuration by setting the last run date to now.
 if ! $RESTORE_SETTINGS; then
-  logInfo "Setting last run date for GitHub Connect jobs ..." 1>&3
+  log_info "Setting last run date for GitHub Connect jobs ..." 1>&3
   echo "now=$(date +%s.0000000); ghe-redis-cli mset timer:UpdateConnectInstallationInfo \$now timer:UploadEnterpriseServerUserAccountsJob \$now timer:UploadConnectMetricsJob \$now timer:GitHubConnectPushNewContributionsJob \$now" |
     ghe-ssh "$GHE_HOSTNAME" -- /bin/sh 1>&3
 fi
@@ -503,7 +503,7 @@ fi
 # When restoring to a host that has already been configured, kick off a
 # config run to perform data migrations.
 if $CLUSTER; then
-  logInfo "Configuring cluster ..."
+  log_info "Configuring cluster ..."
   if [ "$GHE_VERSION_MAJOR" -eq "3" ]; then
     ghe-ssh "$GHE_HOSTNAME" -- "ghe-cluster-nomad-cleanup" 1>&3 2>&3
   elif [ "$GHE_VERSION_MAJOR" -eq "2" ] && [ "$GHE_VERSION_MINOR" -eq "22" ]; then
@@ -511,7 +511,7 @@ if $CLUSTER; then
   fi
   ghe-ssh "$GHE_HOSTNAME" -- "ghe-cluster-config-apply" 1>&3 2>&3
 elif $instance_configured; then
-  logInfo "Configuring appliance ..."
+  log_info "Configuring appliance ..."
   if [ "$GHE_VERSION_MAJOR" -eq "3" ]; then
     ghe-ssh "$GHE_HOSTNAME" -- "ghe-nomad-cleanup" 1>&3 2>&3
   elif [ "$GHE_VERSION_MAJOR" -eq "2" ] && [ "$GHE_VERSION_MINOR" -eq "22" ]; then
@@ -560,25 +560,25 @@ update_restore_status "complete"
 ghe_remote_logger "Completed restore from $(hostname) / snapshot ${GHE_RESTORE_SNAPSHOT}."
 
 if ! $CLUSTER; then
-  logInfo "Restoring SSH host keys ..."
+  log_info "Restoring SSH host keys ..."
   ghe-ssh "$GHE_HOSTNAME" -- 'ghe-import-ssh-host-keys' < "$GHE_RESTORE_SNAPSHOT_PATH/ssh-host-keys.tar" 1>&3
 else
   # This will make sure that Git over SSH host keys (babeld) are
   # copied to all the cluster nodes so babeld uses the same keys.
-  logInfo "Restoring Git over SSH host keys ..."
+  log_info "Restoring Git over SSH host keys ..."
   ghe-ssh "$GHE_HOSTNAME" -- "sudo tar -xpf - -C $GHE_REMOTE_DATA_USER_DIR/common" < "$GHE_RESTORE_SNAPSHOT_PATH/ssh-host-keys.tar" 1>&3
   ghe-ssh "$GHE_HOSTNAME" -- "sudo chown babeld:babeld $GHE_REMOTE_DATA_USER_DIR/common/ssh_host_*" 1>&3
-  logInfo "if [ -f /usr/local/share/enterprise/ghe-cluster-config-update ]; then /usr/local/share/enterprise/ghe-cluster-config-update -s; else ghe-cluster-config-update -s; fi" |
+  log_info "if [ -f /usr/local/share/enterprise/ghe-cluster-config-update ]; then /usr/local/share/enterprise/ghe-cluster-config-update -s; else ghe-cluster-config-update -s; fi" |
   ghe-ssh "$GHE_HOSTNAME" -- /bin/sh 1>&3
 fi
 
 END_TIME=$(date +%s)
-logInfo 'End time:' $END_TIME
-logInfo 'Runtime:' $(($END_TIME - $START_TIME)) 'seconds'
+log_info 'End time:' $END_TIME
+log_info 'Runtime:' $(($END_TIME - $START_TIME)) 'seconds'
 
-logInfo "Restore of $GHE_HOSTNAME from snapshot $GHE_RESTORE_SNAPSHOT finished."
+log_info "Restore of $GHE_HOSTNAME from snapshot $GHE_RESTORE_SNAPSHOT finished."
 
 if ! $instance_configured; then
-  logInfo "To complete the restore process, please visit https://$hostname/setup/settings to review and save the appliance configuration."
+  log_info "To complete the restore process, please visit https://$hostname/setup/settings to review and save the appliance configuration."
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-actions b/share/github-backup-utils/ghe-backup-actions
--- a/share/github-backup-utils/ghe-backup-actions
+++ b/share/github-backup-utils/ghe-backup-actions
@@ -20,7 +20,7 @@ backup_dir="$GHE_SNAPSHOT_DIR/actions"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  logError "Error: rsync not found." 1>&2
+  log_error "Error: rsync not found." 1>&2
   exit 1
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-es-rsync b/share/github-backup-utils/ghe-backup-es-rsync
--- a/share/github-backup-utils/ghe-backup-es-rsync
+++ b/share/github-backup-utils/ghe-backup-es-rsync
@@ -20,7 +20,7 @@ ghe_remote_version_required "$host"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  logError "rsync not found." 1>&2
+  log_error "rsync not found." 1>&2
   exit 1
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-pages b/share/github-backup-utils/ghe-backup-pages
--- a/share/github-backup-utils/ghe-backup-pages
+++ b/share/github-backup-utils/ghe-backup-pages
@@ -18,7 +18,7 @@ backup_dir="$GHE_SNAPSHOT_DIR/pages"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  logError "rsync not found." 1>&2
+  log_error "rsync not found." 1>&2
   exit 1
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-repositories b/share/github-backup-utils/ghe-backup-repositories
--- a/share/github-backup-utils/ghe-backup-repositories
+++ b/share/github-backup-utils/ghe-backup-repositories
@@ -46,7 +46,7 @@ backup_current="$GHE_DATA_DIR/current/repositories"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  logError "rsync not found." 1>&2
+  log_error "rsync not found." 1>&2
   exit 1
 fi
 
@@ -142,7 +142,7 @@ ghe_debug "\n$(find "$tempdir" -maxdepth 1 -name '*.rsync')"
 bm_end "$(basename $0) - Processing routes"
 
 if [ -z "$(find "$tempdir" -maxdepth 1 -name '*.rsync')" ]; then
-  logWarn "no routes found, skipping repositories backup ..."
+  log_warn "no routes found, skipping repositories backup ..."
   exit 0
 fi
 
@@ -187,7 +187,7 @@ sync_data (){
   # should be transferred here.
   echo 1>&3
 
-  logInfo "* Transferring auxiliary files ..." 1>&3
+  log_info "* Transferring auxiliary files ..." 1>&3
   rsync_repository_data $1:122 $2 -z <<RULES
 - /__*__/
 - /info/
@@ -224,7 +224,7 @@ RULES
     # Sync packed refs files. This is performed before sync'ing loose refs since
     # loose refs trump packed-refs information.
   echo 1>&3
-  logInfo "* Transferring packed-refs files ..." 1>&3
+  log_info "* Transferring packed-refs files ..." 1>&3
   rsync_repository_data $1:122 $2 -z <<RULES
 - /__*__/
 - /info/
@@ -250,7 +250,7 @@ RULES
     # Sync loose refs and reflogs. This must be performed before object data is
     # transferred to ensure that all referenced objects are included.
   echo 1>&3
-  logInfo "* Transferring refs and reflogs ..."  1>&3
+  log_info "* Transferring refs and reflogs ..."  1>&3
   rsync_repository_data $1:122 $2 -z <<RULES
 - /__*__/
 - /info/
@@ -286,7 +286,7 @@ RULES
     # Sync git objects and pack files. Compression is disabled during this phase
     # since these files are already well compressed.
   echo 1>&3
-  logInfo "* Transferring objects and packs ..." 1>&3
+  log_info "* Transferring objects and packs ..." 1>&3
   rsync_repository_data $1:122 $2 -H <<RULES
 - /__*__/
 - /info/
@@ -350,7 +350,7 @@ for h in $hostnames; do
   # /data/repositories. All other special user data directories have been moved under
   # the /data/user directory.
   echo 1>&3
-  logInfo "* Transferring special data directories from $h..." 1>&3
+  log_info "* Transferring special data directories from $h..." 1>&3
   rsync_repository_data $h:122 -z <<RULES
 - /__nodeload_archives__/
 - /__gitmon__/
diff --git a/share/github-backup-utils/ghe-backup-storage b/share/github-backup-utils/ghe-backup-storage
--- a/share/github-backup-utils/ghe-backup-storage
+++ b/share/github-backup-utils/ghe-backup-storage
@@ -19,7 +19,7 @@ backup_dir="$GHE_SNAPSHOT_DIR/storage"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  logError "rsync not found." 1>&2
+  log_error "rsync not found." 1>&2
   exit 1
 fi
 
@@ -60,7 +60,7 @@ cleanup() {
   # Enable remote maintenance operations
   for hostname in $hostnames; do
     ghe-gc-enable $ssh_config_file_opt $hostname:$port || { 
-      logWarn "Re-enable gc on $hostname failed, please manually delete $SYNC_IN_PROGRESS_FILE" 1>&2
+      log_warn "Re-enable gc on $hostname failed, please manually delete $SYNC_IN_PROGRESS_FILE" 1>&2
     }
   done
 
@@ -111,7 +111,7 @@ ghe_debug "\n$(find "$tempdir" -maxdepth 1 -name '*.rsync')"
 bm_end "$(basename $0) - Processing routes"
 
 if [ -z "$(find "$tempdir" -maxdepth 1 -name '*.rsync')" ]; then
-  logWarn "no routes found, skipping storage backup ..."
+  log_warn "no routes found, skipping storage backup ..."
   exit 0
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-userdata b/share/github-backup-utils/ghe-backup-userdata
--- a/share/github-backup-utils/ghe-backup-userdata
+++ b/share/github-backup-utils/ghe-backup-userdata
@@ -13,7 +13,7 @@ bm_start "$(basename $0) - $1"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  logError "rsync not found." 1>&2
+  log_error "rsync not found." 1>&2
   exit 1
 fi
 
