change to true

diff --git a/bin/ghe-backup b/bin/ghe-backup
--- a/bin/ghe-backup
+++ b/bin/ghe-backup
@@ -81,6 +81,25 @@ if [ "$(ls -il dest1/testfile | awk '{ print $1 }')" != "$(ls -il dest2/testfile
 fi
 rm -rf src dest1 dest2
 
+# if we should use gitbackups to backup repositories
+should_use_gitbackups_for_repositories(){
+  ghe-ssh "$GHE_HOSTNAME" ghe-config "app.github.gitbackups" true
+}
+
+# check that the appliance supports using gitbackups for repositories
+can_use_gitbackups_for_repositories(){
+  ghe-ssh "$GHE_HOSTNAME" test -e /data/github/current/bin/ghe-backup-repositories
+}
+
+# Exit early if the appliance is missing script to backup repositories using gitbackups
+if should_use_gitbackups_for_repositories; then
+  if ! can_use_gitbackups_for_repositories; then
+    echo "Error: Configuration setting 'app.github.gitbackups' is enabled but this version of GHES cannot use gitbackups to back up repositories via 'ghe-backup'."
+    echo "Disable configuration setting 'app.github.gitbackups' and re-run 'ghe-backup' to use rsync."
+    exit 1
+  fi
+fi
+
 # To prevent multiple backup runs happening at the same time, we create a
 # in-progress file with the timestamp and pid of the backup process,
 # giving us a form of locking.
@@ -173,6 +192,11 @@ bm_start "ghe-export-ssh-host-keys"
 ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-ssh-host-keys' > ssh-host-keys.tar ||
 failures="$failures ssh-host-keys"
 bm_end "ghe-export-ssh-host-keys"
+
+# if we are going to take a binary backup
+is_binary_backup(){
+  ghe-ssh "$GHE_HOSTNAME" ghe-config "mysql.backup.binary" true
+}
 
 echo "Backing up MySQL database ..."
 bm_start "ghe-export-mysql"
