Fixed Shell Check Errors on Inappropriate Globbing and added some shellcheck disable lines

diff --git a/bin/ghe-backup b/bin/ghe-backup
--- a/bin/ghe-backup
+++ b/bin/ghe-backup
@@ -78,6 +78,7 @@ if ! output=$(rsync -a src/ dest1 2>&1 && rsync -av src/ --link-dest=../dest1 de
   exit 1
 fi
 
+# shellcheck disable=SC2012
 if [ "$(ls -il dest1/testfile | awk '{ print $1 }')" != "$(ls -il dest2/testfile | awk '{ print $1 }')" ]; then
   echo "Error: the filesystem containing $GHE_DATA_DIR does not support hard links." 1>&2
   echo "Backup Utilities use hard links to store backup data efficiently." 1>&2
@@ -99,7 +100,7 @@ cleanup () {
     progress=$(cat ../in-progress)
     snapshot=$(echo "$progress" | cut -d ' ' -f 1)
     pid=$(echo "$progress" | cut -d ' ' -f 2)
-    if [ "$snapshot" = "$GHE_SNAPSHOT_TIMESTAMP" ] && [ "$$" = $pid ]; then
+    if [ "$snapshot" = "$GHE_SNAPSHOT_TIMESTAMP" ] && [ "$$" = "$pid" ]; then
       unlink ../in-progress
     fi
   fi
@@ -140,13 +141,13 @@ fi
 echo "$GHE_SNAPSHOT_TIMESTAMP $$" > ../in-progress
 
 START_TIME=$(date +%s)
-echo 'Start time:' $START_TIME
+echo 'Start time:' "$START_TIME"
 echo "Starting backup of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION in snapshot $GHE_SNAPSHOT_TIMESTAMP"
 
 # Perform a host connection check and establish the remote appliance version.
 # The version is available in the GHE_REMOTE_VERSION variable and also written
 # to a version file in the snapshot directory itself.
-ghe_remote_version_required
+ghe_remote_version_required "$@"
 echo "$GHE_REMOTE_VERSION" > version
 
 if [ -n "$GHE_ALLOW_REPLICA_BACKUP" ]; then
@@ -228,7 +229,7 @@ if [ "$GHE_BACKUP_STRATEGY" = "rsync" ]; then
 fi
 
 if [ "$GHE_PARALLEL_ENABLED" = "yes" ]; then
-  $GHE_PARALLEL_COMMAND $GHE_PARALLEL_COMMAND_OPTIONS -- "${commands[@]}"
+  $GHE_PARALLEL_COMMAND "$GHE_PARALLEL_COMMAND_OPTIONS" -- "${commands[@]}"
 else
   for c in "${commands[@]}"; do
     eval "$c"
@@ -241,7 +242,7 @@ fi
 
 # git fsck repositories after the backup
 if [ "$GHE_BACKUP_FSCK" = "yes" ]; then
-  ghe-backup-fsck $GHE_SNAPSHOT_DIR || failures="$failures fsck"
+  ghe-backup-fsck "$GHE_SNAPSHOT_DIR" || failures="$failures fsck"
 fi
 
 # If everything was successful, mark the snapshot as complete, update the
@@ -257,16 +258,17 @@ if [ -z "$failures" ]; then
 fi
 
 END_TIME=$(date +%s)
-echo 'End time:' $END_TIME
-echo 'Runtime:' $(($END_TIME - $START_TIME)) 'seconds'
+echo 'End time:' "$END_TIME"
+echo 'Runtime:' $(("$END_TIME" - "$START_TIME")) 'seconds'
 
 echo "Completed backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP at $(date +"%H:%M:%S")"
 
 # Exit non-zero and list the steps that failed.
+# shellcheck disable=SC2001
 if [ -z "$failures" ]; then
   ghe_remote_logger "Completed backup from $(hostname) / snapshot $GHE_SNAPSHOT_TIMESTAMP successfully."
 else
-  steps="$(echo $failures | sed 's/ /, /g')"
+  steps="$(echo "$failures" | sed 's/ /, /g')" # TODO: THIS CAN BE OPTIMIZED
   ghe_remote_logger "Completed backup from $(hostname) / snapshot $GHE_SNAPSHOT_TIMESTAMP with failures: ${steps}."
   echo "Error: Snapshot incomplete. Some steps failed: ${steps}. "
   exit 1
