Updated hostcheck to use rsync

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -151,11 +151,14 @@ min_jq=""
 # shellcheck source=share/github-backup-utils/requirements.txt
 . "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/requirements.txt"
 
+#source disk size file
+. "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/ghe-rsync-size.sh"
+
 #Display dir requirements for repositories and mysql
-backup_dir=${GHE_DATA_DIR}
-available_space=$(df $backup_dir | awk 'END{print $4}')
+available_space=$(df $GHE_DATA_DIR | awk 'END{print $4}') 
+echo "Available space: $available_space" 1>&2
+
 repo_disk_size=$(ghe-ssh "$host" sudo du -sh /data/user/repositories | awk '{print $1}')
-#mysql_disk_size=$(ghe-ssh "$host" sudo du -sh /data/user/mysql | awk '{print $1}')
 # Convert the data size to kilobytes
 case "$repo_disk_size" in
   *T) repo_disk_size=$(( $(echo "$repo_disk_size" | sed 's/T/000000000/') )) ;;
@@ -163,30 +166,39 @@ case "$repo_disk_size" in
   *M) repo_disk_size=$(( $(echo "$repo_disk_size" | sed 's/M/000/') )) ;;
   *K) repo_disk_size=$(( $(echo "$repo_disk_size" | sed 's/K//') )) ;;
 esac
+repos_disk_size=$(transfer_size repositories /tmp)
+pages_disk_size=$(transfer_size pages /tmp)
+es_disk_size=$(transfer_size elasticsearch /tmp)
+stor_disk_size=$(transfer_size storage /tmp)
+minio_disk_size=$(transfer_size minio /tmp)
+min_disk_req=$(( $(echo "$repos_disk_size" | awk '{print $1}') + $(echo "$pages_disk_size" | awk '{print $1}') + $(echo "$es_disk_size" | awk '{print $1}') + $(echo "$stor_disk_size" | awk '{print $1}') + $(echo "$minio_disk_size" | awk '{print $1}') ))
+echo "repositories = $repos_disk_size, pages: $pages_disk_size, elasticsearch: $es_disk_size, storage: $stor_disk_size, minio: $minio_disk_size" 1>&2
+echo "min_disk_required for backup = $min_disk_req bytes" 1>&2
+
 if [[ $available_space -lt $repo_disk_size ]]; then
-  echo "There is not enough disk space for the backup"
+  echo "There is not enough disk space for the backup" 1>&2
   exit 1
 fi
 
 #Check rsync, openssh & jq versions
 rsync_version=$(rsync --version | grep 'version' | awk '{print $3}')
 if awk "BEGIN {exit !($rsync_version < $min_rsync)}" &> /dev/null; then
-  echo "rsync version $rsync_version in backup-host does not meet minimum requirements."
-  echo "Please make sure you have the minimum required version of rsync: $min_rsync installed"
+  echo "rsync version $rsync_version in backup-host does not meet minimum requirements." 1>&2
+  echo "Please make sure you have the minimum required version of rsync: $min_rsync installed" 1>&2
   exit 1
 fi
 
 ssh_version=$(ssh -V 2>&1 | awk '{print $1}'|grep -oPm 1 '[\d\.]+' |head -1)
 if awk "BEGIN {exit !($ssh_version < $min_openssh)}" &> /dev/null; then
-  echo "openSSH version $ssh_version in backup-host does not meet minimum requirements."
-  echo "Please make sure the minimum required version of openSSH: $min_openssh is installed"
+  echo "openSSH version $ssh_version in backup-host does not meet minimum requirements." 1>&2
+  echo "Please make sure the minimum required version of openSSH: $min_openssh is installed" 1>&2
   exit 1
 fi
 
 jq_version=$(jq --version |awk -F\- '{print $2}')
 if awk "BEGIN {exit !($jq_version < $min_jq)}" &> /dev/null; then
-  echo "jq version $jq_version in backup-host does not meet minimum requirements."
-  echo "Please make sure you have the minimum required version of jq: $min_jq installed"
+  echo "jq version $jq_version in backup-host does not meet minimum requirements." 1>&2
+  echo "Please make sure you have the minimum required version of jq: $min_jq installed" 1>&2
   exit 1
 fi
 
