reverting logging statements

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -90,11 +90,11 @@ start_cron () {
   echo  "Starting cron ..." 
   if $CLUSTER; then
     if ! ghe-ssh "$GHE_HOSTNAME" -- "ghe-cluster-each -- sudo service cron start" ; then
-      log_warn "Failed to start cron on one or more nodes"
+      echo  "Failed to start cron on one or more nodes"
     fi
   else
     if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo service cron start" ; then
-      log_warn "Failed to start cron"
+      echo  "Failed to start cron"
     fi
   fi
 }
@@ -124,13 +124,13 @@ cleanup () {
   # Cleanup SSH multiplexing
   echo  "Cleaning up SSH multiplexing ..." 
   if ! ghe-ssh --clean ; then
-    log_warn "Failed to clean up SSH multiplexing"
+    echo  "Failed to clean up SSH multiplexing"
   fi
   # Remove in-progress file
   echo  "Removing in-progress file ..." 1>&3
 
   if ! rm -f ${GHE_DATA_DIR}/in-progress-restore ; then
-    log_warn "Failed to remove in-progress file" 1>&3
+    echo  "Failed to remove in-progress file" 1>&3
   fi
 }
 
@@ -139,7 +139,7 @@ cleanup () {
 cleanup_cluster_nodes() {
   uuid="$1"
   if [ -z "$uuid" ]; then
-    log_error "Node UUID required."
+    echo  "Node UUID required."
     exit 2
   fi
   echo  "Cleaning up spokes" 1>&3
@@ -218,7 +218,7 @@ export CLUSTER
 
 # Restoring a cluster backup to a standalone appliance is not supported
 if ! $CLUSTER && [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
-  log_error "Error: Snapshot from a GitHub Enterprise cluster cannot be restored to a standalone appliance. Aborting." >&2
+  echo  "Error: Snapshot from a GitHub Enterprise cluster cannot be restored to a standalone appliance. Aborting." >&2
   exit 1
 fi
 
@@ -230,7 +230,7 @@ fi
 # Figure out if this appliance is in a replication pair
 if ghe-ssh "$GHE_HOSTNAME" -- \
   "[ -f '$GHE_REMOTE_ROOT_DIR/etc/github/repl-state' ]"; then
-  log_error "Error: Restoring to an appliance with replication enabled is not supported. Please teardown replication before restoring." >&2
+  echo  "Error: Restoring to an appliance with replication enabled is not supported. Please teardown replication before restoring." >&2
   exit 1
 fi
 
@@ -295,7 +295,7 @@ update_restore_status "restoring"
 # Make sure the GitHub appliance is in maintenance mode.
 if $instance_configured; then
   if ! ghe-maintenance-mode-status "$GHE_HOSTNAME"; then
-    log_error "Error: $GHE_HOSTNAME must be put in maintenance mode before restoring. Aborting." 1>&2
+    echo  "Error: $GHE_HOSTNAME must be put in maintenance mode before restoring. Aborting." 1>&2
     exit 1
   fi
 fi
@@ -307,7 +307,7 @@ RELEASE_VERSION=$(ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --get core.package-vers
 # mismatches in the secrets needed for Actions which ultimately results in Actions not working properly. Note: xargs is to remove whitespace
 ACTIONS_ENABLED_IN_BACKUP=$(git config -f $GHE_RESTORE_SNAPSHOT_PATH/settings.json --bool app.actions.enabled | xargs)
 if [[ $ACTIONS_ENABLED_IN_BACKUP != true ]] && ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-    log_error "Restoring a backup with Actions disabled onto an appliance with Actions enabled is not supported." >&2
+    echo  "Restoring a backup with Actions disabled onto an appliance with Actions enabled is not supported." >&2
     exit 1
 fi
 
@@ -318,15 +318,15 @@ if [ -d "$GHE_RESTORE_SNAPSHOT_PATH/mssql" ] || [ -d "$GHE_RESTORE_SNAPSHOT_PATH
     ac_db_ghe=$(echo 'ghe-mssql-console -y -n -q "SELECT name FROM sys.databases" | grep -i "ArtifactCache" | wc -l | tr -d " "' | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
     ac_db_snapshot=$(find "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/mssql/" -maxdepth 1 -name 'ArtifactCache*.bak' | wc -l | tr -d " ")
     if [[ $ac_db_ghe -gt 0  &&  $ac_db_snapshot -eq 0 ]]; then
-      log_error "$GHE_HOSTNAME has Actions Cache service enabled but no Actions Cache data is present in snapshot to restore. Aborting \n Please disable Actions cache service in $GHE_HOSTNAME and retry\nTo disable Actions Cache service run as admin: ghe-actions-cache-disable" 1>&2
+      echo  "$GHE_HOSTNAME has Actions Cache service enabled but no Actions Cache data is present in snapshot to restore. Aborting \n Please disable Actions cache service in $GHE_HOSTNAME and retry\nTo disable Actions Cache service run as admin: ghe-actions-cache-disable" 1>&2
       exit 1
     fi
     if [[ $ac_db_ghe -eq 0  &&  $ac_db_snapshot -gt 0 && ! $RESTORE_SETTINGS ]]; then
-      log_error "$GHE_HOSTNAME has Actions Cache service disabled but the snapshot is attempting to restore data for the service. Aborting. \n Please enable Actions cache service in $GHE_HOSTNAME and retry \n To enable Actions Cache service run as admin: ghe-actions-cache-enable" 1>&2
+      echo  "$GHE_HOSTNAME has Actions Cache service disabled but the snapshot is attempting to restore data for the service. Aborting. \n Please enable Actions cache service in $GHE_HOSTNAME and retry \n To enable Actions Cache service run as admin: ghe-actions-cache-enable" 1>&2
       exit 1
     fi
   else
-    log_error "$GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting. \n Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@$RELEASE_VERSION/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled" 1>&2
+    echo  "$GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting. \n Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@$RELEASE_VERSION/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled" 1>&2
     exit 1
   fi
 fi
@@ -335,7 +335,7 @@ fi
 bm_init > /dev/null
 
 ghe-backup-store-version  ||
-log_warn "Warning: storing backup-utils version remotely failed."
+echo  "Warning: storing backup-utils version remotely failed."
 
 # Stop cron and timerd, as scheduled jobs may disrupt the restore process.
 echo  "Stopping cron and github-timerd ..."
@@ -433,7 +433,7 @@ if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
 
   echo  "Restoring Actions data ..."
   ghe-restore-actions "$GHE_HOSTNAME" 1>&3
-  log_warn "* WARNING: Every self-hosted Actions runner that communicates with the restored GHES server must be restarted or reconfigured in order to continue functioning. \n See https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners for more details on how to reconfigure self-hosted Actions runners."
+  echo  "* WARNING: Every self-hosted Actions runner that communicates with the restored GHES server must be restarted or reconfigured in order to continue functioning. \n See https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners for more details on how to reconfigure self-hosted Actions runners."
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.minio.enabled'; then
@@ -479,7 +479,7 @@ fi
 if [ -f "$GHE_RESTORE_SNAPSHOT_PATH"/es-scan-complete ]; then
   echo  "Restoring Elasticsearch audit log migration sentinel file ..." 1>&3
   if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo touch $GHE_REMOTE_DATA_USER_DIR/common/es-scan-complete"; then
-    log_error "Failed to restore Elasticsearch audit log migration sentinel file." 1>&3
+    echo  "Failed to restore Elasticsearch audit log migration sentinel file." 1>&3
   fi
 fi
 
