Fix indentation, make output more similar to original output

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -30,19 +30,19 @@ if ! ghe-ssh $options "$host" -- true; then
 fi
 
 if ! ghe-ssh $options "$host" -- test -f "$metadata_file"; then
-  echo "Error: $metadata on '$host' doesn't exist, maybe this isn't a GitHub appliance?" 1>&2
-  exit 2
+    echo "Error: $metadata on '$host' doesn't exist or this isn't a GitHub appliance." 1>&2
+    exit 2
 fi
 
 # SSH to the GHE host and grab metadata file to check SSH connectivity
 if ! metadata="$(ghe-ssh $options "$host" -- "cat '$metadata_file'")"; then
-    echo "Error: failed to read $metadata_file on '$host'. Maybe this isn't a GitHub appliance?" 1>&2
+    echo "Error: failed to read $metadata_file on '$host' or this isn't a GitHub appliance." 1>&2
     exit 2
 fi
 
 version=$(echo "$metadata" | grep version | cut -d'"' -f4)
 if [ -z "$version" ]; then
-    echo "Error: failed to version from $metadata_file on '$host'. Maybe this isn't a GitHub appliance?" 1>&2
+    echo "Error: failed to version from $metadata_file on '$host' or this isn't a GitHub appliance." 1>&2
     exit 2
 fi
 
