Update restore status before importing host keys
Works around the issue where you can't ssh after restoring the host
keys that's super annoying.

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -189,10 +189,14 @@ if [ "$GHE_VERSION_MAJOR" -ge 2 ]; then
     ghe-ssh "$GHE_HOSTNAME" -- "sudo ghe-config-apply" 1>&3
 fi
 
+# Update the remote status to "complete". This has to happen before importing
+# ssh host keys because subsequent commands will fail due to the host key
+# changing otherwise.
+trap "" EXIT
+update_restore_status "complete"
+
 echo "Restoring SSH host keys ..."
 ghe-ssh "$GHE_HOSTNAME" -- 'ghe-import-ssh-host-keys' < "$GHE_RESTORE_SNAPSHOT_PATH/ssh-host-keys.tar" 1>&3
 
-trap "" EXIT
-update_restore_status "complete"
 echo "Completed restore of $GHE_HOSTNAME from snapshot $GHE_RESTORE_SNAPSHOT"
-echo "Visit https://$hostname/setup/settings to review appliance configuration and disable maintenance mode."
+echo "Visit https://$hostname/setup/settings to review appliance configuration."
