move code lower after ssh is resolved with port

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -41,22 +41,6 @@ done
 # $GHE_HOSTNAME configured in backup.config when not present.
 host="${1:-$GHE_HOSTNAME}"
 
-CLUSTER=false
-if ghe-ssh "$host" -- \
-  "[ -f '$GHE_REMOTE_ROOT_DIR/etc/github/cluster' ]"; then
-  CLUSTER=true
-fi
-
-if "$CLUSTER"; then
-  node_version_list=$(ghe-ssh "$host" ghe-cluster-each -- ghe-version)
-  distinct_versions=$(echo "$node_version_list" | awk '{split($0, a, ":"); print a[2]}' | awk '{print $4}' | uniq | wc -l)
-  if [ "$distinct_versions" -ne 1 ]; then
-    echo "$node_version_list" 1>&2
-    echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&2
-    exit 1
-  fi
-fi
-
 # Options to pass to SSH during connection check
 options="
   -o PasswordAuthentication=no
@@ -98,6 +82,23 @@ if [ $rc -ne 0 ]; then
 
   esac
   exit $rc
+fi
+
+CLUSTER=false
+if ghe-ssh "$host" -- \
+  "[ -f '$GHE_REMOTE_ROOT_DIR/etc/github/cluster' ]"; then
+  CLUSTER=true
+fi
+
+# ensure all nodes in the cluster are running the same version
+if "$CLUSTER"; then
+  node_version_list=$(ghe-ssh "$host" ghe-cluster-each -- ghe-version)
+  distinct_versions=$(echo "$node_version_list" | awk '{split($0, a, ":"); print a[2]}' | awk '{print $4}' | uniq | wc -l)
+  if [ "$distinct_versions" -ne 1 ]; then
+    echo "$node_version_list" 1>&2
+    echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&2
+    exit 1
+  fi
 fi
 
 version=$(echo "$output" | grep "GitHub Enterprise" | awk '{print $NF}')
