Add comments

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -144,58 +144,63 @@ if [ -z "$supported" ]; then
   exit 1
 fi
 
-# Bring in the requirements file
-min_rsync=""
-min_openssh=""
-min_jq=""
-# shellcheck source=share/github-backup-utils/requirements.txt
-. "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/requirements.txt"
+if [[ "$CALLING_SCRIPT" == "ghe-backup" ]]; then
+  # Bring in the requirements file
+  min_rsync=""
+  min_openssh=""
+  min_jq=""
+  # shellcheck source=share/github-backup-utils/requirements.txt
+  . "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/requirements.txt"
 
-#source disk size file
-# shellcheck source=share/github-backup-utils/ghe-rsync-size.sh
-. "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/ghe-rsync-size.sh"
+  #source disk size file
+  # shellcheck source=share/github-backup-utils/ghe-rsync-size.sh
+  . "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/ghe-rsync-size.sh"
 
-#Display dir requirements for repositories and mysql
-available_space=$(df -B 1k $GHE_DATA_DIR | awk 'END{printf "%.0f", $4 * 1024}') 
-echo "Available space: $available_space" 1>&2
+  #Display dir requirements for repositories and mysql
+  echo "Checking host for sufficient space for a backup..." 1>&2
+  available_space=$(df -B 1k $GHE_DATA_DIR | awk 'END{printf "%.0f", $4 * 1024}') 
+  printf "Available space: %d MB. We recommend allocating at least 5x the amount of storage allocated to the primary GitHub appliance for historical snapshots and growth over time.\n" "$((available_space / 1024 ** 2))" 1>&2
 
-repos_disk_size=$(transfer_size repositories /tmp)
-pages_disk_size=$(transfer_size pages /tmp)
-es_disk_size=$(transfer_size elasticsearch /tmp)
-stor_disk_size=$(transfer_size storage /tmp)
-minio_disk_size=$(transfer_size minio /tmp)
-mysql_disk_size=$(transfer_size mysql /tmp)
+  repos_disk_size=$(transfer_size repositories /tmp)
+  pages_disk_size=$(transfer_size pages /tmp)
+  es_disk_size=$(transfer_size elasticsearch /tmp)
+  stor_disk_size=$(transfer_size storage /tmp)
+  minio_disk_size=$(transfer_size minio /tmp)
+  mysql_disk_size=$(transfer_size mysql /tmp)
+  actions_disk_size=$(transfer_size actions /tmp)
+  mssql_disk_size=$(transfer_size mssql /tmp)
 
-min_disk_req=$(( $(echo "$repos_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$pages_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$es_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$stor_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$minio_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$mysql_disk_size" | awk '{printf "%.0f", $1/2}') ))
-echo "repositories = $repos_disk_size, pages: $pages_disk_size, elasticsearch: $es_disk_size, storage: $stor_disk_size, minio: $minio_disk_size, mysql: $mysql_disk_size" 1>&2
-echo "min_disk_required for backup = $min_disk_req bytes" 1>&2
+  min_disk_req=$(( $(echo "$repos_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$pages_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$es_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$stor_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$minio_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$mysql_disk_size" | awk '{printf "%.0f", $1/2}') + $(echo "$actions_disk_size" | awk '{printf "%.0f", $1}') + $(echo "$mssql_disk_size" | awk '{printf "%.0f", $1}') ))
+  echo "Data transfer size for - repositories = $repos_disk_size, pages: $pages_disk_size, elasticsearch: $es_disk_size, storage: $stor_disk_size, minio: $minio_disk_size, mysql: $mysql_disk_size, actions: $actions_disk_size, mssql: $mssql_disk_size" 1>&2
+  printf "min_disk_required for this backup is at least %d MB\n" "$((min_disk_req / 1024 ** 2))" 1>&2
 
-if [[ $available_space -lt $min_disk_req ]]; then
-  echo "There is not enough disk space for the backup. Please allocate more space and continue." 1>&2
-  exit 1
+  if [[ $available_space -lt $min_disk_req ]]; then
+    echo "There is not enough disk space for the backup. Please allocate more space and continue." 1>&2
+    exit 1
+  fi
+
+  #Check rsync, openssh & jq versions
+  rsync_version=$(rsync --version | grep 'version' | awk '{print $3}')
+  if awk "BEGIN {exit !($rsync_version < $min_rsync)}" &> /dev/null; then
+    echo "rsync version $rsync_version in backup-host does not meet minimum requirements." 1>&2
+    echo "Please make sure you have the minimum required version of rsync: $min_rsync installed" 1>&2
+    exit 1
+  fi
+
+  ssh_version=$(ssh -V 2>&1 | awk '{print $1}'|grep -oPm 1 '[\d\.]+' |head -1)
+  if awk "BEGIN {exit !($ssh_version < $min_openssh)}" &> /dev/null; then
+    echo "openSSH version $ssh_version in backup-host does not meet minimum requirements." 1>&2
+    echo "Please make sure the minimum required version of openSSH: $min_openssh is installed" 1>&2
+    exit 1
+  fi
+
+  jq_version=$(jq --version |awk -F\- '{print $2}')
+  if awk "BEGIN {exit !($jq_version < $min_jq)}" &> /dev/null; then
+    echo "jq version $jq_version in backup-host does not meet minimum requirements." 1>&2
+    echo "Please make sure you have the minimum required version of jq: $min_jq installed" 1>&2
+    exit 1
+  fi
+  echo "Backup host meets minimum software requirements for OpenSSH, rsync and jq." 1>&2
 fi
-
-#Check rsync, openssh & jq versions
-rsync_version=$(rsync --version | grep 'version' | awk '{print $3}')
-if awk "BEGIN {exit !($rsync_version < $min_rsync)}" &> /dev/null; then
-  echo "rsync version $rsync_version in backup-host does not meet minimum requirements." 1>&2
-  echo "Please make sure you have the minimum required version of rsync: $min_rsync installed" 1>&2
-  exit 1
-fi
-
-ssh_version=$(ssh -V 2>&1 | awk '{print $1}'|grep -oPm 1 '[\d\.]+' |head -1)
-if awk "BEGIN {exit !($ssh_version < $min_openssh)}" &> /dev/null; then
-  echo "openSSH version $ssh_version in backup-host does not meet minimum requirements." 1>&2
-  echo "Please make sure the minimum required version of openSSH: $min_openssh is installed" 1>&2
-  exit 1
-fi
-
-jq_version=$(jq --version |awk -F\- '{print $2}')
-if awk "BEGIN {exit !($jq_version < $min_jq)}" &> /dev/null; then
-  echo "jq version $jq_version in backup-host does not meet minimum requirements." 1>&2
-  echo "Please make sure you have the minimum required version of jq: $min_jq installed" 1>&2
-  exit 1
-fi
-
 
 echo "Connect $hostname:$port OK (v$version)"
