Block on pre-2.11 instances

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -90,4 +90,12 @@ if [ -z "$version" ]; then
     exit 2
 fi
 
+# backup-utils 2.13 onwards only has support for 2.11 and newer versions.
+if ! echo "v$version" | grep -Eq "v2\.1[1-9]|v[3-9]"; then
+  echo "Error: old release of GitHub Enterprise detected." 1>&2
+  echo "Backup Utilities $BACKUP_UTILS_VERSION requires GitHub Enterprise v2.11 or newer." 1>&2
+  echo "Please update your GitHub Enterprise appliance of use backup-utils v2.11.4." 1>&2
+  exit 1
+fi
+
 echo "Connect $hostname:$port OK (v$version)"
