Not to compress for binary backup

diff --git a/bin/ghe-backup b/bin/ghe-backup
--- a/bin/ghe-backup
+++ b/bin/ghe-backup
@@ -176,8 +176,16 @@ bm_end "ghe-export-ssh-host-keys"
 
 echo "Backing up MySQL database ..."
 bm_start "ghe-export-mysql"
-echo 'set -o pipefail; ghe-export-mysql | pigz' |
+export_command="ghe-export-mysql"
+if ! is_binary_backup; then
+  # binary backup is already compressed
+  export_command+=" | pigz"
+fi
+echo "set -o pipefail; ${export_command}" |
 ghe-ssh "$GHE_HOSTNAME" -- /bin/bash > mysql.sql.gz || failures="$failures mysql"
+if is_binary_backup; then
+  echo "NO_ADDITIONAL_COMPRESSION" > mysql-binary-backup-sentinel
+fi
 bm_end "ghe-export-mysql"
 
 echo "Backing up Redis database ..."
