Don't attempt stale node cleanup on unconfigured instances
Unconfigured instances may have pending database migrations that could
cause the required database queries to fail. We can't predict which
migrations will affect the cleanup so the best option is to not run them
on unconfigured instances.

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -341,8 +341,8 @@ else
   fi
 fi
 
-# Clean up all stale replicas
-if ! $CLUSTER; then
+# Clean up all stale replicas on configured instances.
+if ! $CLUSTER && $instance_configured; then
   restored_uuid=$(cat $GHE_RESTORE_SNAPSHOT_PATH/uuid)
   other_nodes=$(echo "
     set -o pipefail; \
