Only check that it's readable/exists with cat

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -22,11 +22,7 @@ options="
 # The location of metadata file on the remote side.
 metadata_file="$GHE_REMOTE_DATA_DIR/enterprise/chef_metadata.json"
 
-metadata_commands="
-    [ -f '$metadata_file' ] || exit 101
-    cat '$metadata_file' || exit 102
-"
-if ! metadata=$(echo "$metadata_commands" | ghe-ssh $options $host -- /bin/sh); then
+if ! metadata=$(echo "$metadata_commands" | ghe-ssh $options $host -- cat "$metadata_file"); then
     rc=$?
     case $rc in
         255)
@@ -34,14 +30,8 @@ if ! metadata=$(echo "$metadata_commands" | ghe-ssh $options $host -- /bin/sh); 
             echo "Note that your SSH key needs to be setup on $host as described in:" 1>&2
             echo "* https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access" 1>&2
             ;;
-        101)
-            echo "Error: missing Enterprise fingerprint on '$host' or this isn't a GitHub appliance." 1>&2
-            ;;
-        102)
-            echo "Error: couldn't read Enterprise fingerprint on '$host'" 1>&2
-            ;;
         *)
-            echo "Error: unexpected problem verifying Enterprise fingerprint on '$host'" 1>&2
+            echo "Error: couldn't read Enterprise fingerprint on '$host' or this isn't a GitHub appliance." 1>&2
             ;;
     esac
     exit $rc
