Add confirmation prompt when restoring BYODB snapshot to unconfigured instance

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -192,6 +192,32 @@ if $instance_configured && ! $FORCE; then
   echo
 fi
 
+# Prompt to verify that restoring BYODB snapshot to unconfigured instance
+# will result in BYODB connection information being restored as well.
+if ! $instance_configured && is_external_database_snapshot; then
+  echo
+  echo "WARNING: Restoring the snapshot ${GHE_RESTORE_SNAPSHOT} will also restore the external MySQL database connection information."
+  echo "         If the appliance the snapshot was taken from is still online, this could result in two GHES appliances writing to the same MySQL database."
+  echo "Please verify that this is understood before continuing."
+  printf "Type 'yes' to continue: "
+
+  while read -r response; do
+    case $response in
+      yes|Yes|YES)
+        break
+        ;;
+      '')
+        printf "Type 'yes' to continue: "
+        ;;
+      *)
+        echo "Restore aborted." 1>&2
+        exit 1
+        ;;
+    esac
+  done
+  echo
+fi
+
 # Log restore start message locally and in /var/log/syslog on remote instance
 echo "Starting restore of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION from snapshot $GHE_RESTORE_SNAPSHOT"
 ghe_remote_logger "Starting restore from $(hostname) with backup-utils v$BACKUP_UTILS_VERSION / snapshot $GHE_RESTORE_SNAPSHOT ..."
