More formatting

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -159,8 +159,7 @@ if [[ "$CALLING_SCRIPT" == "ghe-backup" ]]; then
   #Display dir requirements for repositories and mysql
   echo "Checking host for sufficient space for a backup..." 1>&2
   available_space=$(df -B 1k $GHE_DATA_DIR | awk 'END{printf "%.0f", $4 * 1024}') 
-  echo -e "Available space: $((available_space / (1024 ** 2))) MB\n" 1>&2
-  echo -e "We recommend allocating at least 5x the amount of storage allocated to the primary GitHub appliance for historical snapshots and growth over time.\n" 1>&2
+  echo "We recommend allocating at least 5x the amount of storage allocated to the primary GitHub appliance for historical snapshots and growth over time." 1>&2
 
   repos_disk_size=$(transfer_size repositories /tmp)
   pages_disk_size=$(transfer_size pages /tmp)
@@ -172,6 +171,8 @@ if [[ "$CALLING_SCRIPT" == "ghe-backup" ]]; then
   mssql_disk_size=$(transfer_size mssql /tmp)
 
   min_disk_req=$((repos_disk_size + pages_disk_size + es_disk_size + stor_disk_size + minio_disk_size + mysql_disk_size + actions_disk_size + mssql_disk_size))
+  echo "Available space: $((available_space / (1024 ** 2))) MB" 1>&2
+  echo -e "Min Disk required for this backup is at least $min_disk_req MB\n" 1>&2
 
 cat <<DATA_TRANSFER_SIZE 1>&2
 ### Data Transfer Sizes 
@@ -184,7 +185,6 @@ mysql: $mysql_disk_size MB
 actions: $actions_disk_size MB
 mssql: $mssql_disk_size MB
 DATA_TRANSFER_SIZE
-  printf "min_disk_required for this backup is at least %d MB\n" "$min_disk_req" 1>&2
 
   if [[ $available_space -lt $min_disk_req ]]; then
     echo "There is not enough disk space for the backup. Please allocate more space and continue." 1>&2
@@ -192,6 +192,7 @@ DATA_TRANSFER_SIZE
   fi
 
   #Check rsync, openssh & jq versions
+  echo "### Software versions" 1>&2
   rsync_version=$(rsync --version | grep 'version' | awk '{print $3}')
   if awk "BEGIN {exit !($rsync_version < $min_rsync)}" &> /dev/null; then
     echo "rsync version $rsync_version in backup-host does not meet minimum requirements." 1>&2
