restoring

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -485,9 +485,9 @@ fi
 # Restore the audit log migration sentinel file, if it exists in the snapshot
 if [ -f "$GHE_RESTORE_SNAPSHOT_PATH"/es-scan-complete ]; then
   log_info "Restoring Elasticsearch audit log migration sentinel file ..." 1>&3
-  # if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo touch $GHE_REMOTE_DATA_USER_DIR/common/es-scan-complete"; then
-  #   log_error "Failed to restore Elasticsearch audit log migration sentinel file." 1>&3
-  # fi
+  if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo touch $GHE_REMOTE_DATA_USER_DIR/common/es-scan-complete"; then
+    log_error "Failed to restore Elasticsearch audit log migration sentinel file." 1>&3
+  fi
 fi
 
 # Restore exported audit logs to 2.12.9 and newer single nodes and
