Clean up stale HA nodes

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -341,6 +341,16 @@ else
   fi
 fi
 
+# Clean up all stale replicas
+if ! $CLUSTER; then
+  inactive_nodes=$(echo "ghe-spokes server show inactive --json | jq -r '.[] | select(.host | contains(\"git-server\")).host' | sed 's/^git-server-//g'" | ghe-ssh "$GHE_HOSTNAME" -- /bin/bash)
+  if [ -n "$inactive_nodes" ]; then
+    echo "Cleaning up stale nodes ..."
+    for uuid in $inactive_nodes; do
+      ghe-ssh "$GHE_HOSTNAME" -- "/usr/local/share/enterprise/ghe-cluster-cleanup-node $uuid" 1>&3
+    done
+  fi
+fi
 
 # Update the remote status to "complete". This has to happen before importing
 # ssh host keys because subsequent commands will fail due to the host key
