Also detect connection refused on 22

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -31,7 +31,12 @@ set -e
 if [ $rc -ne 0 ]; then
     case $rc in
         255)
-            echo "Error: ssh to '$host' failed" 1>&2
+            if echo "$output" | grep -i -q "port 22: connection refused"; then
+                exec "$0" "$hostname:122"
+            fi
+
+            echo "$output" 1>&2
+            echo "Error: ssh connection with '$host' failed" 1>&2
             echo "Note that your SSH key needs to be setup on $host as described in:" 1>&2
             echo "* https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access" 1>&2
             ;;
