add cluster check

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -41,22 +41,30 @@ done
 # $GHE_HOSTNAME configured in backup.config when not present.
 host="${1:-$GHE_HOSTNAME}"
 
-node_version_list=$(ghe-ssh "$host" ghe-cluster-each -- ghe-version)
-first_node_version=""
-(
-  IFS=$'\n'
-  for node_version in $node_version_list; do
-    echo "$node_version"
-    if [ -z "$first_node_version" ]; then
-      first_node_version=$(echo "$node_version" | cut -f2 -d":")
-    fi
-    current_node_version=$(echo "$node_version" | cut -f2 -d":")
-    if [ "$first_node_version" != "$current_node_version" ]; then
-      echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&2
-      exit 1
-    fi
-  done
-)
+CLUSTER=false
+if ghe-ssh "$host" -- \
+  "[ -f '$GHE_REMOTE_ROOT_DIR/etc/github/cluster' ]"; then
+  CLUSTER=true
+fi
+
+if "$CLUSTER"; then
+  node_version_list=$(ghe-ssh "$host" ghe-cluster-each -- ghe-version)
+  first_node_version=""
+  (
+    IFS=$'\n'
+    for node_version in $node_version_list; do
+      echo "$node_version"
+      if [ -z "$first_node_version" ]; then
+        first_node_version=$(echo "$node_version" | cut -f2 -d":")
+      fi
+      current_node_version=$(echo "$node_version" | cut -f2 -d":")
+      if [ "$first_node_version" != "$current_node_version" ]; then
+        echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&2
+        exit 1
+      fi
+    done
+  )
+fi
 
 # Options to pass to SSH during connection check
 options="
