Stop restore when a backup without Actions is being restored onto an appliance with Actions enabled (#946)
* throw error and abort when restoring a backup with Actions disabled onto an appliance with Actions enabled

* set ACTIONS_ENABLED_IN_BACKUP to false if the value is not found in settings.json

* use git config to grab app.actions.enabled directly

* add bash function to enable and disable actions in settings.json

* enable actions in settings for part of other tests that require it

* use git config to set initial value for actions in settings.json

* empty settings.json before using git config

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -285,6 +285,14 @@ fi
 # Get GHES release version in major.minor format
 RELEASE_VERSION=$(ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --get core.package-version' | cut -d '.' -f 1,2)
 
+# If the backup being restored is from an appliance with Actions disabled, restoring it onto an appliance with Actions enabled will cause
+# mismatches in the secrets needed for Actions which ultimately results in Actions not working properly. Note: xargs is to remove whitespace
+ACTIONS_ENABLED_IN_BACKUP=$(git config -f $GHE_RESTORE_SNAPSHOT_PATH/settings.json --bool app.actions.enabled | xargs)
+if [[ $ACTIONS_ENABLED_IN_BACKUP != true ]] && ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
+    echo "Error: Restoring a backup with Actions disabled onto an appliance with Actions enabled is not supported." >&2
+    exit 1
+fi
+
 # Make sure the GitHub appliance has Actions enabled if the snapshot contains Actions data.
 # If above is true, also check if ac is present in appliance then snapshot should also contains ac databases
 if [ -d "$GHE_RESTORE_SNAPSHOT_PATH/mssql" ] || [ -d "$GHE_RESTORE_SNAPSHOT_PATH/actions" ]; then
