Use pigz instead of gzip in backup-util

diff --git a/bin/ghe-backup b/bin/ghe-backup
--- a/bin/ghe-backup
+++ b/bin/ghe-backup
@@ -176,7 +176,7 @@ bm_end "ghe-export-ssh-host-keys"
 
 echo "Backing up MySQL database ..."
 bm_start "ghe-export-mysql"
-echo 'set -o pipefail; ghe-export-mysql | gzip' |
+echo 'set -o pipefail; ghe-export-mysql | pigz' |
 ghe-ssh "$GHE_HOSTNAME" -- /bin/bash > mysql.sql.gz || failures="$failures mysql"
 bm_end "ghe-export-mysql"
 
