more tweaks

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -87,7 +87,7 @@ while true; do
 done
 
 start_cron () {
-  log_info "Starting cron ..." 1>&3
+  log_info "Starting cron ..." 
   if $CLUSTER; then
     if ! ghe-ssh "$GHE_HOSTNAME" -- "ghe-cluster-each -- sudo service cron start" ; then
       log_warn "Failed to start cron on one or more nodes"
@@ -100,7 +100,7 @@ start_cron () {
 }
 
 cleanup () {
-  log_info " Exiting, cleaning up ..." 1>&3
+  log_info " Exiting, cleaning up ..." 
   if [ -n "$1" ]; then
     update_restore_status "$1"
   fi
@@ -122,7 +122,7 @@ cleanup () {
   fi
 
   # Cleanup SSH multiplexing
-  log_info "Cleaning up SSH multiplexing ..." 1>&3
+  log_info "Cleaning up SSH multiplexing ..." 
   if ! ghe-ssh --clean ; then
     log_warn "Failed to clean up SSH multiplexing"
   fi
@@ -130,7 +130,7 @@ cleanup () {
   log_info "Removing in-progress file ..." 1>&3
 
   if ! rm -f ${GHE_DATA_DIR}/in-progress-restore ; then
-    log_warn "Failed to remove in-progress file"
+    log_warn "Failed to remove in-progress file" 1>&3
   fi
 }
 
@@ -318,20 +318,15 @@ if [ -d "$GHE_RESTORE_SNAPSHOT_PATH/mssql" ] || [ -d "$GHE_RESTORE_SNAPSHOT_PATH
     ac_db_ghe=$(echo 'ghe-mssql-console -y -n -q "SELECT name FROM sys.databases" | grep -i "ArtifactCache" | wc -l | tr -d " "' | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
     ac_db_snapshot=$(find "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/mssql/" -maxdepth 1 -name 'ArtifactCache*.bak' | wc -l | tr -d " ")
     if [[ $ac_db_ghe -gt 0  &&  $ac_db_snapshot -eq 0 ]]; then
-      log_error "$GHE_HOSTNAME has Actions Cache service enabled but no Actions Cache data is present in snapshot to restore. Aborting" \
-      "\n""Please disable Actions cache service in $GHE_HOSTNAME and retry" \
-      "\n""To disable Actions Cache service run as admin: ghe-actions-cache-disable" 1>&2
+      log_error "$GHE_HOSTNAME has Actions Cache service enabled but no Actions Cache data is present in snapshot to restore. Aborting \n Please disable Actions cache service in $GHE_HOSTNAME and retry\nTo disable Actions Cache service run as admin: ghe-actions-cache-disable" 1>&2
       exit 1
     fi
     if [[ $ac_db_ghe -eq 0  &&  $ac_db_snapshot -gt 0 && ! $RESTORE_SETTINGS ]]; then
-      log_error "$GHE_HOSTNAME has Actions Cache service disabled but the snapshot is attempting to restore data for the service. Aborting." \
-      "\n""Please enable Actions cache service in $GHE_HOSTNAME and retry" \
-      "\n""To enable Actions Cache service run as admin: ghe-actions-cache-enable" 1>&2
+      log_error "$GHE_HOSTNAME has Actions Cache service disabled but the snapshot is attempting to restore data for the service. Aborting. \n Please enable Actions cache service in $GHE_HOSTNAME and retry \n To enable Actions Cache service run as admin: ghe-actions-cache-enable" 1>&2
       exit 1
     fi
   else
-    log_error "$GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting." \
-     "\n""Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@$RELEASE_VERSION/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled" 1>&2
+    log_error "$GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting. \n Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@$RELEASE_VERSION/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled" 1>&2
     exit 1
   fi
 fi
@@ -438,8 +433,7 @@ if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
 
   log_info "Restoring Actions data ..."
   ghe-restore-actions "$GHE_HOSTNAME" 1>&3
-  log_warn "* WARNING: Every self-hosted Actions runner that communicates with the restored GHES server must be restarted or reconfigured in order to continue functioning."
-  log_warn "           See https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners for more details on how to reconfigure self-hosted Actions runners."
+  log_warn "* WARNING: Every self-hosted Actions runner that communicates with the restored GHES server must be restarted or reconfigured in order to continue functioning. \n See https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners for more details on how to reconfigure self-hosted Actions runners."
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.minio.enabled'; then
@@ -496,7 +490,7 @@ if $CLUSTER || [ "$(version $GHE_REMOTE_VERSION)" -ge "$(version 2.12.9)" ]; the
     log_info "Skipping restore of audit logs."
   else
     commands+=("
-     echo \"Restoring Audit logs ...\"
+    echo \"Restoring Audit logs ...\"
     ghe-restore-es-audit-log \"$GHE_HOSTNAME\" 1>&3")
   fi
 
@@ -594,7 +588,7 @@ else
   log_info "Restoring Git over SSH host keys ..."
   ghe-ssh "$GHE_HOSTNAME" -- "sudo tar -xpf - -C $GHE_REMOTE_DATA_USER_DIR/common" < "$GHE_RESTORE_SNAPSHOT_PATH/ssh-host-keys.tar" 1>&3
   ghe-ssh "$GHE_HOSTNAME" -- "sudo chown babeld:babeld $GHE_REMOTE_DATA_USER_DIR/common/ssh_host_*" 1>&3
-  log_info "if [ -f /usr/local/share/enterprise/ghe-cluster-config-update ]; then /usr/local/share/enterprise/ghe-cluster-config-update -s; else ghe-cluster-config-update -s; fi" |
+  echo "if [ -f /usr/local/share/enterprise/ghe-cluster-config-update ]; then /usr/local/share/enterprise/ghe-cluster-config-update -s; else ghe-cluster-config-update -s; fi" |
   ghe-ssh "$GHE_HOSTNAME" -- /bin/sh 1>&3
 fi
 
