added ac condition in restore

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -262,11 +262,19 @@ if $instance_configured; then
 fi
 
 # Make sure the GitHub appliance has Actions enabled if the snapshot contains Actions data.
+# It above is true, also check if ac is present in appliance then snapshot should also contains ac databases
 if [ -d "$GHE_RESTORE_SNAPSHOT_PATH/mssql" ] || [ -d "$GHE_RESTORE_SNAPSHOT_PATH/actions" ]; then
-  if ! ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
+  if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
+    ac_in_ghe_status=`echo 'set -o pipefail; ghe-mssql-console -y -n -q "SELECT name from sys.databases where name like \"ArtifactCache%\"" | grep -iq "ArtifactCache"' | ./share/github-backup-utils/ghe-ssh "$GHE_HOSTNAME" /bin/bash; echo $?`
+    ac_in_snapshot_status=`grep -qi "ArtifactCache*" <<< ls $GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/mssql/*.bak; echo $?``
+    if [[ $ac_in_ghe_status -eq 0  &&  $ac_in_snapshot_status -ne 0 ]]; then
+      echo "Error: $GHE_HOSTNAME contains ArtifactCache databases but no ArtifactCache databases are present in snapshot. Aborting" 1>&2
+      echo "Please delete ArtifactCache databases from $GHE_HOSTNAME and retry" 1>&2
+      exit 1
+    fi
+  else
     # Get GHES release version in major.minor format
     RELEASE_VERSION=$(ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --get core.package-version' | cut -d '.' -f 1,2)
-
     echo "Error: $GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting." 1>&2
     echo "Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@$RELEASE_VERSION/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled" 1>&2
     exit 1
