added node version check and fail out if they don't match

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -15,31 +15,47 @@ set -e
 
 while true; do
   case "$1" in
-    -h|--help)
-      export GHE_SHOW_HELP=true
-      shift
-      ;;
-    --version)
-      export GHE_SHOW_VERSION=true
-      shift
-      ;;
-    -*)
-      echo "Error: invalid argument: '$1'" 1>&2
-      exit 1
-      ;;
-    *)
-      break
-      ;;
+  -h | --help)
+    export GHE_SHOW_HELP=true
+    shift
+    ;;
+  --version)
+    export GHE_SHOW_VERSION=true
+    shift
+    ;;
+  -*)
+    echo "Error: invalid argument: '$1'" 1>&2
+    exit 1
+    ;;
+  *)
+    break
+    ;;
   esac
 done
 
 # Bring in the backup configuration
 # shellcheck source=share/github-backup-utils/ghe-backup-config
-. "$( dirname "${BASH_SOURCE[0]}" )/../share/github-backup-utils/ghe-backup-config"
+. "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/ghe-backup-config"
 
 # Use the host provided on the command line if provided, or fallback on the
 # $GHE_HOSTNAME configured in backup.config when not present.
 host="${1:-$GHE_HOSTNAME}"
+
+node_version_list=$(ghe-ssh "$host" ghe-cluster-each -- ghe-version)
+first_node_version=""
+(
+  IFS=$'\n'
+  for node_version in $node_version_list; do
+    if [ -z "$first_node_version" ]; then
+      first_node_version=$(echo "$node_version" | cut -f2 -d":")
+    fi
+    current_node_version=$(echo "$node_version" | cut -f2 -d":")
+    if [ "$first_node_version" != "$current_node_version" ]; then
+      echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&2
+      exit 1
+    fi
+  done
+)
 
 # Options to pass to SSH during connection check
 options="
@@ -59,26 +75,26 @@ set -e
 
 if [ $rc -ne 0 ]; then
   case $rc in
-    255)
-      if echo "$output" | grep -i "port 22: Network is unreachable\|port 22: connection refused\|port 22: no route to host\|ssh_exchange_identification: Connection closed by remote host\|Connection timed out during banner exchange\|port 22: Connection timed out" >/dev/null; then
-        exec "$(basename $0)" "$hostname:122"
-      fi
+  255)
+    if echo "$output" | grep -i "port 22: Network is unreachable\|port 22: connection refused\|port 22: no route to host\|ssh_exchange_identification: Connection closed by remote host\|Connection timed out during banner exchange\|port 22: Connection timed out" >/dev/null; then
+      exec "$(basename $0)" "$hostname:122"
+    fi
 
+    echo "$output" 1>&2
+    echo "Error: ssh connection with '$host' failed" 1>&2
+    echo "Note that your SSH key needs to be setup on $host as described in:" 1>&2
+    echo "* https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access" 1>&2
+    ;;
+  101)
+    echo "Error: couldn't read GitHub Enterprise Server fingerprint on '$host' or this isn't a GitHub appliance." 1>&2
+    ;;
+  1)
+    if [ "${port:-22}" -eq 22 ] && echo "$output" | grep "use port 122" >/dev/null; then
+      exec "$(basename $0)" "$hostname:122"
+    else
       echo "$output" 1>&2
-      echo "Error: ssh connection with '$host' failed" 1>&2
-      echo "Note that your SSH key needs to be setup on $host as described in:" 1>&2
-      echo "* https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access" 1>&2
-      ;;
-    101)
-      echo "Error: couldn't read GitHub Enterprise Server fingerprint on '$host' or this isn't a GitHub appliance." 1>&2
-      ;;
-    1)
-      if [ "${port:-22}" -eq 22 ] && echo "$output" | grep "use port 122" >/dev/null; then
-        exec "$(basename $0)" "$hostname:122"
-      else
-        echo "$output" 1>&2
-      fi
-      ;;
+    fi
+    ;;
 
   esac
   exit $rc
