Working but rough version of changes
Co-authored-by: Chuck Pathanjali <chuckp22@github.com>

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -123,7 +123,7 @@ cleanup () {
   # Cleanup SSH multiplexing
   ghe-ssh --clean
   # Remove in-progress file
-  ghe_restore_finished
+  rm -f ${GHE_DATA_DIR}/.in-progress-restore
 }
 
 # This function's type definition is being passed to a remote host via `ghe-ssh` but is not used locally.
@@ -154,6 +154,25 @@ cleanup_cluster_nodes() {
 # Check to make sure moreutils parallel is installed and working properly
 ghe_parallel_check
 
+# ghe_restore_check
+if [ -h ${GHE_DATA_DIR}/.in-progress-restore ]; then
+  echo "Error: detected a restore already in progress from a previous version of ghe-restore." 1>&2
+  echo "If there is no restore in progress anymore, please remove" 1>&2
+  echo "the $GHE_DATA_DIR/in-progress-restore file." 1>&2
+  exit 1
+fi
+
+echo "${GHE_DATA_DIR}/.in-progress-restore"
+if [ -f ${GHE_DATA_DIR}/.in-progress-restore ]; then
+  progress=$(cat ${GHE_DATA_DIR}/.in-progress-restore)
+  snapshot=$(echo "$progress" | cut -d ' ' -f 1)
+  pid=$(echo "$progress" | cut -d ' ' -f 2)
+    echo "Error: A restore of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
+    echo "If PID $pid is not a process related to the restore utilities, please remove" 1>&2
+    echo "the $GHE_DATA_DIR/in-progress-restore file and try again." 1>&2
+    exit 1
+  fi
+
 # Check to make sure a restore or backup is not in progress
 
 
@@ -175,8 +194,23 @@ GHE_RESTORE_SNAPSHOT_PATH="$(ghe-restore-snapshot-path "$snapshot_id")"
 GHE_RESTORE_SNAPSHOT=$(basename "$GHE_RESTORE_SNAPSHOT_PATH")
 export GHE_RESTORE_SNAPSHOT
 
-ghe_backup_check
-ghe_restore_check
+#ghe_backup_check
+if [ -h ${GHE_DATA_DIR}/.in-progress ]; then
+  echo "Error: detected a backup already in progress from a previous version of ghe-backup." 1>&2
+  echo "If there is no backup in progress anymore, please remove" 1>&2
+  echo "the $GHE_DATA_DIR/.in-progress-backup file." 1>&2
+  exit 1
+fi
+
+if [ -f ${GHE_DATA_DIR}/.in-progress ]; then
+	progress=$(cat ${GHE_DATA_DIR}/.in-progress) 
+  snapshot=$(echo "$progress" | cut -d ' ' -f 1)
+  pid=$(echo "$progress" | cut -d ' ' -f 2)
+    echo "Error: A backup of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
+    echo "If PID $pid is not a process related to the backup utilities, please remove" 1>&2
+    echo "the $GHE_DATA_DIR/.in-progress file and try again." 1>&2
+    exit 1
+  fi
 
 # Detect if the backup we are restoring has a leaked ssh key
 echo "Checking for leaked keys in the backup snapshot that is being restored ..."
@@ -260,8 +294,13 @@ START_TIME=$(date +%s)
 echo 'Start time:' $START_TIME
 echo "Starting restore of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION from snapshot $GHE_RESTORE_SNAPSHOT"
 ghe_remote_logger "Starting restore from $(hostname) with backup-utils v$BACKUP_UTILS_VERSION / snapshot $GHE_RESTORE_SNAPSHOT ..."
-ghe_restore_started $START_TIME
+# Create an in-progress-restore file to prevent simultaneous backup or restore runs
+echo "${START_TIME} $$" > ${GHE_DATA_DIR}/.in-progress-restore
 
+sleep 120
+rm -f ${GHE_DATA_DIR}/.in-progress-restore
+echo "finished with fake restore"
+exit 1
 # Keep other processes on the VM or cluster in the loop about the restore status.
 #
 # Other processes will look for these states:
@@ -588,7 +627,7 @@ echo 'End time:' $END_TIME
 echo 'Runtime:' $(($END_TIME - $START_TIME)) 'seconds'
 
 echo "Restore of $GHE_HOSTNAME from snapshot $GHE_RESTORE_SNAPSHOT finished."
-ghe_restore_finished
+rm -f ${GHE_DATA_DIR}/.in-progress-restore
 
 if ! $instance_configured; then
   echo "To complete the restore process, please visit https://$hostname/setup/settings to review and save the appliance configuration."
