reintroducing logging into the file

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -100,13 +100,13 @@ start_cron () {
 }
 
 cleanup () {
-  echo  " Exiting, cleaning up ..." 
+  log_info " Exiting, cleaning up ..." 
   if [ -n "$1" ]; then
     update_restore_status "$1"
   fi
 
   if $ACTIONS_STOPPED && ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-    echo  "Restarting Actions after restore ..."
+    log_info  "Restarting Actions after restore ..."
     # In GHES 3.3+, ghe-actions-start no longer has a -f (force) flag. In GHES 3.2 and below, we must provide the
     # force flag to make sure it can start in maintenance mode. Use it conditionally based on whether it exists
     # in the --help output
@@ -122,15 +122,15 @@ cleanup () {
   fi
 
   # Cleanup SSH multiplexing
-  echo  "Cleaning up SSH multiplexing ..." 
+  log_info  "Cleaning up SSH multiplexing ..." 
   if ! ghe-ssh --clean ; then
-    echo  "Failed to clean up SSH multiplexing"
+    log_info  "Failed to clean up SSH multiplexing"
   fi
   # Remove in-progress file
-  echo  "Removing in-progress file ..." 1>&3
+  log_info  "Removing in-progress file ..." 1>&3
 
   if ! rm -f ${GHE_DATA_DIR}/in-progress-restore ; then
-    echo  "Failed to remove in-progress file" 1>&3
+    log_error  "Failed to remove in-progress file" 1>&3
   fi
 }
 
@@ -139,21 +139,21 @@ cleanup () {
 cleanup_cluster_nodes() {
   uuid="$1"
   if [ -z "$uuid" ]; then
-    echo  "Node UUID required."
+    log_error  "Node UUID required."
     exit 2
   fi
-  echo  "Cleaning up spokes" 1>&3
+  log_info  "Cleaning up spokes" 1>&3
   ghe-spokes server evacuate git-server-$uuid 'Removing replica'
   ghe-spokes server destroy git-server-$uuid
 
-  echo  "Cleaning up storage" 1>&3
+  log_info  "Cleaning up storage" 1>&3
   ghe-storage destroy-host storage-server-$uuid --force
 
-  echo  "Cleaning up dpages" 1>&3
+  log_info  "Cleaning up dpages" 1>&3
   ghe-dpages offline pages-server-$uuid
   ghe-dpages remove pages-server-$uuid
 
-  echo  "Cleaning up redis" 1>&3
+  log_info  "Cleaning up redis" 1>&3
   ghe-redis-cli del resque:queue:maint_git-server-$uuid
   ghe-redis-cli srem resque:queues maint_git-server-$uuid
 }
@@ -218,7 +218,7 @@ export CLUSTER
 
 # Restoring a cluster backup to a standalone appliance is not supported
 if ! $CLUSTER && [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
-  echo  "Error: Snapshot from a GitHub Enterprise cluster cannot be restored to a standalone appliance. Aborting." >&2
+  log_error  "Error: Snapshot from a GitHub Enterprise cluster cannot be restored to a standalone appliance. Aborting." >&2
   exit 1
 fi
 
@@ -230,7 +230,7 @@ fi
 # Figure out if this appliance is in a replication pair
 if ghe-ssh "$GHE_HOSTNAME" -- \
   "[ -f '$GHE_REMOTE_ROOT_DIR/etc/github/repl-state' ]"; then
-  echo  "Error: Restoring to an appliance with replication enabled is not supported. Please teardown replication before restoring." >&2
+  log_error  "Error: Restoring to an appliance with replication enabled is not supported. Please teardown replication before restoring." >&2
   exit 1
 fi
 
@@ -295,7 +295,7 @@ update_restore_status "restoring"
 # Make sure the GitHub appliance is in maintenance mode.
 if $instance_configured; then
   if ! ghe-maintenance-mode-status "$GHE_HOSTNAME"; then
-    echo  "Error: $GHE_HOSTNAME must be put in maintenance mode before restoring. Aborting." 1>&2
+    log_error  "Error: $GHE_HOSTNAME must be put in maintenance mode before restoring. Aborting." 1>&2
     exit 1
   fi
 fi
@@ -307,7 +307,7 @@ RELEASE_VERSION=$(ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --get core.package-vers
 # mismatches in the secrets needed for Actions which ultimately results in Actions not working properly. Note: xargs is to remove whitespace
 ACTIONS_ENABLED_IN_BACKUP=$(git config -f $GHE_RESTORE_SNAPSHOT_PATH/settings.json --bool app.actions.enabled | xargs)
 if [[ $ACTIONS_ENABLED_IN_BACKUP != true ]] && ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-    echo  "Restoring a backup with Actions disabled onto an appliance with Actions enabled is not supported." >&2
+    log_error  "Restoring a backup with Actions disabled onto an appliance with Actions enabled is not supported." >&2
     exit 1
 fi
 
@@ -318,15 +318,15 @@ if [ -d "$GHE_RESTORE_SNAPSHOT_PATH/mssql" ] || [ -d "$GHE_RESTORE_SNAPSHOT_PATH
     ac_db_ghe=$(echo 'ghe-mssql-console -y -n -q "SELECT name FROM sys.databases" | grep -i "ArtifactCache" | wc -l | tr -d " "' | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
     ac_db_snapshot=$(find "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/mssql/" -maxdepth 1 -name 'ArtifactCache*.bak' | wc -l | tr -d " ")
     if [[ $ac_db_ghe -gt 0  &&  $ac_db_snapshot -eq 0 ]]; then
-      echo  "$GHE_HOSTNAME has Actions Cache service enabled but no Actions Cache data is present in snapshot to restore. Aborting \n Please disable Actions cache service in $GHE_HOSTNAME and retry\nTo disable Actions Cache service run as admin: ghe-actions-cache-disable" 1>&2
+      log_error "$GHE_HOSTNAME has Actions Cache service enabled but no Actions Cache data is present in snapshot to restore. Aborting \n Please disable Actions cache service in $GHE_HOSTNAME and retry\nTo disable Actions Cache service run as admin: ghe-actions-cache-disable" 1>&2
       exit 1
     fi
     if [[ $ac_db_ghe -eq 0  &&  $ac_db_snapshot -gt 0 && ! $RESTORE_SETTINGS ]]; then
-      echo  "$GHE_HOSTNAME has Actions Cache service disabled but the snapshot is attempting to restore data for the service. Aborting. \n Please enable Actions cache service in $GHE_HOSTNAME and retry \n To enable Actions Cache service run as admin: ghe-actions-cache-enable" 1>&2
+      log_error "$GHE_HOSTNAME has Actions Cache service disabled but the snapshot is attempting to restore data for the service. Aborting. \n Please enable Actions cache service in $GHE_HOSTNAME and retry \n To enable Actions Cache service run as admin: ghe-actions-cache-enable" 1>&2
       exit 1
     fi
   else
-    echo  "$GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting. \n Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@$RELEASE_VERSION/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled" 1>&2
+    log_error "$GHE_HOSTNAME must have GitHub Actions enabled before restoring since the snapshot contains Actions data. Aborting. \n Setup details for enabling Actions can be found here: https://docs.github.com/en/enterprise-server@$RELEASE_VERSION/admin/github-actions/advanced-configuration-and-troubleshooting/backing-up-and-restoring-github-enterprise-server-with-github-actions-enabled" 1>&2
     exit 1
   fi
 fi
@@ -335,40 +335,40 @@ fi
 bm_init > /dev/null
 
 ghe-backup-store-version  ||
-echo  "Warning: storing backup-utils version remotely failed."
+log_warn "Warning: storing backup-utils version remotely failed."
 
 # Stop cron and timerd, as scheduled jobs may disrupt the restore process.
-echo  "Stopping cron and github-timerd ..."
+log_info "Stopping cron and github-timerd ..."
 if $CLUSTER; then
   if ! ghe-ssh "$GHE_HOSTNAME" -- "ghe-cluster-each -- sudo service cron stop"; then
-    ghe_verbose "* Warning: Failed to stop cron on one or more nodes"
+    log_warn "Failed to stop cron on one or more nodes" 1>&3
   fi
 
   if [ "$GHE_VERSION_MAJOR" -eq "3" ]; then
     if ghe-ssh "$GHE_HOSTNAME" -- "systemctl -q is-active nomad && nomad job status --short github-timerd &>/dev/null"; then
       if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo nomad stop github-timerd 1>/dev/null"; then
-        ghe_verbose "* Warning: Failed to stop github-timerd on one or more nodes"
+        log_warn "Failed to stop github-timerd on one or more nodes" 1>&3
       fi
     fi
   else
     if ! ghe-ssh "$GHE_HOSTNAME" -- "ghe-cluster-each -- sudo service github-timerd stop"; then
-      ghe_verbose "* Warning: Failed to stop github-timerd on one or more nodes"
+      log_warn "Failed to stop github-timerd on one or more nodes" 1>&3
     fi
   fi
 else
   if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo service cron stop"; then
-    ghe_verbose "* Warning: Failed to stop cron"
+    log_warn "Failed to stop cron" 1>&3
   fi
 
   if [ "$GHE_VERSION_MAJOR" -eq "3" ]; then
     if ghe-ssh "$GHE_HOSTNAME" -- "systemctl -q is-active nomad && nomad job status --short github-timerd &>/dev/null"; then
       if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo nomad stop github-timerd 1>/dev/null"; then
-        ghe_verbose "* Warning: Failed to stop github-timerd"
+        log_warn "Failed to stop github-timerd" 1>&3
       fi
     fi
   else
     if ! ghe-ssh "$GHE_HOSTNAME" -- "sudo service github-timerd stop"; then
-      ghe_verbose "* Warning: Failed to stop github-timerd"
+      log_warn "Failed to stop github-timerd" 1>&3
     fi
   fi
 fi
@@ -390,7 +390,7 @@ fi
 
 # Restore UUID if present and not restoring to cluster.
 if [ -s "$GHE_RESTORE_SNAPSHOT_PATH/uuid" ] && ! $CLUSTER; then
-  echo  "Restoring UUID ..."
+  log_info "Restoring UUID ..."
   cat "$GHE_RESTORE_SNAPSHOT_PATH/uuid" |
   ghe-ssh "$GHE_HOSTNAME" -- "sudo sponge '$GHE_REMOTE_DATA_USER_DIR/common/uuid' 2>/dev/null"
   ghe-ssh "$GHE_HOSTNAME" -- "sudo systemctl stop consul" || true
@@ -415,29 +415,29 @@ else
 fi
 
 if is_external_database_target_or_snapshot && $SKIP_MYSQL; then
-  echo  "Skipping MySQL restore."
+  log_info "Skipping MySQL restore."
 else
-  echo  "Restoring MySQL database from ${backup_snapshot_strategy} backup snapshot on an appliance configured for ${appliance_strategy} backups ..."
+  log_info "Restoring MySQL database from ${backup_snapshot_strategy} backup snapshot on an appliance configured for ${appliance_strategy} backups ..."
   ghe-restore-mysql "$GHE_HOSTNAME" 1>&3
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-  echo  "Stopping Actions before restoring databases ..."
+  log_info "Stopping Actions before restoring databases ..."
   # We mark Actions as stopped even if the `ghe-actions-stop`
   # fails to ensure that we cleanly start actions when performing cleanup.
   ACTIONS_STOPPED=true
   ghe-ssh "$GHE_HOSTNAME" -- 'ghe-actions-stop' 1>&3
 
-  echo  "Restoring MSSQL databases ..."
+  log_info  "Restoring MSSQL databases ..."
   ghe-restore-mssql "$GHE_HOSTNAME" 1>&3
 
-  echo  "Restoring Actions data ..."
+  log_info "Restoring Actions data ..."
   ghe-restore-actions "$GHE_HOSTNAME" 1>&3
   echo  "* WARNING: Every self-hosted Actions runner that communicates with the restored GHES server must be restarted or reconfigured in order to continue functioning. \n See https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners for more details on how to reconfigure self-hosted Actions runners."
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.minio.enabled'; then
-  echo  "Restoring MinIO data ..."
+  log_info "Restoring MinIO data ..."
   ghe-restore-minio "$GHE_HOSTNAME" 1>&3
 fi
 
