Prepend colorized input to logging data
prepend ISO 8601 format timestamp and colorized loglevel to the output
of ghe-backup and ghe-restore.

diff --git a/bin/ghe-backup b/bin/ghe-backup
--- a/bin/ghe-backup
+++ b/bin/ghe-backup
@@ -66,21 +66,21 @@ trap 'rm -rf src dest1 dest2' EXIT
 mkdir -p src
 touch src/testfile
 if ! ln -s /data/does/not/exist/hooks/ src/ >/dev/null 2>&1; then
-  echo "Error: the filesystem containing $GHE_DATA_DIR does not support symbolic links." 1>&2
-  echo "Git repositories contain symbolic links that need to be preserved during a backup." 1>&2
+  logError "Error: the filesystem containing $GHE_DATA_DIR does not support symbolic links." 1>&2
+  logError "Git repositories contain symbolic links that need to be preserved during a backup." 1>&2
   exit 1
 fi
 
 if ! output=$(rsync -a src/ dest1 2>&1 && rsync -av src/ --link-dest=../dest1 dest2 2>&1); then
-  echo "Error: rsync encountered an error that could indicate a problem with permissions," 1>&2
-  echo "hard links, symbolic links, or another issue that may affect backups." 1>&2
+  logError "Error: rsync encountered an error that could indicate a problem with permissions," 1>&2
+  logError "hard links, symbolic links, or another issue that may affect backups." 1>&2
   echo "$output"
   exit 1
 fi
 
 if [ "$(ls -il dest1/testfile | awk '{ print $1 }')" != "$(ls -il dest2/testfile | awk '{ print $1 }')" ]; then
-  echo "Error: the filesystem containing $GHE_DATA_DIR does not support hard links." 1>&2
-  echo "Backup Utilities use hard links to store backup data efficiently." 1>&2
+  logError "Error: the filesystem containing $GHE_DATA_DIR does not support hard links." 1>&2
+  logError "Backup Utilities use hard links to store backup data efficiently." 1>&2
   exit 1
 fi
 rm -rf src dest1 dest2
@@ -115,9 +115,9 @@ trap 'cleanup' EXIT
 trap 'exit $?' INT # ^C always terminate
 
 if [ -h ../in-progress ]; then
-  echo "Error: detected a backup already in progress from a previous version of ghe-backup." 1>&2
-  echo "If there is no backup in progress anymore, please remove" 1>&2
-  echo "the $GHE_DATA_DIR/in-progress file." 1>&2
+  logError "Error: detected a backup already in progress from a previous version of ghe-backup." 1>&2
+  logError "If there is no backup in progress anymore, please remove" 1>&2
+  logError "the $GHE_DATA_DIR/in-progress file." 1>&2
   exit 1
 fi
 
@@ -130,16 +130,16 @@ if [ -f ../in-progress ]; then
     # will clean up the failed backup.
     unlink ../in-progress
   else
-    echo "Error: A backup of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
-    echo "If PID $pid is not a process related to the backup utilities, please remove" 1>&2
-    echo "the $GHE_DATA_DIR/in-progress file and try again." 1>&2
+    logError "Error: A backup of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
+    logError "If PID $pid is not a process related to the backup utilities, please remove" 1>&2
+    logError "the $GHE_DATA_DIR/in-progress file and try again." 1>&2
     exit 1
   fi
 fi
 
 echo "$GHE_SNAPSHOT_TIMESTAMP $$" > ../in-progress
 
-echo "Starting backup of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION in snapshot $GHE_SNAPSHOT_TIMESTAMP"
+logInfo "Starting backup of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION in snapshot $GHE_SNAPSHOT_TIMESTAMP"
 
 # Perform a host connection check and establish the remote appliance version.
 # The version is available in the GHE_REMOTE_VERSION variable and also written
@@ -163,18 +163,18 @@ echo "$GHE_BACKUP_STRATEGY" > strategy
 bm_init > /dev/null
 
 ghe-backup-store-version  ||
-echo "Warning: storing backup-utils version remotely failed."
+logWarn "Warning: storing backup-utils version remotely failed."
 
-echo "Backing up GitHub settings ..."
+logInfo "Backing up GitHub settings ..."
 ghe-backup-settings || failures="$failures settings"
 
-echo "Backing up SSH authorized keys ..."
+logInfo "Backing up SSH authorized keys ..."
 bm_start "ghe-export-authorized-keys"
 ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-authorized-keys' > authorized-keys.json ||
 failures="$failures authorized-keys"
 bm_end "ghe-export-authorized-keys"
 
-echo "Backing up SSH host keys ..."
+logInfo "Backing up SSH host keys ..."
 bm_start "ghe-export-ssh-host-keys"
 ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-ssh-host-keys' > ssh-host-keys.tar ||
 failures="$failures ssh-host-keys"
@@ -183,45 +183,45 @@ bm_end "ghe-export-ssh-host-keys"
 ghe-backup-mysql || failures="$failures mysql"
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-  echo "Backing up MSSQL databases ..."
+  logInfo "Backing up MSSQL databases ..."
   ghe-backup-mssql 1>&3 || failures="$failures mssql"
 
-  echo "Backing up Actions data ..."
+  logInfo "Backing up Actions data ..."
   ghe-backup-actions 1>&3 || failures="$failures actions"
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.minio.enabled'; then
-  echo "Backing up Minio data ..."
+  logInfo "Backing up Minio data ..."
   ghe-backup-minio 1>&3 || failures="$failures minio"
 fi
 
 commands=("
-echo \"Backing up Redis database ...\"
+logInfo \"Backing up Redis database ...\"
 ghe-backup-redis > redis.rdb || printf %s \"redis \" >> \"$failures_file\"")
 
 commands+=("
-echo \"Backing up audit log ...\"
+logInfo \"Backing up audit log ...\"
 ghe-backup-es-audit-log || printf %s \"audit-log \" >> \"$failures_file\"")
 
 commands+=("
-echo \"Backing up Git repositories ...\"
+logInfo \"Backing up Git repositories ...\"
 ghe-backup-repositories || printf %s \"repositories \" >> \"$failures_file\"")
 
 commands+=("
-echo \"Backing up GitHub Pages artifacts ...\"
+logInfo \"Backing up GitHub Pages artifacts ...\"
 ghe-backup-pages || printf %s \"pages \" >> \"$failures_file\"")
 
 commands+=("
-echo \"Backing up storage data ...\"
+logInfo \"Backing up storage data ...\"
 ghe-backup-storage || printf %s \"storage \" >> \"$failures_file\"")
 
 commands+=("
-echo \"Backing up custom Git hooks ...\"
+logInfo \"Backing up custom Git hooks ...\"
 ghe-backup-git-hooks || printf %s \"git-hooks \" >> \"$failures_file\"")
 
 if [ "$GHE_BACKUP_STRATEGY" = "rsync" ]; then
   commands+=("
-  echo \"Backing up Elasticsearch indices ...\"
+  logInfo \"Backing up Elasticsearch indices ...\"
   ghe-backup-es-rsync || printf %s \"elasticsearch \" >> \"$failures_file\"")
 fi
 
@@ -239,6 +239,7 @@ fi
 
 # git fsck repositories after the backup
 if [ "$GHE_BACKUP_FSCK" = "yes" ]; then
+  loginfo "Running git fsck on repositories ..."
   ghe-backup-fsck $GHE_SNAPSHOT_DIR || failures="$failures fsck"
 fi
 
@@ -254,7 +255,7 @@ if [ -z "$failures" ]; then
   ghe-prune-snapshots
 fi
 
-echo "Completed backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP at $(date +"%H:%M:%S")"
+logInfo "Completed backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP at $(date +"%H:%M:%S")"
 
 # Exit non-zero and list the steps that failed.
 if [ -z "$failures" ]; then
@@ -262,12 +263,12 @@ if [ -z "$failures" ]; then
 else
   steps="$(echo $failures | sed 's/ /, /g')"
   ghe_remote_logger "Completed backup from $(hostname) / snapshot $GHE_SNAPSHOT_TIMESTAMP with failures: ${steps}."
-  echo "Error: Snapshot incomplete. Some steps failed: ${steps}. "
+  logError "Error: Snapshot incomplete. Some steps failed: ${steps}. "
   exit 1
 fi
 
 # Detect if the created backup contains any leaked ssh keys
-echo "Checking for leaked ssh keys ..."
+logInfo "Checking for leaked ssh keys ..."
 ghe-detect-leaked-ssh-keys -s "$GHE_SNAPSHOT_DIR" || true
 
 # Make sure we exit zero after the conditional
