migrating the state of the current 3.6 release into a temp branch

diff --git a/bin/ghe-backup b/bin/ghe-backup
--- a/bin/ghe-backup
+++ b/bin/ghe-backup
@@ -37,14 +37,12 @@ while true; do
   esac
 done
 
-export CALLING_SCRIPT="ghe-backup"
 # Bring in the backup configuration
 # shellcheck source=share/github-backup-utils/ghe-backup-config
 . "$( dirname "${BASH_SOURCE[0]}" )/../share/github-backup-utils/ghe-backup-config"
 
 # Check to make sure moreutils parallel is installed and working properly
 ghe_parallel_check
-
 
 # Used to record failed backup steps
 failures=
@@ -65,21 +63,24 @@ touch "incomplete"
 # Exit early if the snapshot filesystem doesn't support hard links, symlinks and
 # if rsync doesn't support hardlinking of dangling symlinks
 trap 'rm -rf src dest1 dest2' EXIT
-mkdir -p src
+mkdir src
 touch src/testfile
 if ! ln -s /data/does/not/exist/hooks/ src/ >/dev/null 2>&1; then
-  log_error "Error: the filesystem containing $GHE_DATA_DIR does not support symbolic links. \nGit repositories contain symbolic links that need to be preserved during a backup." 1>&2
+  echo "Error: the filesystem containing $GHE_DATA_DIR does not support symbolic links." 1>&2
+  echo "Git repositories contain symbolic links that need to be preserved during a backup." 1>&2
   exit 1
 fi
 
 if ! output=$(rsync -a src/ dest1 2>&1 && rsync -av src/ --link-dest=../dest1 dest2 2>&1); then
-  log_error "Error: rsync encountered an error that could indicate a problem with permissions,\n hard links, symbolic links, or another issue that may affect backups." 1>&2
+  echo "Error: rsync encountered an error that could indicate a problem with permissions," 1>&2
+  echo "hard links, symbolic links, or another issue that may affect backups." 1>&2
   echo "$output"
   exit 1
 fi
 
-if [ "$(stat -c %i dest1/testfile)" != "$(stat -c %i dest2/testfile)" ]; then
-  log_error "Error: the filesystem containing $GHE_DATA_DIR does not support hard links.\n Backup Utilities use hard links to store backup data efficiently." 1>&2
+if [ "$(ls -il dest1/testfile | awk '{ print $1 }')" != "$(ls -il dest2/testfile | awk '{ print $1 }')" ]; then
+  echo "Error: the filesystem containing $GHE_DATA_DIR does not support hard links." 1>&2
+  echo "Backup Utilities use hard links to store backup data efficiently." 1>&2
   exit 1
 fi
 rm -rf src dest1 dest2
@@ -98,13 +99,12 @@ cleanup () {
     progress=$(cat ../in-progress)
     snapshot=$(echo "$progress" | cut -d ' ' -f 1)
     pid=$(echo "$progress" | cut -d ' ' -f 2)
-    if [ "$snapshot" = "$GHE_SNAPSHOT_TIMESTAMP" ] && [ "$$" = "$pid" ]; then
+    if [ "$snapshot" = "$GHE_SNAPSHOT_TIMESTAMP" ] && [ "$$" = $pid ]; then
       unlink ../in-progress
     fi
   fi
 
   rm -rf "$failures_file"
-  rm -f "${GHE_DATA_DIR}/in-progress-backup"
 
   # Cleanup SSH multiplexing
   ghe-ssh --clean
@@ -114,14 +114,10 @@ cleanup () {
 trap 'cleanup' EXIT
 trap 'exit $?' INT # ^C always terminate
 
-
-# Check to see if there is a running restore
-ghe_restore_check
-
-# Check to see if there is a running backup
 if [ -h ../in-progress ]; then
-
-  log_error "Error: detected a backup already in progress from a previous version of ghe-backup. \nIf there is no backup in progress anymore, please remove \nthe $GHE_DATA_DIR/in-progress file." 1>&2
+  echo "Error: detected a backup already in progress from a previous version of ghe-backup." 1>&2
+  echo "If there is no backup in progress anymore, please remove" 1>&2
+  echo "the $GHE_DATA_DIR/in-progress file." 1>&2
   exit 1
 fi
 
@@ -134,16 +130,16 @@ if [ -f ../in-progress ]; then
     # will clean up the failed backup.
     unlink ../in-progress
   else
-    log_error "Error: A backup of $GHE_HOSTNAME may still be running on PID $pid. \nIf PID $pid is not a process related to the backup utilities, please remove \nthe $GHE_DATA_DIR/in-progress file and try again." 1>&2
+    echo "Error: A backup of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
+    echo "If PID $pid is not a process related to the backup utilities, please remove" 1>&2
+    echo "the $GHE_DATA_DIR/in-progress file and try again." 1>&2
     exit 1
   fi
 fi
 
 echo "$GHE_SNAPSHOT_TIMESTAMP $$" > ../in-progress
-echo "$GHE_SNAPSHOT_TIMESTAMP $$" > "${GHE_DATA_DIR}/in-progress-backup"
 
-START_TIME=$(date +%s)
-log_info "Starting backup of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION in snapshot $GHE_SNAPSHOT_TIMESTAMP"
+echo "Starting backup of $GHE_HOSTNAME with backup-utils v$BACKUP_UTILS_VERSION in snapshot $GHE_SNAPSHOT_TIMESTAMP"
 
 # Perform a host connection check and establish the remote appliance version.
 # The version is available in the GHE_REMOTE_VERSION variable and also written
@@ -167,18 +163,18 @@ echo "$GHE_BACKUP_STRATEGY" > strategy
 bm_init > /dev/null
 
 ghe-backup-store-version  ||
-log_warn "Warning: storing backup-utils version remotely failed."
+echo "Warning: storing backup-utils version remotely failed."
 
-log_info "Backing up GitHub settings ..."
+echo "Backing up GitHub settings ..."
 ghe-backup-settings || failures="$failures settings"
 
-log_info "Backing up SSH authorized keys ..."
+echo "Backing up SSH authorized keys ..."
 bm_start "ghe-export-authorized-keys"
 ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-authorized-keys' > authorized-keys.json ||
 failures="$failures authorized-keys"
 bm_end "ghe-export-authorized-keys"
 
-log_info "Backing up SSH host keys ..."
+echo "Backing up SSH host keys ..."
 bm_start "ghe-export-ssh-host-keys"
 ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-ssh-host-keys' > ssh-host-keys.tar ||
 failures="$failures ssh-host-keys"
@@ -187,57 +183,50 @@ bm_end "ghe-export-ssh-host-keys"
 ghe-backup-mysql || failures="$failures mysql"
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.actions.enabled'; then
-  log_info "Backing up MSSQL databases ..."
+  echo "Backing up MSSQL databases ..."
   ghe-backup-mssql 1>&3 || failures="$failures mssql"
 
-  log_info "Backing up Actions data ..."
+  echo "Backing up Actions data ..."
   ghe-backup-actions 1>&3 || failures="$failures actions"
 fi
 
 if ghe-ssh "$GHE_HOSTNAME" -- 'ghe-config --true app.minio.enabled'; then
-  log_info "Backing up Minio data ..."
+  echo "Backing up Minio data ..."
   ghe-backup-minio 1>&3 || failures="$failures minio"
 fi
 
-cmd_title=$(log_info "Backing up Redis database ...")
 commands=("
-echo \"$cmd_title\"
+echo \"Backing up Redis database ...\"
 ghe-backup-redis > redis.rdb || printf %s \"redis \" >> \"$failures_file\"")
 
-cmd_title=$(log_info "Backing up audit log ...")
 commands+=("
-echo \"$cmd_title\"
+echo \"Backing up audit log ...\"
 ghe-backup-es-audit-log || printf %s \"audit-log \" >> \"$failures_file\"")
 
-cmd_title=$(log_info "Backing up Git repositories ...")
 commands+=("
-echo \"$cmd_title\"
+echo \"Backing up Git repositories ...\"
 ghe-backup-repositories || printf %s \"repositories \" >> \"$failures_file\"")
 
-cmd_title=$(log_info "Backing up GitHub Pages artifacts ...")
 commands+=("
-echo \"$cmd_title\"
+echo \"Backing up GitHub Pages artifacts ...\"
 ghe-backup-pages || printf %s \"pages \" >> \"$failures_file\"")
 
-cmd_title=$(log_info "Backing up storage data ...")
 commands+=("
-echo \"$cmd_title\"
+echo \"Backing up storage data ...\"
 ghe-backup-storage || printf %s \"storage \" >> \"$failures_file\"")
 
-cmd_title=$(log_info "Backing up custom Git hooks ...")
 commands+=("
-echo \"$cmd_title\"
+echo \"Backing up custom Git hooks ...\"
 ghe-backup-git-hooks || printf %s \"git-hooks \" >> \"$failures_file\"")
 
 if [ "$GHE_BACKUP_STRATEGY" = "rsync" ]; then
-  cmd_title=$(log_info "Backing up Elasticsearch indices ...")
   commands+=("
-  echo \"$cmd_title\"
+  echo \"Backing up Elasticsearch indices ...\"
   ghe-backup-es-rsync || printf %s \"elasticsearch \" >> \"$failures_file\"")
 fi
 
 if [ "$GHE_PARALLEL_ENABLED" = "yes" ]; then
-  "$GHE_PARALLEL_COMMAND" "${GHE_PARALLEL_COMMAND_OPTIONS[@]}" -- "${commands[@]}"
+  $GHE_PARALLEL_COMMAND $GHE_PARALLEL_COMMAND_OPTIONS -- "${commands[@]}"
 else
   for c in "${commands[@]}"; do
     eval "$c"
@@ -250,8 +239,7 @@ fi
 
 # git fsck repositories after the backup
 if [ "$GHE_BACKUP_FSCK" = "yes" ]; then
-  log_info "Running git fsck on repositories ..."
-  ghe-backup-fsck "$GHE_SNAPSHOT_DIR" || failures="$failures fsck"
+  ghe-backup-fsck $GHE_SNAPSHOT_DIR || failures="$failures fsck"
 fi
 
 # If everything was successful, mark the snapshot as complete, update the
@@ -266,25 +254,21 @@ if [ -z "$failures" ]; then
   ghe-prune-snapshots
 fi
 
-END_TIME=$(date +%s)
-log_info "Runtime: $((END_TIME - START_TIME)) seconds"
-log_info "Completed backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP at $(date +"%H:%M:%S")"
+echo "Completed backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP at $(date +"%H:%M:%S")"
 
 # Exit non-zero and list the steps that failed.
 if [ -z "$failures" ]; then
   ghe_remote_logger "Completed backup from $(hostname) / snapshot $GHE_SNAPSHOT_TIMESTAMP successfully."
 else
-  steps="${failures// /, }"
+  steps="$(echo $failures | sed 's/ /, /g')"
   ghe_remote_logger "Completed backup from $(hostname) / snapshot $GHE_SNAPSHOT_TIMESTAMP with failures: ${steps}."
-  log_error "Error: Snapshot incomplete. Some steps failed: ${steps}. "
+  echo "Error: Snapshot incomplete. Some steps failed: ${steps}. "
   exit 1
 fi
 
 # Detect if the created backup contains any leaked ssh keys
-log_info "Checking for leaked ssh keys ..."
+echo "Checking for leaked ssh keys ..."
 ghe-detect-leaked-ssh-keys -s "$GHE_SNAPSHOT_DIR" || true
 
-log_info "Backup of $GHE_HOSTNAME finished."
-
-# Remove in-progress file
-ghe_backup_finished
+# Make sure we exit zero after the conditional
+true
diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -53,7 +53,7 @@ port=$(ssh_port_part "$host")
 hostname=$(ssh_host_part "$host")
 
 set +e
-# ghe-negotiate-version verifies if the target is a GitHub Enterprise Server instance
+# ghe-negotiate-version verifies if the target is a Github Enterprise Server instance
 output=$(echo "ghe-negotiate-version backup-utils $BACKUP_UTILS_VERSION" | ghe-ssh -o BatchMode=no $options $host -- /bin/sh 2>&1)
 rc=$?
 set -e
@@ -68,7 +68,7 @@ if [ $rc -ne 0 ]; then
     echo "$output" 1>&2
     echo "Error: ssh connection with '$host' failed" 1>&2
     echo "Note that your SSH key needs to be setup on $host as described in:" 1>&2
-    echo "* https://docs.github.com/enterprise-server/admin/configuration/configuring-your-enterprise/accessing-the-administrative-shell-ssh" 1>&2
+    echo "* https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access" 1>&2
     ;;
   101)
     echo "Error: couldn't read GitHub Enterprise Server fingerprint on '$host' or this isn't a GitHub appliance." 1>&2
@@ -97,7 +97,7 @@ if "$CLUSTER"; then
   distinct_versions=$(echo "$node_version_list" | awk '{split($0, a, ":"); print a[2]}' | awk '{print $4}' | uniq | wc -l)
   if [ "$distinct_versions" -ne 1 ]; then
     echo "$node_version_list" 1>&2
-    echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&3
+    echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&2
     exit 1
   fi
 fi
@@ -131,7 +131,7 @@ fi
 
 # backup-utils 2.13 onwards limits support to the current and previous two releases
 # of GitHub Enterprise Server.
-supported_minimum_version="3.6.0"
+supported_minimum_version="3.4.0"
 
 if [ "$(version $version)" -ge "$(version $supported_minimum_version)" ]; then
   supported=1
@@ -142,83 +142,6 @@ if [ -z "$supported" ]; then
   echo "Backup Utilities v$BACKUP_UTILS_VERSION requires GitHub Enterprise Server v$supported_minimum_version or newer." 1>&2
   echo "Please update your GitHub Enterprise Server appliance or use an older version of Backup Utilities." 1>&2
   exit 1
-fi
-
-if [[ "$CALLING_SCRIPT" == "ghe-backup" ]]; then
-  # Bring in the requirements file
-  min_rsync=""
-  min_openssh=""
-  min_jq=""
-  # shellcheck source=share/github-backup-utils/requirements.txt
-  . "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/requirements.txt"
-
-  #source disk size file
-  # shellcheck source=share/github-backup-utils/ghe-rsync-size.sh
-  . "$(dirname "${BASH_SOURCE[0]}")/../share/github-backup-utils/ghe-rsync-size.sh"
-
-  #Display dir requirements for repositories and mysql
-  echo "Checking host for sufficient space for a backup..." 1>&2
-  available_space=$(df -B 1k $GHE_DATA_DIR | awk 'END{printf "%.0f", $4 * 1024}') 
-  echo "We recommend allocating at least 5x the amount of storage allocated to the primary GitHub appliance for historical snapshots and growth over time." 1>&2
-
-  repos_disk_size=$(transfer_size repositories /tmp)
-  pages_disk_size=$(transfer_size pages /tmp)
-  es_disk_size=$(transfer_size elasticsearch /tmp)
-  stor_disk_size=$(transfer_size storage /tmp)
-  minio_disk_size=$(transfer_size minio /tmp)
-  mysql_disk_size=$(transfer_size mysql /tmp)
-  actions_disk_size=$(transfer_size actions /tmp)
-  mssql_disk_size=$(transfer_size mssql /tmp)
-
-  min_disk_req=$((repos_disk_size + pages_disk_size + es_disk_size + stor_disk_size + minio_disk_size + mysql_disk_size + actions_disk_size + mssql_disk_size))
-  echo "Available space: $((available_space / (1024 ** 2))) MB" 1>&2
-  echo -e "Min Disk required for this backup is at least $min_disk_req MB\n" 1>&2
-
-cat <<DATA_TRANSFER_SIZE 1>&2
-### Data Transfer Sizes 
-repositories: $repos_disk_size MB
-pages: $pages_disk_size MB
-elasticsearch: $es_disk_size MB
-storage: $stor_disk_size MB
-minio: $minio_disk_size MB
-mysql: $mysql_disk_size MB
-actions: $actions_disk_size MB
-mssql: $mssql_disk_size MB
-DATA_TRANSFER_SIZE
-
-  if [[ $available_space -lt $min_disk_req ]]; then
-    echo "There is not enough disk space for the backup. Please allocate more space and continue." 1>&2
-    exit 1
-  fi
-
-  #Check rsync, openssh & jq versions
-  echo "### Software versions" 1>&2
-  rsync_version=$(rsync --version | grep 'version' | awk '{print $3}')
-  if awk "BEGIN {exit !($rsync_version < $min_rsync)}" &> /dev/null; then
-    echo "rsync version $rsync_version in backup-host does not meet minimum requirements." 1>&2
-    echo "Please make sure you have the minimum required version of rsync: $min_rsync installed" 1>&2
-    exit 1
-  else
-    echo "rsync ${rsync_version} >= required ($min_rsync)" 1>&2
-  fi
-
-  ssh_version=$(ssh -V 2>&1 | awk '{print $1}'|grep -oPm 1 '[\d\.]+' |head -1)
-  if awk "BEGIN {exit !($ssh_version < $min_openssh)}" &> /dev/null; then
-    echo "openSSH version $ssh_version in backup-host does not meet minimum requirements." 1>&2
-    echo "Please make sure the minimum required version of openSSH: $min_openssh is installed" 1>&2
-    exit 1
-  else
-    echo "openSSH ${ssh_version} >= required ($min_openssh)" 1>&2
-  fi
-
-  jq_version=$(jq --version |awk -F\- '{print $2}')
-  if awk "BEGIN {exit !($jq_version < $min_jq)}" &> /dev/null; then
-    echo "jq version $jq_version in backup-host does not meet minimum requirements." 1>&2
-    echo "Please make sure you have the minimum required version of jq: $min_jq installed" 1>&2
-    exit 1
-  else
-    echo "jq ${jq_version} >= required ($min_jq)" 1>&2
-  fi
 fi
 
 echo "Connect $hostname:$port OK (v$version)"
diff --git a/share/github-backup-utils/ghe-backup-actions b/share/github-backup-utils/ghe-backup-actions
--- a/share/github-backup-utils/ghe-backup-actions
+++ b/share/github-backup-utils/ghe-backup-actions
@@ -20,7 +20,7 @@ backup_dir="$GHE_SNAPSHOT_DIR/actions"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  log_error "Error: rsync not found." 1>&2
+  echo "Error: rsync not found." 1>&2
   exit 1
 fi
 
@@ -38,7 +38,7 @@ fi
 
 # Transfer all Actions data from the user data directory using rsync.
 ghe_verbose "* Transferring Actions files from $host ..."
-log_rsync "BEGIN: actions rsync" 1>&3
+
 ghe-rsync -avz \
   -e "ghe-ssh -p $port" \
   --rsync-path='sudo -u actions rsync' \
@@ -46,6 +46,5 @@ ghe-rsync -avz \
   $link_dest \
   "$host:$GHE_REMOTE_DATA_USER_DIR/actions/" \
   "$GHE_SNAPSHOT_DIR/actions" 1>&3
-log_rsync "END: actions rsync" 1>&3
 
 bm_end "$(basename $0)"
diff --git a/share/github-backup-utils/ghe-backup-config b/share/github-backup-utils/ghe-backup-config
--- a/share/github-backup-utils/ghe-backup-config
+++ b/share/github-backup-utils/ghe-backup-config
@@ -14,83 +14,6 @@
 #     . $( dirname "${BASH_SOURCE[0]}" )/../share/github-backup-utils/ghe-backup-config
 #
 set +o posix
-# Terminal colors
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-YELLOW='\033[0;33m'
-BLUE='\033[0;34m'
-NC='\033[0m' # No Colo# Logging display and formatting functions
-
-# Log a message to stdout
-log_level() {
-  local level=$1
-  shift
-  local message=$*
-  local display=""
-  local timestamp
-  timestamp=$(date -u "+%FT%TZ")
-
-
-  if [ "$TERM" = "dumb" ] || [[ "$OUTPUT_COLOR" != "yes" ]]; then
-    if [ "$level" = "info" ]; then
-      display="INFO"
-    elif [ "$level" = "warn" ]; then
-      display="WARN"
-    elif [ "$level" = "error" ]; then
-      display="ERROR"
-    elif [ "$level" = "verbose" ]; then
-      display="INFO"
-    elif [ "$level" = "rsync" ]; then
-      display="RSYNC"
-    elif [ "$level" = "ssh" ]; then
-      display="SSH"
-    else
-      display="-"
-    fi
-  else 
-    if [ "$level" = "info" ]; then
-      display="${GREEN}INFO${NC}"
-    elif [ "$level" = "warn" ]; then
-      display="${YELLOW}WARN${NC}"
-    elif [ "$level" = "error" ]; then
-      display="${RED}ERROR${NC}"
-    elif [ "$level" = "verbose" ]; then
-      display="${GREEN}INFO${NC}"
-    elif [ "$level" = "rsync" ]; then
-      display="${GREEN}RSYNC${NC}"
-    elif [ "$level" = "ssh" ]; then
-      display="${GREEN}SSH${NC}"
-    else
-      display="-"
-    fi
-  fi
-  echo -e "$timestamp  $display  $message"
-}
-
-log_info(){
-  log_level "info" "$1"
-}
-
-log_warn(){
-  log_level "warn" "$1"
-}
-
-log_error(){
-  log_level "error" "$1"
-}
-
-log_verbose(){
-  log_level "verbose" "$1"
-}
-
-log_rsync(){
-  log_level "rsync" "$1"
-}
-
-log_ssh(){
-  log_level "ssh" "$1"
-} 
-
 # Assume this script lives in share/github-backup-utils/ when setting the root
 GHE_BACKUP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
 
@@ -104,7 +27,7 @@ if [ -n "$GHE_SHOW_VERSION" ]; then
 fi
 
 # Check for "--help|-h" in args or GHE_SHOW_HELP=true and show usage
-# shellcheck disable=SC2120 # Our arguments are optional and not meant to be the owning script's
+# shellcheck disable=SC2120 # the script name is always referenced
 print_usage() {
   grep '^#/' <"$0" | cut -c 4-
   exit "${1:-1}"
@@ -143,69 +66,7 @@ for f in "$GHE_BACKUP_CONFIG" "$GHE_BACKUP_ROOT/backup.config" \
   fi
 done
 
-# If we don't have a readlink command, error out
-! type readlink 1>/dev/null 2>&1 && {
-    echo "Error: readlink not found. Please install readlink and ensure it is in your PATH." 1>&2
-    exit 1
-}
-
-GHE_RESTORE_IN_PROGRESS=$(readlink -fm "${GHE_DATA_DIR}/in-progress-restore")
-GHE_BACKUP_IN_PROGRESS=$(readlink -fm "${GHE_DATA_DIR}/in-progress-backup")
-
-export GHE_RESTORE_IN_PROGRESS
-export GHE_BACKUP_IN_PROGRESS
-
-ghe_restore_check() {
-  if [ -h $GHE_RESTORE_IN_PROGRESS ]; then
-    echo "  Error: detected a restore already in progress from a previous version of ghe-restore." 1>&2
-    echo "  If there is no restore in progress anymore, please remove" 1>&2
-    echo "  the $GHE_RESTORE_IN_PROGRESS file and try again." 1>&2
-    exit 1
-  fi
-
-  if [ -f $GHE_RESTORE_IN_PROGRESS ]; then
-    progress=$(cat $GHE_RESTORE_IN_PROGRESS)
-    pid=$(echo "$progress" | cut -d ' ' -f 2)
-    echo "  Error: A restore of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
-    echo "  If PID $pid is not a process related to the restore utilities, please remove" 1>&2
-    echo "  the $GHE_RESTORE_IN_PROGRESS file and try again." 1>&2
-    exit 1
-  fi
-}
-
-ghe_backup_check() {
-  if [ -h $GHE_BACKUP_IN_PROGRESS ]; then
-    echo "  Error: detected a backup already in progress from a previous version of ghe-backup." 1>&2
-    echo "  If there is no backup in progress anymore, please remove" 1>&2
-    echo "  the $GHE_DATA_DIR/$GHE_BACKUP_IN_PROGRESS file and try again." 1>&2
-    exit 1
-  fi
-
-  if [ -f $GHE_BACKUP_IN_PROGRESS ]; then
-    progress=$(cat $GHE_BACKUP_IN_PROGRESS)
-    pid=$(echo "$progress" | cut -d ' ' -f 2)
-    echo "  Error: A backup of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
-    echo "  If PID $pid is not a process related to the backup utilities, please remove" 1>&2
-    echo "  the $GHE_BACKUP_IN_PROGRESS file and try again." 1>&2
-    exit 1
-  fi
-}
-
-ghe_restore_finished() {
-  if [ -f $GHE_RESTORE_IN_PROGRESS ]; then
-    rm -f $GHE_RESTORE_IN_PROGRESS
-  fi
-}
-
-ghe_backup_finished() {
-  if [ -f $GHE_BACKUP_IN_PROGRESS ]; then
-    rm -f $GHE_BACKUP_IN_PROGRESS
-  fi
-}
-
 ghe_parallel_check() {
-  GHE_PARALLEL_COMMAND_OPTIONS=()
-
   if [ "$GHE_PARALLEL_ENABLED" != "yes" ]; then
     return 0
   fi
@@ -227,13 +88,13 @@ ghe_parallel_check() {
   done
 
   # Check that the GHE_PARALLEL_COMMAND is pointing to moreutils parallel
-  if ! "$GHE_PARALLEL_COMMAND" -h | grep -q "parallel \[OPTIONS\] command -- arguments"; then
+  if ! $GHE_PARALLEL_COMMAND -h | grep -q "parallel \[OPTIONS\] command -- arguments"; then
     echo "Error: moreutils not found. Please install https://joeyh.name/code/moreutils" 1>&2
     exit 1
   fi
 
   if [ -n "$GHE_PARALLEL_MAX_JOBS" ]; then
-    GHE_PARALLEL_COMMAND_OPTIONS+=(-j "$GHE_PARALLEL_MAX_JOBS")
+    GHE_PARALLEL_COMMAND_OPTIONS="-j $GHE_PARALLEL_MAX_JOBS"
     # Default to the number of max rsync jobs to the same as GHE_PARALLEL_MAX_JOBS, if not set.
     # This is only applicable to ghe-restore-repositories currently.
     : "${GHE_PARALLEL_RSYNC_MAX_JOBS:="$GHE_PARALLEL_MAX_JOBS"}"
@@ -244,7 +105,7 @@ ghe_parallel_check() {
   fi
 
   if [ -n "$GHE_PARALLEL_MAX_LOAD" ]; then
-    GHE_PARALLEL_COMMAND_OPTIONS+=(-l "$GHE_PARALLEL_MAX_LOAD")
+    GHE_PARALLEL_COMMAND_OPTIONS+=" -l $GHE_PARALLEL_MAX_LOAD"
     GHE_PARALLEL_RSYNC_COMMAND_OPTIONS+=" -l $GHE_PARALLEL_MAX_LOAD"
   fi
 }
@@ -266,16 +127,12 @@ if [ -n "$GHE_VERBOSE" ]; then
     if [ "$GHE_PARALLEL_ENABLED" != "yes" ]; then
       exec 3>>"$GHE_VERBOSE_LOG"
     else
-      calling_script_name="$(caller | sed 's:.*/::')"
-      if [ "$TERM" = "dumb" ] || [[ "$OUTPUT_COLOR" != "yes" ]]; then
-        exec 3>>"$GHE_VERBOSE_LOG"
-        log_info "$calling_script_name $*" 1>&3
-      else
-        # colorize the input if supported. 
-        display_caller="${BLUE}$calling_script_name${NC}"
-        exec 3>>"$GHE_VERBOSE_LOG"
-        log_info "$display_caller $*" 1>&3
+      if ! echo | awk '{ print strftime("%b %d %H:%M:%S"); fflush(); }' &>/dev/null; then
+        echo "Error: awk command failed. Please install https://www.gnu.org/software/gawk" 1>&2
+        exit 1
       fi
+      calling_script_name="$(caller | sed 's:.*/::')"
+      exec 3> >(awk -v c="$calling_script_name" '{ print strftime("%b %d %H:%M:%S"), c":", $0; fflush(); }' >>"$GHE_VERBOSE_LOG")
     fi
   else
     exec 3>&1
@@ -300,9 +157,10 @@ if [ -z "$GHE_DATA_DIR" ]; then
 fi
 
 # Convert the data directory path to an absolute path, basing any relative
-# paths on the backup-utils root, and use readlink to canonicalize the path.
+# paths on the backup-utils root, and using readlink, if available, to
+# canonicalize the path.
 if [ "${GHE_DATA_DIR:0:1}" != "/" ]; then
-  GHE_DATA_DIR="$(cd "$GHE_BACKUP_ROOT" && readlink -m "$GHE_DATA_DIR")"
+  GHE_DATA_DIR="$(cd "$GHE_BACKUP_ROOT" && readlink -m "$GHE_DATA_DIR" 2>/dev/null || echo "$GHE_BACKUP_ROOT/$GHE_DATA_DIR")"
 fi
 export GHE_DATA_DIR
 
@@ -374,7 +232,7 @@ export GHE_SNAPSHOT_DIR
 # Set "true" to get verbose logging of all ssh commands on stderr
 : ${GHE_VERBOSE_SSH:=false}
 
-# The location of the cluster configuration file on the remote side.
+# The location of the cluster configuration file file on the remote side.
 # This is always "/data/user/common/cluster.conf" for GitHub Cluster instances.
 # Use of this variable allows the location to be overridden in tests.
 : ${GHE_REMOTE_CLUSTER_CONF_FILE:="$GHE_REMOTE_DATA_DIR/user/common/cluster.conf"}
@@ -406,13 +264,23 @@ ghe_remote_version_config() {
 ###############################################################################
 ### Utility functions
 
+# If we don't have a readlink command, parse ls -l output.
+if ! type readlink 1>/dev/null 2>&1; then
+  readlink() {
+    if [ -x "$1" ]; then
+      ls -ld "$1" | sed 's/.*-> //'
+    else
+      return 1
+    fi
+  }
+fi
+
 # Run ghe-host-check and establish the version of the remote GitHub instance in
 # the exported GHE_REMOTE_VERSION variable. If the remote version has already
 # been established then don't perform the host check again. Utilities in share/github-backup-utils
 # that need the remote version should use this function instead of calling
 # ghe-host-check directly to reduce ssh roundtrips. The top-level ghe-backup and
 # ghe-restore commands establish the version for all subcommands.
-# shellcheck disable=SC2120 # Our arguments are optional and not meant to be the owning script's
 ghe_remote_version_required() {
   if [ -z "$GHE_REMOTE_VERSION" ]; then
     _out=$(ghe-host-check "$@")
@@ -467,7 +335,7 @@ ssh_host_part() {
 # rsync commands.
 ssh_port_part() {
   if [ "${1##*:}" != "$1" ] && [ "${1##*:}" -ne "122" ]; then
-    echo "Error: SSH port has to be 122 connecting to GitHub Enterprise Server, current value is ${1##*:} for $1." 1>&2
+    echo "Error: SSH port has to be 122 connecting to Github Enterprise Server, current value is ${1##*:} for $1." 1>&2
     exit 1
   fi
 
@@ -486,7 +354,7 @@ ghe_remote_logger() {
 # Log if verbose mode is enabled (GHE_VERBOSE or `-v`).
 ghe_verbose() {
   if [ -n "$GHE_VERBOSE" ]; then
-    log_verbose "$@" 1>&3
+    echo "$@" 1>&3
   fi
 }
 
@@ -639,8 +507,3 @@ restore-secret() {
     ghe-ssh "$GHE_HOSTNAME" -- /bin/bash
   fi
 }
-
-
-
-
-
diff --git a/share/github-backup-utils/ghe-backup-mssql b/share/github-backup-utils/ghe-backup-mssql
--- a/share/github-backup-utils/ghe-backup-mssql
+++ b/share/github-backup-utils/ghe-backup-mssql
@@ -22,46 +22,15 @@ tran_expire=
 # Check if the export tool is available in this version
 export_tool_available() {
   if [ -z "$GHE_TEST_REMOTE_VERSION" ]; then
-    ghe_ssh_mssql "test -e /usr/local/bin/ghe-export-mssql"
+    ghe-ssh "$GHE_HOSTNAME" "test -e /usr/local/bin/ghe-export-mssql"
   else
     # Always return available for test
     return 0
   fi
 }
 
-ghe_ssh_mssql() {
-  ghe-ssh $opts $ssh_config_file_opt "$GHE_MSSQL_PRIMARY_HOST" "$@"
-}
-
-cleanup() {
-  rm -rf $tempdir
-}
-trap 'cleanup' EXIT INT
-
-# use the mssql primary host if GHES cluster configuration contains a mssql-master or use the ghe server if the mssql-master is not available.
-GHE_MSSQL_PRIMARY_NODE="$(ghe-ssh "$GHE_HOSTNAME" -- "ghe-config cluster.mssql-master" || true)"
-GHE_MSSQL_PRIMARY_HOST="$(ghe-ssh "$GHE_HOSTNAME" -- "ghe-config cluster.$GHE_MSSQL_PRIMARY_NODE.hostname" || true)"
-
-if [ -z "$GHE_MSSQL_PRIMARY_HOST" ]; then
-  GHE_MSSQL_PRIMARY_HOST="$GHE_HOSTNAME"
-fi
-
-tempdir=$(mktemp -d -t backup-utils-backup-XXXXXX)
-ssh_config_file_opt=
-opts=
-
-isHA="$(ghe-ssh "$GHE_HOSTNAME" -- "ghe-config cluster.ha" || true)"
-
-# get server hostnames under cluster and HA
-if [ "$GHE_BACKUP_STRATEGY" = "cluster" ] || [ "$isHA" = "true" ]  ; then
-  ssh_config_file="$tempdir/ssh_config"
-  ssh_config_file_opt="-F $ssh_config_file"
-  opts="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
-  ghe-ssh-config "$GHE_HOSTNAME" "$GHE_MSSQL_PRIMARY_HOST" > "$ssh_config_file"
-fi
-
-if ! export_tool_available ; then
-  log_error "ghe-export-mssql is not available" 1>&2
+if ! export_tool_available; then
+  ghe_verbose "ghe-export-mssql is not available"
   exit
 fi
 
@@ -80,11 +49,11 @@ find_timestamp() {
   filename="${1##*/}"
   IFS='@' read -ra parts <<< "$filename"
   datetime_part=${parts[1]:0:15}
-  echo "$datetime_part"
+  echo $datetime_part
 }
 
 actions_dbs() {
-  all_dbs=$(echo 'set -o pipefail; ghe-mssql-console -y -n -q "SET NOCOUNT ON; SELECT name FROM sys.databases"' | ghe_ssh_mssql /bin/bash)
+  all_dbs=$(echo 'set -o pipefail; ghe-mssql-console -y -n -q "SET NOCOUNT ON; SELECT name FROM sys.databases"' | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
   for db in $all_dbs; do
     if [[ ! "$db" =~ ^(master|tempdb|model|msdb)$ ]] && [[ "$db" =~ ^[a-zA-Z0-9_-]+$ ]]; then
       echo "$db"
@@ -110,8 +79,8 @@ ensure_same_dbs() {
   done
 
   if [[ "${#locals[@]}" -ne 0 ]]; then
-    log_warn "Warning: Found following ${#locals[@]} backup files that can't be traced back to the specified GHES host."
-    log_warn "Warning: Did you recently reconfigure the GHES host? Move or delete these backup files if no longer needed."
+    ghe_verbose "Warning: Found following ${#locals[@]} backup files that can't be traced back to the specified GHES host."
+    ghe_verbose "Warning: Did you recently reconfigure the GHES host? Move or delete these backup files if no longer needed."
     for local in "${locals[@]}"; do
       ghe_verbose "$1/$local"
     done
@@ -121,7 +90,7 @@ ensure_same_dbs() {
 }
 
 run_query() {
-  echo "set -o pipefail; ghe-mssql-console -y -n -q \"SET NOCOUNT ON; $1\"" | ghe_ssh_mssql /bin/bash | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
+  echo "set -o pipefail; ghe-mssql-console -y -n -q \"SET NOCOUNT ON; $1\"" | ghe-ssh "$GHE_HOSTNAME" /bin/bash | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
 }
 
 get_latest_backup_file() {
@@ -129,7 +98,7 @@ get_latest_backup_file() {
   db=$2
   ext=$3
 
-  latest_full_backup=$(find "$backups_dir" -type f -name "$db*.$ext" | grep -E '[0-9]{8}T[0-9]{6}' | sort | tail -n 1)
+  latest_full_backup=$(find "$backups_dir" -type f -name "$db*.$ext" | egrep '[0-9]{8}T[0-9]{6}' | sort | tail -n 1)
   latest_full_backup_file="${latest_full_backup##*/}"
   echo "$latest_full_backup_file"
 }
@@ -177,8 +146,8 @@ get_next_diff_backup_base_lsn() {
 
 last_mssql=$GHE_DATA_DIR/current/mssql
 
-if [ ! -d "$last_mssql" ] \
-  || [ -z "$(find "$last_mssql" -type f -name '*.bak' | head -n 1)" ]; then
+if [ ! -d $last_mssql ] \
+  || [ -z "$(find $last_mssql -type f -name '*.bak' | head -n 1)" ]; then
   ghe_verbose "Taking first full backup"
   backup_type="full"
 else
@@ -190,34 +159,34 @@ else
   current=$(date -u +%Y%m%d%H%M%S)
 
   full=$(find "$last_mssql" -type f -name "*.bak" | head -n 1)
-  full=$(find_timestamp "$full")
-  full_expire=$(add_minute "$full" "${cadence[0]}")
+  full=$(find_timestamp $full)
+  full_expire=$(add_minute $full ${cadence[0]})
   full_expire="${full_expire//T}"
 
   diff=$(find "$last_mssql" -type f -name "*.diff" | head -n 1)
   if [ -f "$diff" ]; then
-    diff=$(find_timestamp "$diff")
-    diff_expire=$(add_minute "$diff" "${cadence[1]}")
+    diff=$(find_timestamp $diff)
+    diff_expire=$(add_minute $diff ${cadence[1]})
     diff_expire="${diff_expire//T}"
   else
-    diff_expire=$(add_minute "$full" "${cadence[1]}")
+    diff_expire=$(add_minute $full ${cadence[1]})
     diff_expire="${diff_expire//T}"
   fi
 
-  tran=$(find "$last_mssql" -type f -name "*.log" | grep -E '[0-9]{8}T[0-9]{6}' | sort | tail -1)
-  tran=$(find_timestamp "$tran")
-  tran_expire=$(add_minute "$tran" "${cadence[2]}")
+  tran=$(find "$last_mssql" -type f -name "*.log" | egrep '[0-9]{8}T[0-9]{6}' | sort | tail -1)
+  tran=$(find_timestamp $tran)
+  tran_expire=$(add_minute $tran ${cadence[2]})
   tran_expire="${tran_expire//T}"
 
   ghe_verbose "current $current, full expire $full_expire, \
 diff expire $diff_expire, tran expire $tran_expire"
 
   # Determine the type of backup to take based on expiry time
-  if [ "$current" -gt "$full_expire" ]; then
+  if [ $current -gt $full_expire ]; then
     backup_type='full'
-  elif [ "$current" -gt "$diff_expire" ]; then
+  elif [ $current -gt $diff_expire ]; then
     backup_type='diff'
-  elif [ "$current" -gt "$tran_expire" ]; then
+  elif [ $current -gt $tran_expire ]; then
     backup_type='transaction'
   fi
 
@@ -231,28 +200,28 @@ diff expire $diff_expire, tran expire $tran_expire"
       if [ "$backup_type" == 'diff' ]; then
         full_backup_file=$(get_latest_backup_file "$last_mssql" "$db" "bak")
         if [[ "$full_backup_file" == "" ]]; then
-          log_warn "Taking a full backup instead of a diff backup because for $db a full backup file wasn't found"
+          ghe_verbose "Taking a full backup instead of a diff backup because for $db a full backup file wasn't found"
           backup_type="full"
           break
         fi
 
         full_backup_file_checkpoint_lsn=$(get_backup_checkpoint_lsn "$db" "$full_backup_file")
         if [[ "$full_backup_file_checkpoint_lsn" = "NULL" ]] || [[ "$full_backup_file_checkpoint_lsn" == "" ]]; then
-          log_warn "Taking a full backup instead of a diff backup because for $db the checkpoint LSN for $full_backup_file couldn't be determined"
+          ghe_verbose "Taking a full backup instead of a diff backup because for $db the checkpoint LSN for $full_backup_file couldn't be determined"
           backup_type="full"
           break
         fi
 
         next_diff_backup_base_lsn=$(get_next_diff_backup_base_lsn "$db")
         if [[ "$next_diff_backup_base_lsn" = "NULL" ]] || [[ "$next_diff_backup_base_lsn" == "" ]]; then
-          log_warn "Taking a full backup instead of a $backup_type backup because for $db the base LSN for the next diff backup couldn't be determined"
+          ghe_verbose "Taking a full backup instead of a $backup_type backup because for $db the base LSN for the next diff backup couldn't be determined"
           backup_type="full"
           break
         fi
 
         # The base of the diff backup we're about to take must exactly match the checkpoint LSN of the full backup file we have
         if [[ "$next_diff_backup_base_lsn" -ne "$full_backup_file_checkpoint_lsn" ]]; then
-          log_warn "Taking a full backup instead of a $backup_type backup because for $db the diff would have base LSN $next_diff_backup_base_lsn yet our full backup has checkpoint LSN $full_backup_file_checkpoint_lsn"
+          ghe_verbose "Taking a full backup instead of a $backup_type backup because for $db the diff would have base LSN $next_diff_backup_base_lsn yet our full backup has checkpoint LSN $full_backup_file_checkpoint_lsn"
           backup_type="full"
           break
         fi
@@ -261,21 +230,21 @@ diff expire $diff_expire, tran expire $tran_expire"
       # Ensure that a transaction log backup will immediately follow the previous one
       latest_log_backup_file=$(get_latest_backup_file "$last_mssql" "$db" "log")
       if [[ "$latest_log_backup_file" == "" ]]; then
-        log_warn "Taking a full backup instead of a $backup_type backup because for $db a previous transaction log backup wasn't found"
+        ghe_verbose "Taking a full backup instead of a $backup_type backup because for $db a previous transaction log backup wasn't found"
         backup_type="full"
         break
       fi
 
       latest_log_backup_last_lsn=$(get_backup_last_lsn "$db" "$latest_log_backup_file")
       if [[ "$latest_log_backup_last_lsn" = "NULL" ]] || [[ "$latest_log_backup_last_lsn" == "" ]]; then
-        log_warn "Taking a full backup instead of a $backup_type backup because for $db the LSN range for $latest_log_backup_file couldn't be determined"
+        ghe_verbose "Taking a full backup instead of a $backup_type backup because for $db the LSN range for $latest_log_backup_file couldn't be determined"
         backup_type="full"
         break
       fi
 
       next_log_backup_starting_lsn=$(get_next_log_backup_starting_lsn "$db")
       if [[ "$next_log_backup_starting_lsn" = "NULL" ]] || [[ "$next_log_backup_starting_lsn" == "" ]]; then
-        log_warn "Taking a full backup instead of a $backup_type backup because for $db the starting LSN for the next log backup couldn't be determined"
+        ghe_verbose "Taking a full backup instead of a $backup_type backup because for $db the starting LSN for the next log backup couldn't be determined"
         backup_type="full"
         break
       fi
@@ -283,7 +252,7 @@ diff expire $diff_expire, tran expire $tran_expire"
       # The starting LSN of the backup we're about to take must be equal to (or before) the last LSN from the last backup,
       # otherwise there'll be a gap and the logfiles won't be restorable
       if [[ "$next_log_backup_starting_lsn" -gt "$latest_log_backup_last_lsn" ]]; then
-        log_warn "Taking a full backup instead of a $backup_type backup because for $db a gap would exist between the last backup ending at LSN $latest_log_backup_last_lsn and next backup starting at $next_log_backup_starting_lsn"
+        ghe_verbose "Taking a full backup instead of a $backup_type backup because for $db a gap would exist between the last backup ending at LSN $latest_log_backup_last_lsn and next backup starting at $next_log_backup_starting_lsn"
         backup_type="full"
         break
       fi
@@ -295,8 +264,8 @@ fi
 mkdir -p "$backup_dir"
 
 # Use hard links to "copy" over previous applicable backups to the new snapshot folder to save disk space and time
-if [ -d "$last_mssql" ]; then
-  for p in "$last_mssql"/*
+if [ -d $last_mssql ]; then
+  for p in $last_mssql/*
   do
     [[ -e "$p" ]] || break
 
@@ -305,23 +274,23 @@ if [ -d "$last_mssql" ]; then
     transfer=
 
     # Copy full backups unless we're taking a new full backup
-    if [ "$extension" = "bak" ] && [ "$backup_type" != 'full' ]; then
+    if [ $extension = "bak" ] && [ "$backup_type" != 'full' ]; then
       transfer=1
     fi
 
     # Copy diff backups unless we're taking a new full or diff backup
-    if [ "$extension" = "diff" ] && [ "$backup_type" != 'full' ] && [ "$backup_type" != 'diff' ]; then
+    if [ $extension = "diff" ] && [ "$backup_type" != 'full' ] && [ "$backup_type" != 'diff' ]; then
       transfer=1
     fi
 
     # Copy transaction log backups unless we're taking a new full or diff backup
-    if [ "$extension" = "log" ] && [ "$backup_type" != 'full' ] && [ "$backup_type" != 'diff' ]; then
+    if [ $extension = "log" ] && [ "$backup_type" != 'full' ] && [ "$backup_type" != 'diff' ]; then
       transfer=1
     fi
 
     if [ -n "$transfer" ]; then
       ghe_verbose "Creating hard link to $filename"
-      ln "$last_mssql"/"$filename" "$backup_dir"/"$filename"
+      ln $last_mssql/$filename $backup_dir/$filename
     fi
   done
 fi
@@ -335,21 +304,21 @@ if [ -n "$backup_type" ]; then
   elif [ "$backup_type" = "transaction" ]; then
     backup_command='ghe-export-mssql -t'
   fi
-  
-  bm_start "$(basename "$0")"
-  ghe_ssh_mssql  -- "$backup_command" || failures="$failures mssql"
-  bm_end "$(basename "$0")"
+
+  bm_start "$(basename $0)"
+  ghe-ssh "$GHE_HOSTNAME" -- "$backup_command" || failures="$failures mssql"
+  bm_end "$(basename $0)"
 
   # Configure the backup cadence on the appliance, which is used for diagnostics
-  ghe_ssh_mssql "ghe-config mssql.backup.cadence $GHE_MSSQL_BACKUP_CADENCE"
+  ghe-ssh "$GHE_HOSTNAME" "ghe-config mssql.backup.cadence $GHE_MSSQL_BACKUP_CADENCE"
 
   # Transfer backup files from appliance to backup host
   appliance_dir="$GHE_REMOTE_DATA_DIR/user/mssql/backups"
   backups=$(echo "set -o pipefail; if sudo test -d \"$appliance_dir\"; then \
-    sudo ls \"$appliance_dir\"; fi" | ghe_ssh_mssql /bin/bash)
+    sudo ls \"$appliance_dir\"; fi" | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
   for b in $backups
   do
     ghe_verbose "Transferring to backup host $b"
-    ghe_ssh_mssql "sudo cat $appliance_dir/$b" > "$backup_dir"/"$b"
+    ghe-ssh "$GHE_HOSTNAME" "sudo cat $appliance_dir/$b" > $backup_dir/$b
   done
 fi
diff --git a/share/github-backup-utils/ghe-backup-settings b/share/github-backup-utils/ghe-backup-settings
--- a/share/github-backup-utils/ghe-backup-settings
+++ b/share/github-backup-utils/ghe-backup-settings
@@ -19,10 +19,10 @@ host="$GHE_HOSTNAME"
 mkdir -p "$GHE_SNAPSHOT_DIR"
 cd "$GHE_SNAPSHOT_DIR"
 
-log_info "* Transferring settings data ..." 1>&3
+echo "* Transferring settings data ..." 1>&3
 ghe-ssh "$host" -- 'ghe-export-settings' > settings.json
 
-log_info "* Transferring license data ..." 1>&3
+echo "* Transferring license data ..." 1>&3
 ghe-ssh "$host" -- "sudo cat '$GHE_REMOTE_LICENSE_FILE'" > enterprise.ghl
 
 # Function to backup a secret setting to a file.
@@ -61,7 +61,7 @@ backup-secret() {
     esac
   done
 
-  log_info "* Transferring $description ..." 1>&3
+  echo "* Transferring $description ..." 1>&3
   ghe-ssh "$host" -- ghe-config "$setting" > "$file+" || (
     if  [ "$best_effort" = "false" ]; then
       echo "Warning: $description not set" >&2
@@ -76,13 +76,6 @@ backup-secret() {
 
 backup-secret "management console password" "manage-password" "secrets.manage"
 backup-secret "password pepper" "password-pepper" "secrets.github.user-password-secrets"
-backup-secret "kredz.credz HMAC key" "kredz-credz-hmac" "secrets.kredz.credz-hmac-secret"
-backup-secret "kredz.varz HMAC key" "kredz-varz-hmac" "secrets.kredz.varz-hmac-secret"
-
-# Backup argon secrets for multiuser from ghes version 3.8 onwards
-if [ "$(version $GHE_REMOTE_VERSION)" -ge "$(version 3.8.0)" ]; then
-  backup-secret "management console argon2 secret" "manage-argon-secret" "secrets.manage-auth.argon-secret"
-fi
 
 # Backup external MySQL password if running external MySQL DB.
 if is_service_external 'mysql'; then
@@ -109,6 +102,7 @@ if ghe-ssh "$host" -- ghe-config --true app.actions.enabled; then
   backup-secret "Actions SPS validation cert thumbprint" "actions-sps-validation-cert-thumbprint" "secrets.actions.SpsValidationCertThumbprint"
 
   backup-secret "Actions Launch secrets encryption/decryption" "actions-launch-secrets-private-key" "secrets.launch.actions-secrets-private-key"
+  backup-secret "Actions Launch credz HMAC key" "actions-launch-credz-hmac" "secrets.launch.credz-hmac-secret"
   backup-secret "Actions Launch deployer HMAC key" "actions-launch-deployer-hmac" "secrets.launch.deployer-hmac-secret"
   backup-secret "Actions Launch Client id" "actions-launch-client-id" "secrets.launch.client-id"
   backup-secret "Actions Launch Client secret" "actions-launch-client-secret" "secrets.launch.client-secret"
@@ -132,57 +126,25 @@ if ghe-ssh "$host" -- ghe-config --true app.packages.enabled; then
   backup-secret "Packages azure container name" "packages-azure-container-name" "secrets.packages.azure-container-name"
 fi
 
-# Backup Chat Integration settings
-if ghe-ssh "$host" -- ghe-config --true app.chatops.enabled; then
-  backup-secret "Chat Integration MSTeams app id" "chatops-msteams-app-id" "secrets.chatops.msteams.app-id"
-  backup-secret "Chat Integration MSTeams app password" "chatops-msteams-app-password" "secrets.chatops.msteams.app-password"
-  backup-secret "Chat Integration MSTeams public endpoint" "chatops-msteams-app-public-endpoint" "secrets.chatops.msteams.public-endpoint"
-  backup-secret "Chat Integration MSTeams bot handle" "chatops-msteams-bot-handle" "secrets.chatops.msteams.bot-handle"
-  backup-secret "Chat Integration MSTeams bot name" "chatops-msteams-bot-name" "secrets.chatops.msteams.bot-name"
-  backup-secret "Chat Integration Slack app id" "chatops-slack-app-id" "secrets.chatops.slack.app-id"
-  backup-secret "Chat Integration Slack client id" "chatops-slack-client-id" "secrets.chatops.slack.client-id"
-  backup-secret "Chat Integration Slack client secret" "chatops-slack-client-secret" "secrets.chatops.slack.client-secret"
-  backup-secret "Chat Integration Slack verification token" "chatops-slack-verification-token" "secrets.chatops.slack.verification-token"
-  backup-secret "Chat Integration Slack config token" "chatops-slack-config-token" "secrets.chatops.slack.config-token"
-  backup-secret "Chat Integration Slack public endpoint" "chatops-slack-public-endpoint" "secrets.chatops.slack.public-endpoint"
-  backup-secret "Chat Integration Slack signing secret" "chatops-slack-signing-secret" "secrets.chatops.slack.signing-secret"
-  backup-secret "Chat Integration Slack app level token" "chatops-slack-app-level-token" "secrets.chatops.slack.app-level-token"
-  backup-secret "Chat Integration Slack slack command" "chatops-slack-slash-command" "secrets.chatops.slack.slash-command"
-  backup-secret "Chat Integration Slack app name" "chatops-slack.app-name" "secrets.chatops.slack.app-name"
-  backup-secret "Chat Integration Slack socket mode" "chatops-slack.socket-mode" "secrets.chatops.slack.socket-mode"
-  backup-secret "Chat Integration public endpoint" "chatops-public-endpoint" "secrets.chatops.public-endpoint"
-  backup-secret "Chat Integration app type" "chatops-app-type" "secrets.chatops.app-type"
-  backup-secret "Chat Integration app id teams" "chatops-app-id-teams" "secrets.chatops.app-id-teams"
-  backup-secret "Chat Integration webhook secret teams" "chatops-webhook-secret-teams" "secrets.chatops.webhook-secret-teams"
-  backup-secret "Chat Integration client secret teams" "chatops-client-secret-teams" "secrets.chatops.client-secret-teams"
-  backup-secret "Chat Integration clien id teams" "chatops-client-id-teams" "secrets.chatops.client-id-teams"
-  backup-secret "Chat Integration storage secret" "chatops-storage-secret" "secrets.chatops.storage-secret"
-  backup-secret "Chat Integration session secret" "chatops-session-secret" "secrets.chatops.session-secret"
-  backup-secret "Chat Integration app id slack" "chatops-app-id-slack" "secrets.chatops.app-id-slack"
-  backup-secret "Chat Integration webhook secret slack" "chatops-webhook-secret-slack" "secrets.chatops.webhook-secret-slack"
-  backup-secret "Chat Integration client secret slack" "chatops-client-secret-slack" "secrets.chatops.client-secret-slack"
-  backup-secret "Chat Integration client id slack" "chatops-client-id-slack" "secrets.chatops.client-id-slack"
-fi
-
 if ghe-ssh "$host" -- "test -f $GHE_REMOTE_DATA_USER_DIR/common/idp.crt"; then
-  log_info "* Transferring SAML keys ..." 1>&3
+  echo "* Transferring SAML keys ..." 1>&3
   ghe-ssh $host -- sudo tar -C $GHE_REMOTE_DATA_USER_DIR/common/ -cf - "idp.crt saml-sp.p12" > saml-keys.tar
 fi
 
 if ghe-ssh "$host" -- "which ghe-export-ssl-ca-certificates 1>/dev/null"; then
-  log_info "* Transferring CA certificates ..." 1>&3
+  echo "* Transferring CA certificates ..." 1>&3
   ghe-ssh "$host" -- "ghe-export-ssl-ca-certificates" > ssl-ca-certificates.tar
 fi
 
 if [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
-  log_info "* Transferring cluster configuration ..." 1>&3
+  echo "* Transferring cluster configuration ..." 1>&3
   if ! ghe-ssh "$host" -- "sudo cat $GHE_REMOTE_CLUSTER_CONF_FILE 2>/dev/null" > cluster.conf; then
-    log_error "Error: Enterprise Cluster is not configured yet, backup will fail" >&2
+    echo "Error: Enterprise Cluster is not configured yet, backup will fail" >&2
     exit 1
   fi
 else
   if ghe-ssh "$host" -- "sudo cat $GHE_REMOTE_DATA_USER_DIR/common/uuid 2>/dev/null" > uuid; then
-    log_info "* Transferring UUID ..." 1>&3
+    echo "* Transferring UUID ..." 1>&3
   fi
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-storage b/share/github-backup-utils/ghe-backup-storage
--- a/share/github-backup-utils/ghe-backup-storage
+++ b/share/github-backup-utils/ghe-backup-storage
@@ -19,7 +19,7 @@ backup_dir="$GHE_SNAPSHOT_DIR/storage"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  log_error "rsync not found." 1>&2
+  echo "Error: rsync not found." 1>&2
   exit 1
 fi
 
@@ -47,7 +47,7 @@ if [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
   ssh_config_file="$tempdir/ssh_config"
   ssh_config_file_opt="-F $ssh_config_file"
   opts="$opts -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
-  hostnames=$(ghe-cluster-find-nodes "$GHE_HOSTNAME" "storage-server")
+  hostnames=$(ghe-cluster-nodes "$GHE_HOSTNAME" "storage-server")
   ghe-ssh-config "$GHE_HOSTNAME" "$hostnames" > "$ssh_config_file"
 fi
 
@@ -60,7 +60,7 @@ cleanup() {
   # Enable remote maintenance operations
   for hostname in $hostnames; do
     ghe-gc-enable $ssh_config_file_opt $hostname:$port || { 
-      log_warn "Re-enable gc on $hostname failed, please manually delete $SYNC_IN_PROGRESS_FILE" 1>&2
+      echo "Re-enable gc on $hostname failed, please manually delete $SYNC_IN_PROGRESS_FILE" 1>&2
     }
   done
 
@@ -111,7 +111,7 @@ ghe_debug "\n$(find "$tempdir" -maxdepth 1 -name '*.rsync')"
 bm_end "$(basename $0) - Processing routes"
 
 if [ -z "$(find "$tempdir" -maxdepth 1 -name '*.rsync')" ]; then
-  log_warn "no routes found, skipping storage backup ..."
+  echo "Warning: no routes found, skipping storage backup ..."
   exit 0
 fi
 
@@ -123,7 +123,7 @@ for file_list in $tempdir/*.rsync; do
 
   object_num=$(cat $file_list | wc -l)
   ghe_verbose "* Transferring $object_num objects from $hostname"
-  log_rsync "BEGIN: storage rsync" 1>&3
+
   ghe-rsync -avr \
   -e "ssh -q $opts -p $port $ssh_config_file_opt -l $user" \
   $link_dest "$@" \
@@ -133,7 +133,6 @@ for file_list in $tempdir/*.rsync; do
   --size-only \
   "$hostname:$GHE_REMOTE_DATA_USER_DIR/storage/" \
   "$backup_dir" 1>&3 &
-  log_rsync "END: storage rsync" 1>&3
 done
 
 for pid in $(jobs -p); do
diff --git a/share/github-backup-utils/ghe-gc-disable b/share/github-backup-utils/ghe-gc-disable
--- a/share/github-backup-utils/ghe-gc-disable
+++ b/share/github-backup-utils/ghe-gc-disable
@@ -50,7 +50,7 @@ echo "
 " | ghe-ssh $opts "$host" -- /bin/bash || {
   res=$?
   if [ $res = 7 ]; then
-    log_error "Error: Git GC processes remain after $GHE_GIT_COOLDOWN_PERIOD seconds. Aborting..." 1>&2
+    echo "Error: Git GC processes remain after $GHE_GIT_COOLDOWN_PERIOD seconds. Aborting..." 1>&2
   fi
   exit $res
 }
diff --git a/share/github-backup-utils/ghe-restore-snapshot-path b/share/github-backup-utils/ghe-restore-snapshot-path
--- a/share/github-backup-utils/ghe-restore-snapshot-path
+++ b/share/github-backup-utils/ghe-restore-snapshot-path
@@ -25,7 +25,7 @@ fi
 # Bail out if we don't have a good snapshot.
 if [ -z "$GHE_RESTORE_SNAPSHOT" ] || [ ! -d "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT" ]; then
   : "${GHE_RESTORE_SNAPSHOT:=current}"
-  log_error "Error: Snapshot '$GHE_RESTORE_SNAPSHOT' doesn't exist." 1>&2
+  echo "Error: Snapshot '$GHE_RESTORE_SNAPSHOT' doesn't exist." 1>&2
   exit 1
 fi
 
