Make the criteria clearer
... and a force option and fix typo inconsistency

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -123,14 +123,19 @@ if ghe-ssh "$GHE_HOSTNAME" -- \
   exit 1
 fi
 
-# Only allow restores of 2.9 and 2.10 to 2.11 and above, after running the audit log migration
-if ! test -f $GHE_RESTORE_SNAPSHOT_PATH/es-scan-complete && \
-   ! echo $snapshot_instance_version | grep -Eq "v2\.[1-9][1-9]" && \
-   echo $GHE_REMOTE_VERSION | grep -Eq "v2\.[1-9][1-9]"; then
-      echo "Error: Snapshot must be from GitHub Enterprise v2.9 or v.2.10 after running the" >&2
-      echo "       audit log migration, or from 2.11.0 or above." >&2
-      echo "Please see https://git.io/v5rCE for the audit log migration procedure." >&2
-      exit 1
+# Only allow restores of 2.9 and 2.10 snapshots that have run the audit log migration to 2.11 and above
+if ! $force; then
+  snapshot_instance_version=$(cat $GHE_RESTORE_SNAPSHOT_PATH/version)
+  snapshot_version_major=$(echo "${snapshot_instance_version#v}" | cut -f 1 -d .)
+  snapshot_version_minor=$(echo "$snapshot_instance_version"     | cut -f 2 -d .)
+  if ! test -f $GHE_RESTORE_SNAPSHOT_PATH/es-scan-complete && \
+     [ "$snapshot_version_major" -eq 2 ] && [ "$snapshot_version_minor" -lt 11 ] && \
+     [ "$GHE_VERSION_MAJOR" -eq 2 ] && [ "$GHE_VERSION_MINOR" -ge 11 ]; then
+        echo "Error: Snapshot must be from GitHub Enterprise v2.9 or v2.10 after running the" >&2
+        echo "       audit log migration, or from v2.11.0 or above." >&2
+        echo "Please see https://git.io/v5rCE for the audit log migration procedure." >&2
+        exit 1
+  fi
 fi
 
 # Prompt to verify the restore host given is correct. Restoring overwrites
