Update bin/ghe-host-check
Co-authored-by: Caine Jette <cainejette@github.com>

diff --git a/bin/ghe-host-check b/bin/ghe-host-check
--- a/bin/ghe-host-check
+++ b/bin/ghe-host-check
@@ -50,20 +50,11 @@ fi
 if "$CLUSTER"; then
   node_version_list=$(ghe-ssh "$host" ghe-cluster-each -- ghe-version)
   echo "$node_version_list" 1>&2
-  first_node_version=""
-  (
-    IFS=$'\n'
-    for node_version in $node_version_list; do
-      if [ -z "$first_node_version" ]; then
-        first_node_version=$(echo "$node_version" | cut -f2 -d":")
-      fi
-      current_node_version=$(echo "$node_version" | cut -f2 -d":")
-      if [ "$first_node_version" != "$current_node_version" ]; then
-        echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&2
-        exit 1
-      fi
-    done
-  )
+  distinct_versions=$(echo "$node_version_list" | awk '{split($0, a, ":"); print a[2]}' | uniq | wc -l)
+  if [ $distinct_versions -ne 1 ]; then
+    echo "Error: Not all nodes are running the same version! Please ensure all nodes are running the same version before using backup-utils." 1>&2
+    exit 1
+  fi
 fi
 
 # Options to pass to SSH during connection check
