Attempt to manually cleanup cluster nodes.
ghe-cluster-cleanup-node is being removed in later versions of GHES,
so we should remove its reference in backup-utils as well. This will
run the same set of commands that the script did.

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -451,7 +451,19 @@ if ! $CLUSTER && $instance_configured; then
   if [ -n "$other_nodes" ]; then
     echo "Cleaning up stale nodes ..."
     for uuid in $other_nodes; do
-      ghe-ssh "$GHE_HOSTNAME" -- "/usr/local/share/enterprise/ghe-cluster-cleanup-node $uuid" 1>&3
+      1>&3 ghe-ssh "$GHE_HOSTNAME" <<-EOF
+        if [ -z "$uuid" ]; then
+          echo "Node UUID required."
+          exit 2
+        fi
+        ghe-spokes server evacuate git-server-$uuid 'Removing replica'
+        ghe-spokes server destroy git-server-$uuid
+        ghe-storage destroy-host storage-server-$uuid --force
+        ghe-dpages offline pages-server-$uuid
+        ghe-dpages remove pages-server-$uuid
+        ghe-redis-cli del resque:queue:maint_git-server-$uuid
+        ghe-redis-cli srem resque:queues maint_git-server-$uuid
+      EOF
     done
   fi
 fi
