Added a new GHE_REMOTE_GIT_FSCK option
Run git fsck remotely after a restore and report the results.

Looks something like:

```
Restoring MySQL database ...
 --> Importing MySQL data...
Restoring Redis database ...
Restoring Git repositories into cluster ...
Restoring Gists into cluster ...
Checking remote git repositories ...
Running git fsck on ghe-test-cluster-migration-node1 ...
* Repos verified: 4, Errors: 1, Took: 5s
Running git fsck on ghe-test-cluster-migration-node2 ...
* Repos verified: 4, Errors: 0, Took: 5s
Running git fsck on ghe-test-cluster-migration-node3 ...
* Repos verified: 4, Errors: 0, Took: 4s
Running git fsck on ghe-test-cluster-migration-node4 ...
* Repos verified: 3, Errors: 0, Took: 4s
```

When the verbose mode is enabled:

```
Restoring MySQL database ...
 --> Importing MySQL data...
Restoring Redis database ...
Restoring Git repositories into cluster ...
Restoring Gists into cluster ...
Checking remote git repositories ...
Running git fsck on ghe-test-cluster-migration-node1 ...
ERROR /data/user/repositories/c/nw/c8/1e/72/2/2.git ghe-admin/test2 1s
error: HEAD: invalid sha1 pointer 8dc523028e592fb72020f6f1901ac033e326eebb
error: refs/heads/master: invalid sha1 pointer 8dc523028e592fb72020f6f1901ac033e326eebb
error: refs/heads/master: invalid reflog entry 8dc523028e592fb72020f6f1901ac033e326eebb
notice: No default references
* Repos verified: 4, Errors: 1, Took: 5s
Running git fsck on ghe-test-cluster-migration-node2 ...
* Repos verified: 4, Errors: 0, Took: 5s
Running git fsck on ghe-test-cluster-migration-node3 ...
* Repos verified: 4, Errors: 0, Took: 4s
Running git fsck on ghe-test-cluster-migration-node4 ...
* Repos verified: 3, Errors: 0, Took: 4s
```

It will exit 1 if the remote fsck fails and GHE_REMOTE_GIT_FSCK_ABORT_ON_ERROR=yes,
warn otherwise.

Note: git fsck is quite expensive and slow on large installs and for now it's only
useful for debugging/troubleshooting so the new option is disabled by default.

diff --git a/bin/ghe-restore b/bin/ghe-restore
--- a/bin/ghe-restore
+++ b/bin/ghe-restore
@@ -235,6 +235,22 @@ else
   ghe-restore-repositories-${GHE_BACKUP_STRATEGY} "$GHE_HOSTNAME" 1>&3
 fi
 
+# git fsck repositories after restoring the repositories
+if [ "$GHE_REMOTE_GIT_FSCK" = "yes" ]; then
+  echo "Checking remote git repositories ..."
+  cmd="ghe-remote-git-fsck"
+  if $cluster; then
+    cmd="ghe-remote-git-fsck-cluster"
+  fi
+  if ! $cmd $GHE_HOSTNAME; then
+    if [ "$GHE_REMOTE_GIT_FSCK_ABORT_ON_ERROR" = "yes" ]; then
+      exit 1
+    else
+      echo "Warning: remote git fsck failed, ignoring"
+    fi
+  fi
+fi
+
 if $cluster; then
   echo "Restoring GitHub Pages into DPages..."
   ghe-restore-pages-dpages "$GHE_HOSTNAME" 1>&3
