Mimic no index during testing

diff --git a/test/bin/curl b/test/bin/curl
--- a/test/bin/curl
+++ b/test/bin/curl
@@ -6,6 +6,9 @@ set -e
 # Return empty list of indexes for ghe-backup-es-audit-log
 if echo "$@" | grep -q '_cat/indices/audit_log\*?h=index$'; then
   exit 0
+# Exit with non-zero code to mimic a non-existant index
+elif echo "$@" | grep -q 'localhost:9201/audit_log'; then
+  exit 1
 fi
 
 # Write args to stdout
