Use consistent two-space indentation

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -17,12 +17,12 @@ export GHE_VERBOSE_SSH=true
 res=true
 for version in $REMOTE_VERSIONS
 do
-    echo "==> Running testsuite with GHE_TEST_REMOTE_VERSION=$version"
-    export GHE_TEST_REMOTE_VERSION="$version"
-    if ! ls -1 test/test-*.sh | xargs -P 4 -n 1 /bin/bash; then
-        res=false
-    fi
-    echo
+  echo "==> Running testsuite with GHE_TEST_REMOTE_VERSION=$version"
+  export GHE_TEST_REMOTE_VERSION="$version"
+  if ! ls -1 test/test-*.sh | xargs -P 4 -n 1 /bin/bash; then
+    res=false
+  fi
+  echo
 done
 
 # If any of the version tests failed, exit non-zero
@@ -35,31 +35,34 @@ $res
 pkg_files=
 
 # Build the tarball
+ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
+TMPDIR="$ROOTDIR/test/tmp"
+
 echo "Building tar.gz package ..."
-if script/package-tarball 1>package-tarball.txt 2>&1; then
-    pkg_files=$(grep '^Package ' < package-tarball.txt | cut -f 2 -d ' ')
+if script/package-tarball 1>$TMPDIR/package-tarball.txt 2>&1; then
+  pkg_files=$(grep '^Package ' < $TMPDIR/package-tarball.txt | cut -f 2 -d ' ')
 else
-    echo "Packaging tar.gz failed:"
-    cat package-tarball.txt | sed 's/^/    /' 1>&2
-    exit 1
+  echo "Packaging tar.gz failed:"
+  cat $TMPDIR/package-tarball.txt | sed 's/^/    /' 1>&2
+  exit 1
 fi
 
 # Skip deb packaging if debuild not installed
 if ! type debuild 1>/dev/null 2>&1; then
-    echo "debuild not installed, skipping deb packaging ..."
-    exit 0
+  echo "debuild not installed, skipping deb packaging ..."
+  exit 0
 fi
 
 # Build the deb related packages
 echo "Building deb package ..."
-if DEB_BUILD_OPTIONS=nocheck script/package-deb 1>package-deb-out.txt 2>package-deb-err.txt; then
-    pkg_files="$pkg_files $(cat package-deb-out.txt)"
+if DEB_BUILD_OPTIONS=nocheck script/package-deb 1>$TMPDIR/package-deb-out.txt 2>$TMPDIR/package-deb-err.txt; then
+  pkg_files="$pkg_files $(cat $TMPDIR/package-deb-out.txt)"
 else
-    echo "Package build failed:"
-    cat package-deb-out.txt package-deb-err.txt >&2
-    echo >&2
-    cat dist/debuild/github-backup-utils*.build >&2
-    exit 1
+  echo "Package build failed:"
+  cat $TMPDIR/package-deb-out.txt $TMPDIR/package-deb-err.txt >&2
+  echo >&2
+  cat dist/debuild/github-backup-utils*.build >&2
+  exit 1
 fi
 
 # Generate md5sums
diff --git a/share/github-backup-utils/ghe-backup-config b/share/github-backup-utils/ghe-backup-config
--- a/share/github-backup-utils/ghe-backup-config
+++ b/share/github-backup-utils/ghe-backup-config
@@ -36,8 +36,8 @@ fi
 
 # Check for "--help|-h" in args or GHE_SHOW_HELP=true and show usage
 print_usage () {
-    grep '^#/' <"$0" | cut -c 4-
-    exit ${1:-1}
+  grep '^#/' <"$0" | cut -c 4-
+  exit ${1:-1}
 }
 
 if [ -n "$GHE_SHOW_HELP" ]; then
@@ -64,22 +64,22 @@ GHE_HOSTNAME_PRESERVE="$GHE_HOSTNAME"
 config_found=false
 for f in "$GHE_BACKUP_CONFIG" "$GHE_BACKUP_ROOT/backup.config" \
   "$HOME/.github-backup-utils/backup.config" "/etc/github-backup-utils/backup.config"; do
-    if [ -f "$f" ]; then
-        GHE_BACKUP_CONFIG="$f"
-        . "$GHE_BACKUP_CONFIG"
-        config_found=true
-        break
-    fi
+  if [ -f "$f" ]; then
+    GHE_BACKUP_CONFIG="$f"
+    . "$GHE_BACKUP_CONFIG"
+    config_found=true
+    break
+  fi
 done
 
 # Check that the config file exists before we source it in.
 if ! $config_found; then
-    echo "Error: No backup configuration file found. Tried:" 1>&2
-    [ -n "$GHE_BACKUP_CONFIG" ] && echo " - $GHE_BACKUP_CONFIG" 1>&2
-    echo " - $GHE_BACKUP_ROOT/backup.config" 1>&2
-    echo " - $HOME/.github-backup-utils/backup.config" 1>&2
-    echo " - /etc/github-backup-utils/backup.config" 1>&2
-    exit 2
+  echo "Error: No backup configuration file found. Tried:" 1>&2
+  [ -n "$GHE_BACKUP_CONFIG" ] && echo " - $GHE_BACKUP_CONFIG" 1>&2
+  echo " - $GHE_BACKUP_ROOT/backup.config" 1>&2
+  echo " - $HOME/.github-backup-utils/backup.config" 1>&2
+  echo " - /etc/github-backup-utils/backup.config" 1>&2
+  exit 2
 fi
 
 # Restore saved off hostname.
@@ -87,14 +87,14 @@ fi
 
 # Check that the GHE hostname is set.
 if [ -z "$GHE_HOSTNAME" ]; then
-    echo "Error: GHE_HOSTNAME not set in config file." 1>&2
-    exit 2
+  echo "Error: GHE_HOSTNAME not set in config file." 1>&2
+  exit 2
 fi
 
 # Check that the GHE data directory is set.
 if [ -z "$GHE_DATA_DIR" ]; then
-    echo "Error: GHE_DATA_DIR not set in config file." 1>&2
-    exit 2
+  echo "Error: GHE_DATA_DIR not set in config file." 1>&2
+  exit 2
 fi
 
 # Convert the data directory path to an absolute path, basing any relative
@@ -120,13 +120,13 @@ GHE_CREATE_DATA_DIR=${GHE_CREATE_DATA_DIR:-yes}
 
 # Check that the data directory is set and create it if it doesn't exist.
 if [ ! -d "$GHE_DATA_DIR" ] && [ "$GHE_CREATE_DATA_DIR" = "yes" ]; then
-    echo "Creating the backup data directory ..." 1>&3
-    mkdir -p "$GHE_DATA_DIR"
+  echo "Creating the backup data directory ..." 1>&3
+  mkdir -p "$GHE_DATA_DIR"
 fi
 
 if [ ! -d "$GHE_DATA_DIR" ]; then
-    echo "Error: GHE_DATA_DIR $GHE_DATA_DIR does not exist." >&2
-    exit 8
+  echo "Error: GHE_DATA_DIR $GHE_DATA_DIR does not exist." >&2
+  exit 8
 fi
 
 # Set some defaults if needed.
@@ -189,9 +189,9 @@ GHE_SNAPSHOT_DIR="$GHE_DATA_DIR"/"$GHE_SNAPSHOT_TIMESTAMP"
 # called immediately after the remote version is obtained by
 # ghe_remote_version_required(). Child processes inherit the values set here.
 ghe_remote_version_config () {
-    GHE_REMOTE_DATA_USER_DIR="$GHE_REMOTE_DATA_DIR/user"
-    export GHE_REMOTE_DATA_DIR GHE_REMOTE_DATA_USER_DIR
-    export GHE_REMOTE_LICENSE_FILE
+  GHE_REMOTE_DATA_USER_DIR="$GHE_REMOTE_DATA_DIR/user"
+  export GHE_REMOTE_DATA_DIR GHE_REMOTE_DATA_USER_DIR
+  export GHE_REMOTE_LICENSE_FILE
 }
 
 ###############################################################################
@@ -199,13 +199,13 @@ ghe_remote_version_config () {
 
 # If we don't have a readlink command, parse ls -l output.
 if ! type readlink 1>/dev/null 2>&1; then
-    readlink () {
-        if [ -x "$1" ]; then
-            ls -ld "$1" | sed 's/.*-> //'
-        else
-            return 1
-        fi
-    }
+  readlink () {
+    if [ -x "$1" ]; then
+      ls -ld "$1" | sed 's/.*-> //'
+    else
+      return 1
+    fi
+  }
 fi
 
 # Run ghe-host-check and establish the version of the remote GitHub instance in
@@ -215,22 +215,22 @@ fi
 # ghe-host-check directly to reduce ssh roundtrips. The top-level ghe-backup and
 # ghe-restore commands establish the version for all subcommands.
 ghe_remote_version_required () {
-    if [ -z "$GHE_REMOTE_VERSION" ]; then
-        _out=$(ghe-host-check "$@")
-        echo "$_out"
+  if [ -z "$GHE_REMOTE_VERSION" ]; then
+    _out=$(ghe-host-check "$@")
+    echo "$_out"
 
-        # override hostname w/ ghe-host-check output because the port could have
-        # been autodetected to 122.
-        GHE_HOSTNAME=$(echo "$_out" | sed 's/Connect \(.*:[0-9]*\) OK.*/\1/')
-        export GHE_HOSTNAME
+    # override hostname w/ ghe-host-check output because the port could have
+    # been autodetected to 122.
+    GHE_HOSTNAME=$(echo "$_out" | sed 's/Connect \(.*:[0-9]*\) OK.*/\1/')
+    export GHE_HOSTNAME
 
-        GHE_REMOTE_VERSION=$(echo "$_out" | sed 's/.*(\(.*\))/\1/')
-        export GHE_REMOTE_VERSION
+    GHE_REMOTE_VERSION=$(echo "$_out" | sed 's/.*(\(.*\))/\1/')
+    export GHE_REMOTE_VERSION
 
-        ghe_parse_remote_version "$GHE_REMOTE_VERSION"
-        ghe_remote_version_config "$GHE_REMOTE_VERSION"
-    fi
-    true
+    ghe_parse_remote_version "$GHE_REMOTE_VERSION"
+    ghe_remote_version_config "$GHE_REMOTE_VERSION"
+  fi
+  true
 }
 
 # Parse major, minor, and patch parts of the remote appliance version and store
@@ -241,34 +241,34 @@ ghe_remote_version_required () {
 # Scripts use these variables to alter behavior based on what's supported on the
 # appliance version.
 ghe_parse_remote_version () {
-    GHE_VERSION_MAJOR=$(echo "${1#v}" | cut -f 1 -d .)
-    GHE_VERSION_MINOR=$(echo "$1"     | cut -f 2 -d .)
-    GHE_VERSION_PATCH=$(echo "$1"     | cut -f 3 -d .)
-    GHE_VERSION_PATCH=${GHE_VERSION_PATCH%%[a-zA-Z]*}
+  GHE_VERSION_MAJOR=$(echo "${1#v}" | cut -f 1 -d .)
+  GHE_VERSION_MINOR=$(echo "$1"     | cut -f 2 -d .)
+  GHE_VERSION_PATCH=$(echo "$1"     | cut -f 3 -d .)
+  GHE_VERSION_PATCH=${GHE_VERSION_PATCH%%[a-zA-Z]*}
 
-    export GHE_VERSION_MAJOR GHE_VERSION_MINOR GHE_VERSION_PATCH
+  export GHE_VERSION_MAJOR GHE_VERSION_MINOR GHE_VERSION_PATCH
 }
 
 # Parses the <host> part out of a "<host>:<port>" or just "<host>" string.
 # This is used primarily to break hostspecs with non-standard ports down for
 # rsync commands.
 ssh_host_part () {
-    [ "${1##*:}" = "$1" ] && echo "$1" || echo "${1%:*}"
+  [ "${1##*:}" = "$1" ] && echo "$1" || echo "${1%:*}"
 }
 
 # Parses the <port> part out of a "<host>:<port>" or just "<host>" string.
 # This is used primarily to break hostspecs with non-standard ports down for
 # rsync commands.
 ssh_port_part () {
-    [ "${1##*:}" = "$1" ] && echo 22 || echo "${1##*:}"
+  [ "${1##*:}" = "$1" ] && echo 22 || echo "${1##*:}"
 }
 
 # Usage: ghe_remote_logger <message>...
 # Log a message to /var/log/syslog on the remote instance.
 # Note: Use sparingly. Remote logging requires an ssh connection per invocation.
 ghe_remote_logger () {
-    echo "$@" |
-    ghe-ssh "$GHE_HOSTNAME" -- logger -t backup-utils || true
+  echo "$@" |
+  ghe-ssh "$GHE_HOSTNAME" -- logger -t backup-utils || true
 }
 
 # Usage: ghe_verbose <message>
diff --git a/share/github-backup-utils/ghe-backup-git-hooks b/share/github-backup-utils/ghe-backup-git-hooks
--- a/share/github-backup-utils/ghe-backup-git-hooks
+++ b/share/github-backup-utils/ghe-backup-git-hooks
@@ -13,8 +13,8 @@ bm_start "$(basename $0)"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-    echo "Error: rsync not found." 1>&2
-    exit 1
+  echo "Error: rsync not found." 1>&2
+  exit 1
 fi
 
 bm_start "$(basename $0)"
@@ -61,42 +61,41 @@ trap 'exit $?' INT # ^C always terminate
 # already been transferred. A set of rsync filter rules are provided on stdin
 # for each invocation.
 rsync_git_hooks_data () {
-    port=$(ssh_port_part "$1")
-    host=$(ssh_host_part "$1")
+  port=$(ssh_port_part "$1")
+  host=$(ssh_host_part "$1")
 
-    subpath=$2
-    shift 2
+  subpath=$2
+  shift 2
 
-    # If we have a previous increment and it is not empty, avoid transferring existing files via rsync's
-    # --link-dest support. This also decreases physical space usage considerably.
-    if [ -d "$backup_current/$subpath" ] && [ "$(ls -A $backup_current/$subpath)" ]; then
+  # If we have a previous increment and it is not empty, avoid transferring existing files via rsync's
+  # --link-dest support. This also decreases physical space usage considerably.
+  if [ -d "$backup_current/$subpath" ] && [ "$(ls -A $backup_current/$subpath)" ]; then
+    subdir="git-hooks/$subpath"
+    link_path=".."
+    while true; do
+      if [ $(dirname $subdir) = "." ]; then
+        break
+      fi
 
-      subdir="git-hooks/$subpath"
-      link_path=".."
-      while true; do
-        if [ $(dirname $subdir) = "." ]; then
-          break
-        fi
+      if [ $(dirname $subdir) = "/" ]; then
+        break
+      fi
 
-        if [ $(dirname $subdir) = "/" ]; then
-          break
-        fi
+      link_path="../$link_path"
+      subdir=$(dirname $subdir)
+    done
 
-        link_path="../$link_path"
-        subdir=$(dirname $subdir)
-      done
+    local link_dest="--link-dest=../${link_path}/current/git-hooks/$subpath"
+  fi
 
-      local link_dest="--link-dest=../${link_path}/current/git-hooks/$subpath"
-    fi
+  # Ensure target directory exists, is needed with subdirectories
+  mkdir -p "$backup_dir/$subpath"
 
-    # Ensure target directory exists, is needed with subdirectories
-    mkdir -p "$backup_dir/$subpath"
-
-    ghe-rsync -av \
-        -e "ssh -q $opts -p $port $ssh_config_file_opt -l $user" $link_dest \
-        --rsync-path='sudo -u git rsync' \
-        "$host:$GHE_REMOTE_DATA_USER_DIR/git-hooks/$subpath/" \
-        "$backup_dir/$subpath" 1>&3
+  ghe-rsync -av \
+    -e "ssh -q $opts -p $port $ssh_config_file_opt -l $user" $link_dest \
+    --rsync-path='sudo -u git rsync' \
+    "$host:$GHE_REMOTE_DATA_USER_DIR/git-hooks/$subpath/" \
+    "$backup_dir/$subpath" 1>&3
 }
 
 hostname=$(echo $hostnames | awk '{ print $1; }')
diff --git a/share/github-backup-utils/ghe-backup-pages b/share/github-backup-utils/ghe-backup-pages
--- a/share/github-backup-utils/ghe-backup-pages
+++ b/share/github-backup-utils/ghe-backup-pages
@@ -17,8 +17,8 @@ backup_dir="$GHE_SNAPSHOT_DIR/pages"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-    echo "Error: rsync not found." 1>&2
-    exit 1
+  echo "Error: rsync not found." 1>&2
+  exit 1
 fi
 
 # Perform a host-check and establish GHE_REMOTE_XXX variables.
@@ -74,11 +74,11 @@ for hostname in $hostnames; do
 
   # Transfer all data from the user data directory using rsync.
   ghe-rsync -avz \
-      -e "ssh -q $opts -p 122 $ssh_config_file_opt -l $user" \
-      --rsync-path='sudo -u git rsync' \
-      $link_dest \
-      "$hostname:$GHE_REMOTE_DATA_USER_DIR/pages/" \
-      "$GHE_SNAPSHOT_DIR/pages" 1>&3
+    -e "ssh -q $opts -p 122 $ssh_config_file_opt -l $user" \
+    --rsync-path='sudo -u git rsync' \
+    $link_dest \
+    "$hostname:$GHE_REMOTE_DATA_USER_DIR/pages/" \
+    "$GHE_SNAPSHOT_DIR/pages" 1>&3
   bm_end "$(basename $0) - $hostname"
 done
 
diff --git a/share/github-backup-utils/ghe-backup-storage b/share/github-backup-utils/ghe-backup-storage
--- a/share/github-backup-utils/ghe-backup-storage
+++ b/share/github-backup-utils/ghe-backup-storage
@@ -18,8 +18,8 @@ backup_dir="$GHE_SNAPSHOT_DIR/storage"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-    echo "Error: rsync not found." 1>&2
-    exit 1
+  echo "Error: rsync not found." 1>&2
+  exit 1
 fi
 
 # Perform a host-check and establish GHE_REMOTE_XXX variables.
diff --git a/share/github-backup-utils/ghe-backup-userdata b/share/github-backup-utils/ghe-backup-userdata
--- a/share/github-backup-utils/ghe-backup-userdata
+++ b/share/github-backup-utils/ghe-backup-userdata
@@ -12,8 +12,8 @@ bm_start "$(basename $0) - $1"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-    echo "Error: rsync not found." 1>&2
-    exit 1
+  echo "Error: rsync not found." 1>&2
+  exit 1
 fi
 
 # Grab the host and /data/user directory name.
@@ -54,10 +54,10 @@ mkdir -p "$GHE_SNAPSHOT_DIR/$dirname"
 
 # Transfer all data from the user data directory using rsync.
 ghe-rsync -avz \
-    -e "ghe-ssh -p $(ssh_port_part "$host")" \
-    --rsync-path='sudo -u git rsync' \
-    $link_dest \
-    "$(ssh_host_part "$host"):$GHE_REMOTE_DATA_USER_DIR/$dirname/" \
-    "$GHE_SNAPSHOT_DIR/$dirname" 1>&3
+  -e "ghe-ssh -p $(ssh_port_part "$host")" \
+  --rsync-path='sudo -u git rsync' \
+  $link_dest \
+  "$(ssh_host_part "$host"):$GHE_REMOTE_DATA_USER_DIR/$dirname/" \
+  "$GHE_SNAPSHOT_DIR/$dirname" 1>&3
 
 bm_end "$(basename $0) - $1"
diff --git a/share/github-backup-utils/ghe-restore-snapshot-path b/share/github-backup-utils/ghe-restore-snapshot-path
--- a/share/github-backup-utils/ghe-restore-snapshot-path
+++ b/share/github-backup-utils/ghe-restore-snapshot-path
@@ -18,13 +18,13 @@ fi
 # Resolve the snapshot id if we're restoring from current. This is mostly
 # just for logging.
 if [ "$GHE_RESTORE_SNAPSHOT" = "current" ]; then
-    GHE_RESTORE_SNAPSHOT=$(readlink "$GHE_DATA_DIR"/current || true)
+  GHE_RESTORE_SNAPSHOT=$(readlink "$GHE_DATA_DIR"/current || true)
 fi
 
 # Bail out if we don't have a good snapshot.
 if [ ! -d "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT" ]; then
-    echo "Error: Snapshot '$GHE_RESTORE_SNAPSHOT' doesn't exist." 1>&2
-    exit 1
+  echo "Error: Snapshot '$GHE_RESTORE_SNAPSHOT' doesn't exist." 1>&2
+  exit 1
 fi
 
 echo "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT"
diff --git a/share/github-backup-utils/ghe-restore-userdata b/share/github-backup-utils/ghe-restore-userdata
--- a/share/github-backup-utils/ghe-restore-userdata
+++ b/share/github-backup-utils/ghe-restore-userdata
@@ -19,8 +19,8 @@ GHE_HOSTNAME="$2"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-    echo "Error: rsync not found." 1>&2
-    exit 1
+  echo "Error: rsync not found." 1>&2
+  exit 1
 fi
 
 # Perform a host-check and establish GHE_REMOTE_XXX variables.
@@ -37,10 +37,10 @@ if [ -d "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/$dirname" ]; then
   ghe-ssh "$GHE_HOSTNAME" -- "sudo -u git mkdir -p $GHE_REMOTE_DATA_USER_DIR/$dirname"
 
   ghe-rsync -avz --delete \
-      -e "ghe-ssh -p $(ssh_port_part "$GHE_HOSTNAME")" \
-      --rsync-path="sudo -u git rsync" \
-      "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/$dirname/" \
-      "$(ssh_host_part "$GHE_HOSTNAME"):$GHE_REMOTE_DATA_USER_DIR/$dirname" 1>&3
+    -e "ghe-ssh -p $(ssh_port_part "$GHE_HOSTNAME")" \
+    --rsync-path="sudo -u git rsync" \
+    "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/$dirname/" \
+    "$(ssh_host_part "$GHE_HOSTNAME"):$GHE_REMOTE_DATA_USER_DIR/$dirname" 1>&3
 fi
 
 bm_end "$(basename $0) - $1"
diff --git a/share/github-backup-utils/ghe-ssh b/share/github-backup-utils/ghe-ssh
--- a/share/github-backup-utils/ghe-ssh
+++ b/share/github-backup-utils/ghe-ssh
@@ -12,29 +12,29 @@ set -e
 
 opts="$GHE_EXTRA_SSH_OPTS"
 while true; do
-    case "$1" in
-        -p)
-            port="$2"
-            shift 2
-            ;;
-        -l|-o|-F)
-            opts="$opts $1 $2"
-            shift 2
-            ;;
-        -c|--clean)
-            cleanup_mux=1
-            shift
-            ;;
-        --)
-            echo "Error: illegal '--' in ssh invocation"
-            exit 1
-            ;;
-        *)
-            host="$1"
-            shift
-            break
-            ;;
-    esac
+  case "$1" in
+    -p)
+      port="$2"
+      shift 2
+      ;;
+    -l|-o|-F)
+      opts="$opts $1 $2"
+      shift 2
+      ;;
+    -c|--clean)
+      cleanup_mux=1
+      shift
+      ;;
+    --)
+      echo "Error: illegal '--' in ssh invocation"
+      exit 1
+      ;;
+    *)
+      host="$1"
+      shift
+      break
+      ;;
+  esac
 done
 
 # Show usage with no host
@@ -42,7 +42,7 @@ done
 
 # Shift off '--' if given immediately after host.
 if [ "$1" = "--" ]; then
-    shift
+  shift
 fi
 
 # Split host:port into parts. The port is only used if not specified earlier.
@@ -57,9 +57,9 @@ opts="-l $user $opts"
 # Bail out with error if the simple command form is used with complex commands.
 # Complex
 if echo "$*" | grep "[|;]" >/dev/null || [ $(echo "$*" | wc -l) -gt 1 ]; then
-    echo "fatal: ghe-ssh: Attempt to invoke complex command with simple command form." 1>&2
-    echo "See ghe-ssh --help for more on correcting." 1>&2
-    exit 1
+  echo "fatal: ghe-ssh: Attempt to invoke complex command with simple command form." 1>&2
+  echo "See ghe-ssh --help for more on correcting." 1>&2
+  exit 1
 fi
 
 if [ -z "$GHE_DISABLE_SSH_MUX" ]; then
