Remove extra loop

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -2,28 +2,19 @@
 # Usage: script/cibuild [--no-package]
 set -e
 
-# GHE appliance versions to run tests against. Remote metadata files are put in
-# place with this version at the beginning of each test and many commands have
-# conditional logic based on the remote version. Running the suite against
-# different major versions ensures we're covering these conditional paths.
-REMOTE_VERSIONS="2.19.0 2.20.0 2.21.0"
-
 # Enable verbose logging of ssh commands
 export GHE_VERBOSE_SSH=true
 
-# Run over all remote versions and run entire test suite against each
 res=true
-for version in $REMOTE_VERSIONS
-do
-  echo "==> Running testsuite with GHE_TEST_REMOTE_VERSION=$version"
-  export GHE_TEST_REMOTE_VERSION="$version"
-  if ! find test -name "test-*.sh" -print0 | xargs -0 -P 4 -n 1 /bin/bash; then
-    res=false
-  fi
-  echo
-done
+version=2.21.0
+echo "==> Running testsuite with GHE_TEST_REMOTE_VERSION=$version"
+export GHE_TEST_REMOTE_VERSION="$version"
+if ! find test -name "test-*.sh" -print0 | xargs -0 -P 4 -n 1 /bin/bash; then
+  res=false
+fi
+echo
 
-# If any of the version tests failed, exit non-zero
+# If any of the tests above failed, exit non-zero
 $res
 
 # Bail out when --no-package given
