Generalize 'git-gc processes remain ...' error message
The error message is a bit misleading since this can match git-gc
and git-nw-repack processes now. The point here is to convey that GC
processes didn't complete within the cooldown period, though, so I
think it's fine to generalize a bit here instead of listing the
various GC commands.

diff --git a/libexec/ghe-backup-repositories-rsync b/libexec/ghe-backup-repositories-rsync
--- a/libexec/ghe-backup-repositories-rsync
+++ b/libexec/ghe-backup-repositories-rsync
@@ -87,7 +87,7 @@ echo "
 " | ghe-ssh "$host" -- /bin/sh || {
     res=$?
     if [ $res = 7 ]; then
-        echo "Error: git-gc processes remain after $GHE_GIT_COOLDOWN_PERIOD seconds. Aborting..." 1>&2
+        echo "Error: Git GC processes remain after $GHE_GIT_COOLDOWN_PERIOD seconds. Aborting..." 1>&2
     fi
     exit $res
 }
