ghe-restore -s <snapshot-id> for restoring specific snapshot

diff --git a/scripts/ghe-restore b/scripts/ghe-restore
--- a/scripts/ghe-restore
+++ b/scripts/ghe-restore
@@ -1,5 +1,5 @@
 #!/bin/sh
-#/ Usage: ghe-restore [<host>]
+#/ Usage: ghe-restore [-s <snapshot-id>] [<host>]
 #/ Restores a GitHub instance from local backup snapshots. The <host> is the
 #/ hostname or IP of the GitHub instance. The <host> may be omitted when
 #/ the GHE_RESTORE_HOST config variable is set in backup.config. When a <host>
@@ -9,24 +9,29 @@
 #/ described in the following help article:
 #/
 #/ <https://enterprise.github.com/help/articles/adding-an-ssh-key-for-shell-access>
+#/
+#/ When the -s argument is given, restore from the snapshot with the given id.
+#/ Available snapshots can be listed under the data directory.
 set -e
 
 # Bring in the backup configuration.
 cd $(dirname "$0")/..
 . scripts/ghe-backup-config
 
-# Grab the host arg
-host="${1:-$GHE_RESTORE_HOST}"
+# The snapshot directory we're restoring from. This is the 'current' snapshot
+# by default but may be overridden with the -s flag. Additional restore scripts
+# spawned must abide by this variable as well.
+GHE_RESTORE_SNAPSHOT="current"
+export GHE_RESTORE_SNAPSHOT
 
-# Bail out if we don't have a good snapshot.
-if [ ! -d "$GHE_DATA_DIR/current" ]; then
-    echo "Error: No backup snapshot exists. Aborting." 1>&2
-    exit 1
+# Parse snapshot argument if provided
+if [ "$1" = "-s" ]; then
+    GHE_RESTORE_SNAPSHOT="$(basename "$2")"
+    shift 2
 fi
 
-# Figure out what the current increment number is by reading the symlink.
-# Use gross ls/sed hack because readlink of isn't available.
-current_snapshot=$(ls -ld "$GHE_DATA_DIR"/current 2>&1 | sed 's/.*-> //')
+# Grab the host arg
+host="${1:-$GHE_RESTORE_HOST}"
 
 # Show usage with no <host> or if --help was given
 if [ -z "$host" -o "$1" = "--help" ]; then
@@ -34,7 +39,20 @@ if [ -z "$host" -o "$1" = "--help" ]; then
     exit 1
 fi
 
-echo "Using snapshot '$GHE_DATA_DIR/$current_snapshot' to restore GitHub instance at $host."
+# Resolve the snapshot id if we're restoring from current. This is mostly
+# just for logging.
+if [ "$GHE_RESTORE_SNAPSHOT" = "current" ]; then
+    GHE_RESTORE_SNAPSHOT=$(ls -ld "$GHE_DATA_DIR"/current 2>&1 | sed 's/.*-> //')
+fi
+
+# Bail out if we don't have a good snapshot.
+if [ ! -d "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT" ]; then
+    echo "Error: Snapshot '$GHE_RESTORE_SNAPSHOT' doesn't exist." 1>&2
+    exit 1
+fi
+
+snapshot_dir="$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT"
+echo "Using snapshot '$snapshot_dir' to restore GitHub instance at $host ..."
 
 # Make sure we have SSH connectivity to the restore host
 ghe-host-check "$host"
@@ -43,20 +61,19 @@ echo "Restoring Git repository data ..." 1>&2
 ghe-${GHE_BACKUP_STRATEGY}-restore "$host"
 
 echo "Restoring GitHub Pages data ..." 1>&2
-ssh "admin@$host" -- 'ghe-import-pages' < "$GHE_DATA_DIR"/current/pages.tar
+ssh "admin@$host" -- 'ghe-import-pages' < "$snapshot_dir/pages.tar"
 
 echo "Restoring MySQL data ..." 1>&2
-gzip -dc $GHE_DATA_DIR/current/mysql.sql.gz |
-ssh "admin@$host" -- 'ghe-import-mysql'
+gzip -dc "$snapshot_dir/mysql.sql.gz" | ssh "admin@$host" -- 'ghe-import-mysql'
 
 echo "Restoring Redis data ..." 1>&2
-ssh "admin@$host" -- 'ghe-import-redis' < "$GHE_DATA_DIR"/current/redis.rdb
+ssh "admin@$host" -- 'ghe-import-redis' < "$snapshot_dir/redis.rdb"
 
 echo "Restoring SSH public keys ..." 1>&2
-ssh "admin@$host" -- 'ghe-import-authorized-keys' < "$GHE_DATA_DIR"/current/authorized-keys.json
+ssh "admin@$host" -- 'ghe-import-authorized-keys' < "$snapshot_dir/authorized-keys.json"
 
 echo "Restoring Elasticsearch indices ..." 1>&2
-ssh "admin@$host" -- 'ghe-import-es-indices' < "$GHE_DATA_DIR"/current/es-indices.tar
+ssh "admin@$host" -- 'ghe-import-es-indices' < "$snapshot_dir/es-indices.tar"
 
 echo "Restoring SSH host keys ..." 1>&2
-ssh "admin@$host" -- 'ghe-import-ssh-host-keys' < "$GHE_DATA_DIR"/current/ssh-host-keys.tar
+ssh "admin@$host" -- 'ghe-import-ssh-host-keys' < "$snapshot_dir/ssh-host-keys.tar"
