Bring set -e back in ghe-backup
The more I thought about this, the more I didn't like it. There's
stuff in gh-backup-config that relies on set -e to halt if
a command exits non-zero. This'll work just as well.

diff --git a/scripts/ghe-backup b/scripts/ghe-backup
--- a/scripts/ghe-backup
+++ b/scripts/ghe-backup
@@ -5,19 +5,14 @@
 #/
 #/ With -v, enable verbose output and show more information about what's being
 #/ transferred.
-#set -e
+set -e
 
 # Bring in the backup configuration
 cd $(dirname "$0")/..
 . scripts/ghe-backup-config
 
-FAILED_BACKUP_STEPS=
-
-check_status () {
-    if [ $? -gt 0 ]; then
-        FAILED_BACKUP_STEPS="$FAILED_BACKUP_STEPS $1"
-    fi
-}
+# Used to record failed backup steps
+failures=
 
 echo "Starting backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP"
 
@@ -31,13 +26,15 @@ mkdir -p "$GHE_SNAPSHOT_DIR"
 touch "$GHE_SNAPSHOT_DIR/incomplete"
 
 echo "Backing up GitHub settings ..."
-ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-settings' > "$GHE_SNAPSHOT_DIR"/settings.json
-ghe-ssh "$GHE_HOSTNAME" -- "cat '$GHE_REMOTE_LICENSE_FILE'" > "$GHE_SNAPSHOT_DIR"/enterprise.ghl
-check_status "settings"
+ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-settings' > "$GHE_SNAPSHOT_DIR"/settings.json ||
+failures="$failures settings"
+
+ghe-ssh "$GHE_HOSTNAME" -- "cat '$GHE_REMOTE_LICENSE_FILE'" > "$GHE_SNAPSHOT_DIR"/enterprise.ghl ||
+failures="$failures license"
 
 echo "Backing up Git repositories ..."
-ghe-${GHE_BACKUP_STRATEGY}-backup
-check_status "repositories"
+ghe-${GHE_BACKUP_STRATEGY}-backup ||
+failures="$failures repositories"
 
 echo "Backing up GitHub Pages ..."
 ghe-ssh "$GHE_HOSTNAME" -- "
@@ -46,33 +43,33 @@ ghe-ssh "$GHE_HOSTNAME" -- "
     else
         tar cvf - --files-from /dev/null
     fi
-" > "$GHE_SNAPSHOT_DIR"/pages.tar
-check_status "pages"
+" > "$GHE_SNAPSHOT_DIR"/pages.tar ||
+failures="$failures pages"
 
 echo "Backing up MySQL database ..."
-ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-mysql | gzip' > "$GHE_SNAPSHOT_DIR"/mysql.sql.gz
-check_status "mysql"
+ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-mysql | gzip' > "$GHE_SNAPSHOT_DIR"/mysql.sql.gz ||
+failures="$failures mysql"
 
 echo "Backing up Redis database ..."
-ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-redis' > "$GHE_SNAPSHOT_DIR"/redis.rdb
-check_status "redis"
+ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-redis' > "$GHE_SNAPSHOT_DIR"/redis.rdb ||
+failures="$failures redis"
 
 echo "Backing up SSH public keys ..."
-ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-authorized-keys' > "$GHE_SNAPSHOT_DIR"/authorized-keys.json
-check_status "authorized-keys"
+ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-authorized-keys' > "$GHE_SNAPSHOT_DIR"/authorized-keys.json ||
+failures="$failures authorized-keys"
 
 echo "Backing up SSH host keys ..."
-ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-ssh-host-keys' > "$GHE_SNAPSHOT_DIR"/ssh-host-keys.tar
-check_status "ssh-host-keys"
+ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-ssh-host-keys' > "$GHE_SNAPSHOT_DIR"/ssh-host-keys.tar ||
+failures="$failures ssh-host-keys"
 
 echo "Backing up Elasticsearch indices ..."
-ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-es-indices' > "$GHE_SNAPSHOT_DIR"/es-indices.tar
-check_status "es-indices"
+ghe-ssh "$GHE_HOSTNAME" -- 'ghe-export-es-indices' > "$GHE_SNAPSHOT_DIR"/es-indices.tar ||
+failures="$failures ssh-host-keys"
 
 # If everything was successful, mark the snapshot as complete, update the
 # current symlink to point to the new snapshot and prune expired and failed
 # snapshots.
-if [ -z "$FAILED_BACKUP_STEPS" ]; then
+if [ -z "$failures" ]; then
     rm "$GHE_SNAPSHOT_DIR/incomplete"
 
     rm -f "$GHE_DATA_DIR/current"
@@ -84,8 +81,8 @@ fi
 echo "Completed backup of $GHE_HOSTNAME in snapshot $GHE_SNAPSHOT_TIMESTAMP at $(date +"%H:%M:%S")"
 
 # Exit non-zero and list the steps that failed.
-if [ -n "$FAILED_BACKUP_STEPS" ]; then
-    steps="$(echo $FAILED_BACKUP_STEPS | sed 's/ /, /g')"
+if [ -n "$failures" ]; then
+    steps="$(echo $failures | sed 's/ /, /g')"
     echo "Error: Snapshot incomplete. Some steps failed: ${steps}. "
     exit 1
 fi
