Fix wrong error message when touching sync file fails
We were previously assuming that any failed exit signalled that the
GC cooldown time had been exceeded but there are a number of other
reasons the command could fail. e.g., an ssh network error or system
error.

diff --git a/scripts/ghe-rsync-backup b/scripts/ghe-rsync-backup
--- a/scripts/ghe-rsync-backup
+++ b/scripts/ghe-rsync-backup
@@ -49,10 +49,13 @@ ssh "$host" -- "
             exit 0
         fi
     done
-    exit 1
+    exit 7
 " || {
-    echo "Error: git-gc processes remain after 60 seconds. Aborting..." 1>&2
-    exit 1
+    res=$?
+    if [ $res = 7 ]; then
+        echo "Error: git-gc processes remain after 60 seconds. Aborting..." 1>&2
+    fi
+    exit $res
 }
 
 # Function to rsync repository data from a GitHub instance to the local
