Doing some copy editing

diff --git a/scripts/ghe-backup-config b/scripts/ghe-backup-config
--- a/scripts/ghe-backup-config
+++ b/scripts/ghe-backup-config
@@ -18,18 +18,18 @@ GHE_BACKUP_ROOT="$(pwd)"
 # Add the scripts dir to PATH
 PATH="$GHE_BACKUP_ROOT/scripts:$PATH"
 
-# Check that the config file exists before we source it in
+# Check that the config file exists before we source it in.
 if [ ! -f "backup.config" ]; then
-    echo "error: The backup.config file doesn't exist." 1>&2
+    echo "Error: The backup.config file doesn't exist." 1>&2
     exit 2
 fi
 
-# Source in the backup config file
+# Source in the backup config file.
 . "$GHE_BACKUP_ROOT"/backup.config
 
 # Check that the GHE hostname is set.
 if [ -z "$GHE_HOSTNAME" ]; then
-    echo "error: GHE_HOSTNAME not set in config file." 1>&2
+    echo "Error: GHE_HOSTNAME not set in config file." 1>&2
     exit 2
 fi
 
diff --git a/scripts/ghe-host-check b/scripts/ghe-host-check
--- a/scripts/ghe-host-check
+++ b/scripts/ghe-host-check
@@ -3,13 +3,13 @@
 # Verify connectivity with the GitHub Enterprise host.
 set -e
 
-# Bring in the backup configuration
+# Bring in the backup configuration.
 cd $(dirname "$0")/..
 . scripts/ghe-backup-config
 
-# SSH to the GHE host and run a simple command
+# SSH to the GHE host and run a simple command.
 if ! ssh admin@"$GHE_HOSTNAME" -- "true"; then
-    echo "error: ssh to '$GHE_HOSTNAME' failed." 1>&2
+    echo "Error: ssh to '$GHE_HOSTNAME' failed." 1>&2
     exit 2
 fi
 
