prperly use pigz for logical mysql export, instead of binary

diff --git a/share/github-backup-utils/ghe-backup-mysql-binary b/share/github-backup-utils/ghe-backup-mysql-binary
--- a/share/github-backup-utils/ghe-backup-mysql-binary
+++ b/share/github-backup-utils/ghe-backup-mysql-binary
@@ -17,7 +17,7 @@ ghe_remote_version_required "$GHE_HOSTNAME"
 
 echo "Backing up MySQL database using binary backup strategy ..."
 
-echo "set -o pipefail; ghe-export-mysql | pigz" |
+echo "set -o pipefail; ghe-export-mysql" |
 ghe-ssh "$GHE_HOSTNAME" -- /bin/bash > "$GHE_SNAPSHOT_DIR/mysql.sql.gz"
 echo "NO_ADDITIONAL_COMPRESSION" > "$GHE_SNAPSHOT_DIR/mysql-binary-backup-sentinel"
 
diff --git a/share/github-backup-utils/ghe-backup-mysql-logical b/share/github-backup-utils/ghe-backup-mysql-logical
--- a/share/github-backup-utils/ghe-backup-mysql-logical
+++ b/share/github-backup-utils/ghe-backup-mysql-logical
@@ -18,7 +18,7 @@ ghe_remote_version_required "$GHE_HOSTNAME"
 echo "Backing up MySQL database using logical backup strategy ..."
 
 
-echo "set -o pipefail; ghe-export-mysql" |
+echo "set -o pipefail; ghe-export-mysql | pigz" |
 ghe-ssh "$GHE_HOSTNAME" -- /bin/bash > "$GHE_SNAPSHOT_DIR/mysql.sql.gz"
 
 bm_end "$(basename $0)"
