Merge pull request #268 from github/improved-logging
Prepend colorized input to logging data

diff --git a/share/github-backup-utils/ghe-backup-es-rsync b/share/github-backup-utils/ghe-backup-es-rsync
--- a/share/github-backup-utils/ghe-backup-es-rsync
+++ b/share/github-backup-utils/ghe-backup-es-rsync
@@ -20,7 +20,7 @@ ghe_remote_version_required "$host"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  echo "Error: rsync not found." 1>&2
+  log_error "rsync not found." 1>&2
   exit 1
 fi
 
@@ -43,13 +43,14 @@ fi
 # directory, using a previous snapshot to avoid transferring files that have
 # already been transferred.
 ghe_verbose "* Performing initial sync of ES indices ..."
+log_rsync "BEGIN elasticsearch rsync" 1>&3
 ghe-rsync -avz \
   -e "ghe-ssh -p $(ssh_port_part "$host")" \
   --rsync-path="sudo -u elasticsearch rsync" \
   $link_dest \
   "$(ssh_host_part "$host"):$GHE_REMOTE_DATA_USER_DIR/elasticsearch/" \
   "$GHE_SNAPSHOT_DIR/elasticsearch" 1>&3
-
+log_rsync "END elasticsearch rsync" 1>&3
 # Set up a trap to re-enable flushing on exit and remove temp file
 cleanup () {
   ghe_verbose "* Enabling ES index flushing ..."
@@ -67,12 +68,14 @@ ghe-ssh "$host" -- curl -s -XPOST "localhost:9200/_flush" >/dev/null
 
 # Transfer all ES indices again
 ghe_verbose "* Performing follow-up sync of ES indices ..."
+log_rsync "BEGIN: elasticsearch followup rsync" 1>&3
 ghe-rsync -avz \
   -e "ghe-ssh -p $(ssh_port_part "$host")" \
   --rsync-path="sudo -u elasticsearch rsync" \
   $link_dest \
   "$(ssh_host_part "$host"):$GHE_REMOTE_DATA_USER_DIR/elasticsearch/" \
   "$GHE_SNAPSHOT_DIR/elasticsearch" 1>&3
+log_rsync "END: elasticsearch followup rsync" 1>&3
 
 # "Backup" audit log migration sentinel file
 if ghe-ssh "$host" -- "test -f $GHE_REMOTE_DATA_USER_DIR/common/es-scan-complete"; then
diff --git a/share/github-backup-utils/ghe-backup-minio b/share/github-backup-utils/ghe-backup-minio
--- a/share/github-backup-utils/ghe-backup-minio
+++ b/share/github-backup-utils/ghe-backup-minio
@@ -19,7 +19,7 @@ backup_dir="${GHE_SNAPSHOT_DIR}/minio"
 
 # Verify rsync is available.
 if ! command -v rsync 1> /dev/null 2>&1; then
-  echo "Error: rsync not found." 1>&2
+  log_error "rsync not found." 1>&2
   exit 1
 fi
 
@@ -41,7 +41,7 @@ fi
 
 # Transfer all minio data from the user data directory using rsync.
 ghe_verbose "* Transferring minio files from ${host} ..."
-
+log_rsync "BEGIN: minio rsync" 1>&3
 ghe-rsync \
   --archive \
   --verbose \
@@ -52,5 +52,5 @@ ghe-rsync \
   ${link_dest} \
   "${host}:${GHE_REMOTE_DATA_USER_DIR}/minio/" \
   "${GHE_SNAPSHOT_DIR}/minio" 1>&3
-
+log_rsync "END: minio rsync" 1>&3
 bm_end "$(basename "${0}")"
