feat: use proxycommand for communicating wih mssql master

diff --git a/share/github-backup-utils/ghe-restore-mssql b/share/github-backup-utils/ghe-restore-mssql
--- a/share/github-backup-utils/ghe-restore-mssql
+++ b/share/github-backup-utils/ghe-restore-mssql
@@ -36,8 +36,18 @@ if ! import_tool_available; then
   exit
 fi
 
+tempdir=$(mktemp -d -t backup-utils-backup-XXXXXX)
+ssh_config_file_opt=
+# git server hostnames under cluster
+if [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
+  ssh_config_file="$tempdir/ssh_config"
+  ssh_config_file_opt="-F $ssh_config_file"
+  opts="$opts -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
+  ghe-ssh-config "$GHE_HOSTNAME" "$GHE_MSSQL_PRIMARY_HOST" > "$ssh_config_file"
+fi
+
 # Perform a host-check and establish the remote version in GHE_REMOTE_VERSION.
-ghe_remote_version_required "$GHE_MSSQL_PRIMARY_HOST"
+ghe_remote_version_required "$GHE_HOSTNAME"
 
 # The snapshot to restore should be set by the ghe-restore command but this lets
 # us run this script directly.
@@ -48,20 +58,20 @@ snapshot_dir_mssql="$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/mssql"
 
 # Transfer backup files from appliance to backup host
 appliance_dir="$GHE_REMOTE_DATA_USER_DIR/mssql/backups"
-echo "set -o pipefail; sudo rm -rf $appliance_dir; sudo mkdir -p $appliance_dir" | ghe-ssh "$GHE_MSSQL_PRIMARY_HOST" /bin/bash
+echo "set -o pipefail; sudo rm -rf $appliance_dir; sudo mkdir -p $appliance_dir" | ghe-ssh $opts $ssh_config_file_opt "$GHE_MSSQL_PRIMARY_HOST" /bin/bash
 for b in "$snapshot_dir_mssql"/*
 do
   [[ -e "$b" ]] || break
 
   filename="${b##*/}"
   ghe_verbose "Transferring $filename to appliance host"
-  cat $snapshot_dir_mssql/$filename | ghe-ssh "$GHE_MSSQL_PRIMARY_HOST" "sudo tee -a $appliance_dir/$filename >/dev/null 2>&1"
+  cat $snapshot_dir_mssql/$filename | ghe-ssh $opts $ssh_config_file_opt "$GHE_MSSQL_PRIMARY_HOST" "sudo tee -a $appliance_dir/$filename >/dev/null 2>&1"
 done
 
 # Change owner to mssql:mssql to ready for restore
-ghe-ssh "$GHE_MSSQL_PRIMARY_HOST" "sudo chown -R mssql:mssql $appliance_dir"
+ghe-ssh $opts $ssh_config_file_opt "$GHE_MSSQL_PRIMARY_HOST" "sudo chown -R mssql:mssql $appliance_dir"
 
 # Invoke restore command
 bm_start "$(basename $0)"
-ghe-ssh "$GHE_MSSQL_PRIMARY_HOST" -- "ghe-import-mssql" < "/dev/null" 1>&3
+ghe-ssh $opts $ssh_config_file_opt "$GHE_MSSQL_PRIMARY_HOST" -- "ghe-import-mssql" < "/dev/null" 1>&3
 bm_end "$(basename $0)"
