Do not require gawk to be installed

diff --git a/share/github-backup-utils/ghe-backup-config b/share/github-backup-utils/ghe-backup-config
--- a/share/github-backup-utils/ghe-backup-config
+++ b/share/github-backup-utils/ghe-backup-config
@@ -66,11 +66,6 @@ for f in "$GHE_BACKUP_CONFIG" "$GHE_BACKUP_ROOT/backup.config" \
   fi
 done
 
-if ! echo | awk '{ print strftime("%b %d %H:%M:%S"); fflush(); }' &>/dev/null; then
-  echo "Error: awk command failed. Please install https://www.gnu.org/software/gawk" 1>&2
-  exit 1
-fi
-
 ghe_parallel_check() {
   if [ "$GHE_PARALLEL_ENABLED" != "yes" ]; then
     return 0
@@ -111,8 +106,16 @@ fi
 # otherwise, redirect it to /dev/null. Write verbose output to fd 3.
 if [ -n "$GHE_VERBOSE" ]; then
   if [ -n "$GHE_VERBOSE_LOG" ]; then
-    calling_script_name="$(caller | sed 's:.*/::')"
-    exec 3> >(awk -v c=$calling_script_name '{ print strftime("%b %d %H:%M:%S"), c":", $0; fflush(); }' >> "$GHE_VERBOSE_LOG")
+    if [ "$GHE_PARALLEL_ENABLED" != "yes" ]; then
+      exec 3>> "$GHE_VERBOSE_LOG"
+    else
+      if ! echo | awk '{ print strftime("%b %d %H:%M:%S"); fflush(); }' &>/dev/null; then
+        echo "Error: awk command failed. Please install https://www.gnu.org/software/gawk" 1>&2
+        exit 1
+      fi
+      calling_script_name="$(caller | sed 's:.*/::')"
+      exec 3> >(awk -v c=$calling_script_name '{ print strftime("%b %d %H:%M:%S"), c":", $0; fflush(); }' >> "$GHE_VERBOSE_LOG")
+    fi
   else
     exec 3>&1
   fi
