Co-authored-by: Chuck Pathanjali <chuckp22@github.com>

diff --git a/share/github-backup-utils/ghe-backup-config b/share/github-backup-utils/ghe-backup-config
--- a/share/github-backup-utils/ghe-backup-config
+++ b/share/github-backup-utils/ghe-backup-config
@@ -66,6 +66,67 @@ for f in "$GHE_BACKUP_CONFIG" "$GHE_BACKUP_ROOT/backup.config" \
   fi
 done
 
+GHE_RESTORE_IN_PROGRESS="${GHE_DATA_DIR}/.in-progress-restore"
+GHE_BACKUP_IN_PROGRESS="${GHE_DATA_DIR}/.in-progress"
+export GHE_RESTORE_IN_PROGRESS
+export GHE_BACKUP_IN_PROGRESS
+
+ghe_restore_started() {
+echo "$1 $$" > $GHE_RESTORE_IN_PROGRESS
+}
+
+ghe_restore_check() {
+if [ -h $GHE_RESTORE_IN_PROGRESS ]; then
+  echo "Error: detected a restore already in progress from a previous version of ghe-restore." 1>&2
+  echo "If there is no restore in progress anymore, please remove" 1>&2
+  echo "the $GHE_DATA_DIR/in-progress-restore file." 1>&2
+  exit 1
+fi
+
+if [ -f $GHE_RESTORE_IN_PROGRESS ]; then
+  progress=$(cat $GHE_RESTORE_IN_PROGRESS)
+  snapshot=$(echo "$progress" | cut -d ' ' -f 1)
+  pid=$(echo "$progress" | cut -d ' ' -f 2)
+    echo "Error: A restore of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
+    echo "If PID $pid is not a process related to the restore utilities, please remove" 1>&2
+    echo "the $GHE_DATA_DIR/in-progress-restore file and try again." 1>&2
+    exit 1
+  fi
+}
+
+ghe_backup_check() {
+if [ -h $GHE_BACKUP_IN_PROGRESS ]; then
+  echo "Error: detected a backup already in progress from a previous version of ghe-backup." 1>&2
+  echo "If there is no backup in progress anymore, please remove" 1>&2
+  echo "the $GHE_DATA_DIR/in-progress-backup file." 1>&2
+  exit 1
+fi
+
+if [ -f $GHE_BACKUP_IN_PROGRESS ]; then
+  progress=$(cat $GHE_BACKUP_IN_PROGRESS)
+  snapshot=$(echo "$progress" | cut -d ' ' -f 1)
+  pid=$(echo "$progress" | cut -d ' ' -f 2)
+    echo "Error: A backup of $GHE_HOSTNAME may still be running on PID $pid." 1>&2
+    echo "If PID $pid is not a process related to the backup utilities, please remove" 1>&2
+    echo "the $GHE_DATA_DIR/in-progress file and try again." 1>&2
+    exit 1
+  fi
+}
+
+ghe_restore_finished() {
+	echo "$GHE_RESTORE_IN_PROGRESS"
+	if [ -f $GHE_RESTORE_IN_PROGRESS ]; then
+		echo "$GHE_RESTORE_IN_PROGRESS exists!" 1>&2
+		rm -f $GHE_RESTORE_IN_PROGRESS
+	fi
+}
+
+ghe_backup_finished() {
+	if [ ! -f $GHE_BACKUP_IN_PROGRESS ]; then
+		rm -f $GHE_BACKUP_IN_PROGRESS
+	fi
+}
+
 ghe_parallel_check() {
   if [ "$GHE_PARALLEL_ENABLED" != "yes" ]; then
     return 0
