revert "Updating repository info data" changes

diff --git a/share/github-backup-utils/ghe-restore-repositories b/share/github-backup-utils/ghe-restore-repositories
--- a/share/github-backup-utils/ghe-restore-repositories
+++ b/share/github-backup-utils/ghe-restore-repositories
@@ -194,11 +194,13 @@ if [ -d $GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info ]; then
   ghe_verbose "* Transferring repository info data"
 
   for hostname in $hostnames; do
-    ghe-rsync -av --delete \
+    if ! ghe-rsync -av --delete \
       -e "ssh -q $opts -p $port $ssh_config_file_opt -l $user" \
       --rsync-path="sudo -u git rsync" \
       "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
-      "$hostname:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3
+      "$hostname:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
+       echo "Error restoring /data/repositories/info to $hostname" 1>&2
+    fi
   done
 
 else
