Add check for awk

diff --git a/share/github-backup-utils/ghe-backup-config b/share/github-backup-utils/ghe-backup-config
--- a/share/github-backup-utils/ghe-backup-config
+++ b/share/github-backup-utils/ghe-backup-config
@@ -66,6 +66,11 @@ for f in "$GHE_BACKUP_CONFIG" "$GHE_BACKUP_ROOT/backup.config" \
   fi
 done
 
+if ! echo | awk '{ print strftime("%b %d %H:%M:%S"); fflush(); }' &>/dev/null; then
+  echo "Error: awk not found. Please install https://www.gnu.org/software/gawk" 1>&2
+  exit 1
+fi
+
 ghe_parallel_check() {
   # Some machines may have both moreutils parallel and GNU parallel installed.
   GHE_PARALLEL_COMMAND="parallel"
