Do not require customer to use standard output for backup script

diff --git a/share/github-backup-utils/ghe-restore-mysql b/share/github-backup-utils/ghe-restore-mysql
--- a/share/github-backup-utils/ghe-restore-mysql
+++ b/share/github-backup-utils/ghe-restore-mysql
@@ -30,8 +30,12 @@ snapshot_dir="$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT"
 
 # When customer uses external database, we rely on customer to implement the restore process
 if is_service_external 'mysql' "$snapshot_dir/settings.json"; then
-  echo "Restore external MySQL database using customer-provided script ..."
-  $EXTERNAL_DATABASE_RESTORE_SCRIPT
+  if [ -n "$EXTERNAL_DATABASE_RESTORE_SCRIPT" ]; then
+    $EXTERNAL_DATABASE_RESTORE_SCRIPT
+  else
+    echo "Error: EXTERNAL_DATABASE_RESTORE_SCRIPT is not configured. Please configure in backup.config."
+    exit 1
+  fi
 else
   ssh_config_file_opt=
   if is_binary_backup_feature_on; then
