fix extra space

diff --git a/share/github-backup-utils/ghe-restore-repositories b/share/github-backup-utils/ghe-restore-repositories
--- a/share/github-backup-utils/ghe-restore-repositories
+++ b/share/github-backup-utils/ghe-restore-repositories
@@ -199,7 +199,7 @@ if [ -d $GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info ]; then
       --rsync-path="sudo -u git rsync" \
       "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
       "$hostname:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
-       echo "Error restoring /data/repositories/info to $hostname" 1>&2
+      echo "Error restoring /data/repositories/info to $hostname" 1>&2
     fi
   done
 
