Update ghe-backup-config

diff --git a/share/github-backup-utils/ghe-backup-config b/share/github-backup-utils/ghe-backup-config
--- a/share/github-backup-utils/ghe-backup-config
+++ b/share/github-backup-utils/ghe-backup-config
@@ -466,7 +466,7 @@ ghe_parse_remote_version() {
 # moreutils parallel and GNU parallel. Get parallel command based on version
 ghe_remote_parallel() {
   if [ -z "$GHE_REMOTE_VERSION" ]; then
-    ecbk "Error: ghe_remote_version_required needs to be invoked before ghe_remote_parallel" 1>&2
+    echo "Error: ghe_remote_version_required needs to be invoked before ghe_remote_parallel" 1>&2
     exit 1
   fi
 
