Add restore entry point

diff --git a/share/github-backup-utils/ghe-restore-mysql b/share/github-backup-utils/ghe-restore-mysql
--- a/share/github-backup-utils/ghe-restore-mysql
+++ b/share/github-backup-utils/ghe-restore-mysql
@@ -28,63 +28,68 @@ ghe_remote_version_required "$GHE_HOSTNAME"
 # The directory holding the snapshot to restore
 snapshot_dir="$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT"
 
-ssh_config_file_opt=
-if is_binary_backup_feature_on; then
-  # Feature "mysql.backup.binary" is on, which means new backup scripts are available
-  if is_binary_backup "$snapshot_dir"; then
-    if $CLUSTER ; then
-      ghe_mysql_master=$(ghe-ssh "$GHE_HOSTNAME" ghe-config "cluster.mysql-master")
-      if [ -z $ghe_mysql_master ]; then
-        echo "Something is wrong with configuration: cluster.mysql-master not found" >&2
-        exit 2
+# When customer uses external database, we rely on customer to implement the restore process
+if is_service_external 'mysql'; then
+  cat $GHE_REMOTE_DATA_USER_DIR/tmp/mysql.sql.gz | $EXTERNAL_DATABASE_RESTORE_SCRIPT
+else
+  ssh_config_file_opt=
+  if is_binary_backup_feature_on; then
+    # Feature "mysql.backup.binary" is on, which means new backup scripts are available
+    if is_binary_backup "$snapshot_dir"; then
+      if $CLUSTER ; then
+        ghe_mysql_master=$(ghe-ssh "$GHE_HOSTNAME" ghe-config "cluster.mysql-master")
+        if [ -z $ghe_mysql_master ]; then
+          echo "Something is wrong with configuration: cluster.mysql-master not found" >&2
+          exit 2
+        else
+          tempdir=$(mktemp -d -t backup-utils-restore-XXXXXX)
+          ssh_config_file="$tempdir/ssh_config"
+          ssh_config_file_opt="-F $ssh_config_file"
+          ghe-ssh-config "$GHE_HOSTNAME" "$ghe_mysql_master" > "$ssh_config_file"
+          port=$(ssh_port_part "$GHE_HOSTNAME")
+          ghe_mysql_master=$ghe_mysql_master${port:+:$port}
+        fi
       else
-        tempdir=$(mktemp -d -t backup-utils-restore-XXXXXX)
-        ssh_config_file="$tempdir/ssh_config"
-        ssh_config_file_opt="-F $ssh_config_file"
-        ghe-ssh-config "$GHE_HOSTNAME" "$ghe_mysql_master" > "$ssh_config_file"
-        port=$(ssh_port_part "$GHE_HOSTNAME")
-        ghe_mysql_master=$ghe_mysql_master${port:+:$port}
+        ghe_mysql_master=$GHE_HOSTNAME
+      fi
+
+      # Check if the decompress needed by looking into the sentinel file
+      # In 2.19.5 we compress the binary backup twice
+      if [ "$(cat $snapshot_dir/mysql-binary-backup-sentinel)" = "NO_ADDITIONAL_COMPRESSION" ]; then
+        IMPORT_MYSQL=ghe-import-mysql-xtrabackup
+        GHE_RESTORE_HOST=$ghe_mysql_master
+      else
+        IMPORT_MYSQL="unpigz | ghe-import-mysql-xtrabackup"
+        GHE_RESTORE_HOST=$ghe_mysql_master
       fi
     else
-      ghe_mysql_master=$GHE_HOSTNAME
+      IMPORT_MYSQL="unpigz | ghe-import-mysql-mysqldump"
+      GHE_RESTORE_HOST=$GHE_HOSTNAME
     fi
-
-    # Check if the decompress needed by looking into the sentinel file
-    # In 2.19.5 we compress the binary backup twice
-    if [ "$(cat $snapshot_dir/mysql-binary-backup-sentinel)" = "NO_ADDITIONAL_COMPRESSION" ]; then
-      IMPORT_MYSQL=ghe-import-mysql-xtrabackup
-      GHE_RESTORE_HOST=$ghe_mysql_master
+  else
+    # We do not allow to restore binary backup without "mysql.backup.binary" set
+    if is_binary_backup "$snapshot_dir"; then
+      echo "To restore from a binary backup, you have to set ghe-config \"mysql.backup.binary\" to true" >&2
+      exit 2
     else
-      IMPORT_MYSQL="unpigz | ghe-import-mysql-xtrabackup"
-      GHE_RESTORE_HOST=$ghe_mysql_master
+      # legacy mode
+      IMPORT_MYSQL="unpigz | ghe-import-mysql"
+      GHE_RESTORE_HOST=$GHE_HOSTNAME
     fi
-  else
-    IMPORT_MYSQL="unpigz | ghe-import-mysql-mysqldump"
-    GHE_RESTORE_HOST=$GHE_HOSTNAME
   fi
-else
-  # We do not allow to restore binary backup without "mysql.backup.binary" set
-  if is_binary_backup "$snapshot_dir"; then
-    echo "To restore from a binary backup, you have to set ghe-config \"mysql.backup.binary\" to true" >&2
-    exit 2
-  else
-    # legacy mode
-    IMPORT_MYSQL="unpigz | ghe-import-mysql"
-    GHE_RESTORE_HOST=$GHE_HOSTNAME
-  fi
+
+  cleanup() {
+    ghe-ssh $ssh_config_file_opt "$GHE_RESTORE_HOST" -- "sudo rm -rf $GHE_REMOTE_DATA_USER_DIR/tmp/mysql.sql.gz"
+  }
+  trap 'cleanup' INT TERM EXIT
+
+  ghe-ssh $ssh_config_file_opt "$GHE_RESTORE_HOST" -- "sudo mkdir -p '$GHE_REMOTE_DATA_USER_DIR/tmp'" 1>&3
+
+  # Transfer MySQL data from the snapshot to the GitHub instance.
+  cat $snapshot_dir/mysql.sql.gz | ghe-ssh $ssh_config_file_opt "$GHE_RESTORE_HOST" -- "sudo dd of=$GHE_REMOTE_DATA_USER_DIR/tmp/mysql.sql.gz >/dev/null 2>&1"
+
+  # Import the database
+  echo "cat $GHE_REMOTE_DATA_USER_DIR/tmp/mysql.sql.gz | $IMPORT_MYSQL" | ghe-ssh $ssh_config_file_opt "$GHE_RESTORE_HOST" -- /bin/bash 1>&3
 fi
-
-cleanup() {
-  ghe-ssh $ssh_config_file_opt "$GHE_RESTORE_HOST" -- "sudo rm -rf $GHE_REMOTE_DATA_USER_DIR/tmp/mysql.sql.gz"
-}
-trap 'cleanup' INT TERM EXIT
-
-ghe-ssh $ssh_config_file_opt "$GHE_RESTORE_HOST" -- "sudo mkdir -p '$GHE_REMOTE_DATA_USER_DIR/tmp'" 1>&3
-
-# Transfer MySQL data from the snapshot to the GitHub instance.
-cat $snapshot_dir/mysql.sql.gz | ghe-ssh $ssh_config_file_opt "$GHE_RESTORE_HOST" -- "sudo dd of=$GHE_REMOTE_DATA_USER_DIR/tmp/mysql.sql.gz >/dev/null 2>&1"
-
-# Import the database
-echo "cat $GHE_REMOTE_DATA_USER_DIR/tmp/mysql.sql.gz | $IMPORT_MYSQL" | ghe-ssh $ssh_config_file_opt "$GHE_RESTORE_HOST" -- /bin/bash 1>&3
 
 bm_end "$(basename $0)"
