go back to first upload the dump and later import the entries
This mimics what we do with regular MySQL data.

diff --git a/share/github-backup-utils/ghe-restore-mysql-audit-log b/share/github-backup-utils/ghe-restore-mysql-audit-log
--- a/share/github-backup-utils/ghe-restore-mysql-audit-log
+++ b/share/github-backup-utils/ghe-restore-mysql-audit-log
@@ -16,13 +16,24 @@ base_path="$( dirname "${BASH_SOURCE[0]}" )"
 
 GHE_HOSTNAME="$1"
 
-# Setup GHE_REMOTE_XXX variables, snapshot_dir and skip_prepare
+# Setup GHE_REMOTE_XXX variables, snapshot_dir,
+# remote_dir, remote_dump and skip_prepare
 setup(){
   # Perform a host-check and establish GHE_REMOTE_XXX variables.
   ghe_remote_version_required "$GHE_HOSTNAME"
 
   snapshot_dir="$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/audit-log-mysql"
+  remote_dir="$GHE_REMOTE_DATA_USER_DIR/tmp"
+  remote_dump="$remote_dump/month.gz"
   skip_prepare=false
+
+  ghe-ssh "$GHE_HOSTNAME" -- "sudo mkdir -p '$remote_dir'" 1>&3 2>&3
+  trap cleanup EXIT
+}
+
+# Clean up on exit
+cleanup(){
+  ghe-ssh "$GHE_HOSTNAME" -- "sudo rm -rf $remote_dump"
 }
 
 # Use ghe-export-audit-logs to fetch the current metadata for all stored
@@ -110,8 +121,11 @@ restore_dump(){
     return 1
   fi
 
-  # Transfer MySQL data from the snapshot to the GitHub instance and restore it on the fly
-  ghe-ssh "$GHE_HOSTNAME" -- "sudo ghe-export-audit-logs restore --use-gunzip=true" 1>&3 2>&3 <"$dump"
+  # Transfer MySQL data from the snapshot to the GitHub instance.
+  ghe-ssh "$GHE_HOSTNAME" -- "sudo dd of=$remote_dump" 1>&3 2>&3 <"$dump"
+
+  # Import the entries
+  echo "gunzip -cd $remote_dump | sudo ghe-export-audit-logs restore" | ghe-ssh "$GHE_HOSTNAME" -- /bin/bash 2>&3
 }
 
 # Restore a month of audit entries
