Logging and backup script check

diff --git a/share/github-backup-utils/ghe-backup-mysql b/share/github-backup-utils/ghe-backup-mysql
--- a/share/github-backup-utils/ghe-backup-mysql
+++ b/share/github-backup-utils/ghe-backup-mysql
@@ -17,7 +17,13 @@ ghe_remote_version_required "$GHE_HOSTNAME"
 
 if is_service_external 'mysql'; then
   # Trigger client mysql backup hook
-  $EXTERNAL_DATABASE_BACKUP_SCRIPT
+  echo "Backing up external MySQL database using customer-provided script..."
+  if [ -n "$EXTERNAL_DATABASE_BACKUP_SCRIPT" ]; then
+    $EXTERNAL_DATABASE_BACKUP_SCRIPT
+  else
+    echo "Error: EXTERNAL_DATABASE_BACKUP_SCRIPT is not configured. Please configure in backup.config."
+    exit 1
+  fi
   # Finsh the benchmark and exit early. If the script returns a non-zero 
   # exit code, it will be caught by`set -e`
   bm_end "$(basename $0)"
