External database support

diff --git a/share/github-backup-utils/ghe-restore-mysql b/share/github-backup-utils/ghe-restore-mysql
--- a/share/github-backup-utils/ghe-restore-mysql
+++ b/share/github-backup-utils/ghe-restore-mysql
@@ -33,13 +33,12 @@ if is_external_database_snapshot; then
   if [ -n "$EXTERNAL_DATABASE_RESTORE_SCRIPT" ]; then
     $EXTERNAL_DATABASE_RESTORE_SCRIPT
   else
-    echo "Error: EXTERNAL_DATABASE_RESTORE_SCRIPT is not configured. Please configure in backup.config."
-    exit 1
+    if is_binary_backup_feature_on || is_binary_backup "$snapshot_dir"; then
+      echo "Error: Restore of a binary backup to appliance with an external database configured is not supported.
+      Please provide a custom external database restore script with EXTERNAL_DATABASE_RESTORE_SCRIPT"
+      exit 1
+    fi
   fi
-  # Finsh the benchmark and exit early. If the script returns a non-zero 
-  # exit code, it will be caught by`set -e`
-  bm_end "$(basename $0)"
-  exit 0
 fi
 
 if is_binary_backup_feature_on; then
