Update logging for support

diff --git a/share/github-backup-utils/ghe-backup-es-audit-log b/share/github-backup-utils/ghe-backup-es-audit-log
--- a/share/github-backup-utils/ghe-backup-es-audit-log
+++ b/share/github-backup-utils/ghe-backup-es-audit-log
@@ -22,7 +22,7 @@ ghe_remote_version_required "$host"
 mkdir -p "$GHE_SNAPSHOT_DIR/audit-log"
 
 if ! indices=$(ghe-ssh "$host" "curl -s \"localhost:9201/_cat/indices/audit_log*?h=index,pri.store.size&bytes=b\""); then
-  echo "Error: failed to retrieve audit log indices." 1>&2
+  logError "ghe-backup-es-audit-log: Failed to retrieve audit log indices." 1>&2
   exit 1
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-fsck b/share/github-backup-utils/ghe-backup-fsck
--- a/share/github-backup-utils/ghe-backup-fsck
+++ b/share/github-backup-utils/ghe-backup-fsck
@@ -14,7 +14,7 @@ echo "Running git fsck on repos..."
 
 # Verify git is available.
 if ! git --version 1>/dev/null 2>&1; then
-  echo "Error: git not found." 1>&2
+  logError "git not found." 1>&2
   exit 1
 fi
 
@@ -26,7 +26,7 @@ t_start=$(date +%s)
 if git fsck -h | grep -q '\-\-dangling'; then
   git_cmd='git fsck --no-dangling'
 else
-  echo "Warning: old git version, --no-dangling not available"
+  logWarn "ghe-backup-fsck: old git version, --no-dangling not available" 1>&3
   git_cmd='git fsck'
 fi
 
@@ -35,7 +35,7 @@ if [ -z "$sdir" ] || [ ! -d "$sdir" ]; then
 fi
 
 if [ ! -d "$sdir/repositories" ]; then
-  echo "Error: $sdir is not a valid snapshot." >&2
+  logError "ghe-backup-fsck: $sdir is not a valid snapshot." >&2
   exit 1
 fi
 
@@ -84,7 +84,7 @@ for repo in $(find $sdir/repositories/ -type d -name \*.git); do
 
 done
 
-echo "* Repos verified: $repos, Errors: $errors, Took: $(($(date +%s) - $t_start))s"
+logInfo "* Repos verified: $repos, Errors: $errors, Took: $(($(date +%s) - $t_start))s"
 
 rm -f $log
 
diff --git a/share/github-backup-utils/ghe-backup-git-hooks b/share/github-backup-utils/ghe-backup-git-hooks
--- a/share/github-backup-utils/ghe-backup-git-hooks
+++ b/share/github-backup-utils/ghe-backup-git-hooks
@@ -14,7 +14,7 @@ bm_start "$(basename $0)"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  echo "Error: rsync not found." 1>&2
+  logError "rsync not found." 1>&2
   exit 1
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-minio b/share/github-backup-utils/ghe-backup-minio
--- a/share/github-backup-utils/ghe-backup-minio
+++ b/share/github-backup-utils/ghe-backup-minio
@@ -19,7 +19,7 @@ backup_dir="${GHE_SNAPSHOT_DIR}/minio"
 
 # Verify rsync is available.
 if ! command -v rsync 1> /dev/null 2>&1; then
-  echo "Error: rsync not found." 1>&2
+  LogError "rsync not found." 1>&2
   exit 1
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-settings b/share/github-backup-utils/ghe-backup-settings
--- a/share/github-backup-utils/ghe-backup-settings
+++ b/share/github-backup-utils/ghe-backup-settings
@@ -19,10 +19,10 @@ host="$GHE_HOSTNAME"
 mkdir -p "$GHE_SNAPSHOT_DIR"
 cd "$GHE_SNAPSHOT_DIR"
 
-echo "* Transferring settings data ..." 1>&3
+logInfo "* Transferring settings data ..." 1>&3
 ghe-ssh "$host" -- 'ghe-export-settings' > settings.json
 
-echo "* Transferring license data ..." 1>&3
+logInfo "* Transferring license data ..." 1>&3
 ghe-ssh "$host" -- "sudo cat '$GHE_REMOTE_LICENSE_FILE'" > enterprise.ghl
 
 # Function to backup a secret setting to a file.
@@ -61,7 +61,7 @@ backup-secret() {
     esac
   done
 
-  echo "* Transferring $description ..." 1>&3
+  logInfo "* Transferring $description ..." 1>&3
   ghe-ssh "$host" -- ghe-config "$setting" > "$file+" || (
     if  [ "$best_effort" = "false" ]; then
       echo "Warning: $description not set" >&2
@@ -133,24 +133,24 @@ if ghe-ssh "$host" -- ghe-config --true app.packages.enabled; then
 fi
 
 if ghe-ssh "$host" -- "test -f $GHE_REMOTE_DATA_USER_DIR/common/idp.crt"; then
-  echo "* Transferring SAML keys ..." 1>&3
+  logInfo "* Transferring SAML keys ..." 1>&3
   ghe-ssh $host -- sudo tar -C $GHE_REMOTE_DATA_USER_DIR/common/ -cf - "idp.crt saml-sp.p12" > saml-keys.tar
 fi
 
 if ghe-ssh "$host" -- "which ghe-export-ssl-ca-certificates 1>/dev/null"; then
-  echo "* Transferring CA certificates ..." 1>&3
+  logInfo "* Transferring CA certificates ..." 1>&3
   ghe-ssh "$host" -- "ghe-export-ssl-ca-certificates" > ssl-ca-certificates.tar
 fi
 
 if [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
-  echo "* Transferring cluster configuration ..." 1>&3
+  logInfo "* Transferring cluster configuration ..." 1>&3
   if ! ghe-ssh "$host" -- "sudo cat $GHE_REMOTE_CLUSTER_CONF_FILE 2>/dev/null" > cluster.conf; then
-    echo "Error: Enterprise Cluster is not configured yet, backup will fail" >&2
+    logError "Error: Enterprise Cluster is not configured yet, backup will fail" >&2
     exit 1
   fi
 else
   if ghe-ssh "$host" -- "sudo cat $GHE_REMOTE_DATA_USER_DIR/common/uuid 2>/dev/null" > uuid; then
-    echo "* Transferring UUID ..." 1>&3
+    logInfo "* Transferring UUID ..." 1>&3
   fi
 fi
 
diff --git a/share/github-backup-utils/ghe-backup-storage b/share/github-backup-utils/ghe-backup-storage
--- a/share/github-backup-utils/ghe-backup-storage
+++ b/share/github-backup-utils/ghe-backup-storage
@@ -19,7 +19,7 @@ backup_dir="$GHE_SNAPSHOT_DIR/storage"
 
 # Verify rsync is available.
 if ! rsync --version 1>/dev/null 2>&1; then
-  echo "Error: rsync not found." 1>&2
+  logError "rsync not found." 1>&2
   exit 1
 fi
 
@@ -60,7 +60,7 @@ cleanup() {
   # Enable remote maintenance operations
   for hostname in $hostnames; do
     ghe-gc-enable $ssh_config_file_opt $hostname:$port || { 
-      echo "Re-enable gc on $hostname failed, please manually delete $SYNC_IN_PROGRESS_FILE" 1>&2
+      logWarn "Re-enable gc on $hostname failed, please manually delete $SYNC_IN_PROGRESS_FILE" 1>&2
     }
   done
 
@@ -111,7 +111,7 @@ ghe_debug "\n$(find "$tempdir" -maxdepth 1 -name '*.rsync')"
 bm_end "$(basename $0) - Processing routes"
 
 if [ -z "$(find "$tempdir" -maxdepth 1 -name '*.rsync')" ]; then
-  echo "Warning: no routes found, skipping storage backup ..."
+  logWarn "no routes found, skipping storage backup ..."
   exit 0
 fi
 
