More portable argument parsing
macOS uses Bash 3.X and argument parsing works differently in that version,
breaking ghe-detect-leaked-ssh-keys.

/cc @sridharavinash

diff --git a/share/github-backup-utils/ghe-detect-leaked-ssh-keys b/share/github-backup-utils/ghe-detect-leaked-ssh-keys
--- a/share/github-backup-utils/ghe-detect-leaked-ssh-keys
+++ b/share/github-backup-utils/ghe-detect-leaked-ssh-keys
@@ -13,30 +13,22 @@ set -e
 
 usage() {
   grep '^#/' < "$0" | cut -c 4-
+  exit 2
 }
 
 TEMPDIR=$(mktemp -d)
-
-# Parse args.
-ARGS=$(getopt --name "$0" --long help,snapshot: --options hs -- "$@") || {
-  usage
-  exit 2
-}
-eval set -- $ARGS
 
 while [ $# -gt 0 ]; do
   case "$1" in
     -h|--help)
       usage
-      exit 2
       ;;
     -s|--snapshot)
-      shift 2
-      snapshot=$1
-      ;;
-    --)
+      snapshot=$2
       shift
-      break
+      ;;
+    *)
+      usage
       ;;
   esac
   shift
@@ -61,6 +53,10 @@ keys="ssh_host_dsa_key.pub ssh_host_ecdsa_key.pub ssh_host_ed25519_key.pub ssh_h
 
 # Get all the host ssh keys tar from all snapshots directories
 if [ -n "$snapshot" ]; then
+  if [ ! -d "$snapshot" ]; then
+    echo "Invalid snapshot directory: $snapshot" >&2
+    exit 1
+  fi
   ssh_tars=$(find "$snapshot" -maxdepth 1 -type f -iname 'ssh-host-keys.tar')
 else
   ssh_tars=$(find "$GHE_DATA_DIR" -maxdepth 2 -type f -iname 'ssh-host-keys.tar')
