spelling: github
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>

diff --git a/share/github-backup-utils/ghe-backup-config b/share/github-backup-utils/ghe-backup-config
--- a/share/github-backup-utils/ghe-backup-config
+++ b/share/github-backup-utils/ghe-backup-config
@@ -335,7 +335,7 @@ ssh_host_part() {
 # rsync commands.
 ssh_port_part() {
   if [ "${1##*:}" != "$1" ] && [ "${1##*:}" -ne "122" ]; then
-    echo "Error: SSH port has to be 122 connecting to Github Enterprise Server, current value is ${1##*:} for $1." 1>&2
+    echo "Error: SSH port has to be 122 connecting to GitHub Enterprise Server, current value is ${1##*:} for $1." 1>&2
     exit 1
   fi
 
