Fix unwanted merge changes

diff --git a/share/github-backup-utils/ghe-restore-repositories-dgit-ng b/share/github-backup-utils/ghe-restore-repositories-dgit-ng
--- a/share/github-backup-utils/ghe-restore-repositories-dgit-ng
+++ b/share/github-backup-utils/ghe-restore-repositories-dgit-ng
@@ -16,7 +16,7 @@ sync_repo_info() {
           --rsync-path="sudo -u git rsync" \
           "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
           "git-server-$uuid:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
-        echo "Error restoring /data/repositories/info to git-server-$uuid"
+        echo "Error restoring /data/repositories/info to git-server-$uuid" 1>&2
       fi
     done
   else
@@ -26,7 +26,7 @@ sync_repo_info() {
           --rsync-path="sudo -u git rsync" \
           "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
           "$route:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
-        echo "Error restoring /data/repositories/info to $route"
+        echo "Error restoring /data/repositories/info to $route" 1>&2
       fi
     done
   fi
