Detect sentinel file on restore and error if not there.

diff --git a/share/github-backup-utils/ghe-restore-mysql b/share/github-backup-utils/ghe-restore-mysql
--- a/share/github-backup-utils/ghe-restore-mysql
+++ b/share/github-backup-utils/ghe-restore-mysql
@@ -35,18 +35,24 @@ if is_external_database_snapshot; then
     bm_end "$(basename $0)"
     exit 0
   else
+    if is_binary_backup "$snapshot_dir"; then
+      echo "Error: Restore of a binary backup to appliance with an external database configured is not supported."
+      echo "Please provide a custom external database restore script with EXTERNAL_DATABASE_RESTORE_SCRIPT"
+      exit 1
+    fi 
+
+    if ! is_default_external_database_snapshot; then
+      echo "Error: Backup was not taken with a GitHub provided backup strategy."
+      echo "You must provide a custom restore script for this backup using EXTERNAL_DATABASE_BACKUP_SCRIPT"
+
+      exit 1
+    fi
+
     if is_binary_backup_feature_on; then
-      if is_binary_backup "$snapshot_dir"; then
-        echo "Error: Restore of a binary backup to appliance with an external database configured is not supported."
-        echo "Please provide a custom external database restore script with EXTERNAL_DATABASE_RESTORE_SCRIPT"
-        exit 1
-      else
-        echo "Warning: Binary backups are configured on the target environment."
-        echo "Binary backups are not supported with an external database configured. Restoring using logical strategy."
-        echo 
-        echo "Please disable binary backups with 'ghe-config mysql.backup.binary false', or"
-        echo "provide a custom restore script using EXTERNAL_DATABASE_BACKUP_SCRIPT"
-      fi
+      echo "Warning: Binary backups are configured on the target environment."
+      echo "Binary backup is not supported with an external MySQL database."
+      echo 
+      echo "Please disable binary backups with 'ghe-config mysql.backup.binary false'"
     fi
   fi
 fi
@@ -64,7 +70,7 @@ else
     echo "To restore from a binary backup, you have to set ghe-config \"mysql.backup.binary\" to true" >&2
     exit 2
   else
-    if is_external_database_snapshot; then
+    if is_default_external_database_snapshot; then
       ghe-restore-mysql-logical $GHE_HOSTNAME
     else
       # legacy mode
