move logic around for binary backups only

diff --git a/share/github-backup-utils/ghe-restore-mysql b/share/github-backup-utils/ghe-restore-mysql
--- a/share/github-backup-utils/ghe-restore-mysql
+++ b/share/github-backup-utils/ghe-restore-mysql
@@ -39,26 +39,26 @@ is_binary_backup_feature_on(){
 }
 
 ssh_config_file_opt=
-if $CLUSTER ; then
-  ghe_mysql_master=$(ghe-ssh "$GHE_HOSTNAME" ghe-config "cluster.mysql-master")
-  if [ -z $ghe_mysql_master ]; then
-    echo "Something is wrong with configuration: cluster.mysql-master not found" >&2
-    exit 2
-  else
-    tempdir=$(mktemp -d -t backup-utils-restore-XXXXXX)
-    ssh_config_file="$tempdir/ssh_config"
-    ssh_config_file_opt="-F $ssh_config_file"
-    ghe-ssh-config "$GHE_HOSTNAME" "$ghe_mysql_master" > "$ssh_config_file"
-    port=$(ssh_port_part "$GHE_HOSTNAME")
-    ghe_mysql_master=$ghe_mysql_master${port:+:$port}
-  fi
-else
-  ghe_mysql_master=$GHE_HOSTNAME
-fi
-
 if is_binary_backup_feature_on; then
   # Feature "mysql.backup.binary" is on, which means new backup scripts are available
   if is_binary_backup; then
+    if $CLUSTER ; then
+      ghe_mysql_master=$(ghe-ssh "$GHE_HOSTNAME" ghe-config "cluster.mysql-master")
+      if [ -z $ghe_mysql_master ]; then
+        echo "Something is wrong with configuration: cluster.mysql-master not found" >&2
+        exit 2
+      else
+        tempdir=$(mktemp -d -t backup-utils-restore-XXXXXX)
+        ssh_config_file="$tempdir/ssh_config"
+        ssh_config_file_opt="-F $ssh_config_file"
+        ghe-ssh-config "$GHE_HOSTNAME" "$ghe_mysql_master" > "$ssh_config_file"
+        port=$(ssh_port_part "$GHE_HOSTNAME")
+        ghe_mysql_master=$ghe_mysql_master${port:+:$port}
+      fi
+    else
+      ghe_mysql_master=$GHE_HOSTNAME
+    fi
+
     # Check if the decompress needed by looking into the sentinel file 
     # In 2.19.5 we compress the binary backup twice
     if [ "$(cat $snapshot_dir/mysql-binary-backup-sentinel)" = "NO_ADDITIONAL_COMPRESSION" ]; then
