ghe-restore-repositories-gist-ng fixes

diff --git a/share/github-backup-utils/ghe-restore-repositories-gist-ng b/share/github-backup-utils/ghe-restore-repositories-gist-ng
--- a/share/github-backup-utils/ghe-restore-repositories-gist-ng
+++ b/share/github-backup-utils/ghe-restore-repositories-gist-ng
@@ -33,9 +33,6 @@ fi
 ghe_remote_version_required "$GHE_HOSTNAME"
 
 # Generate SSH config for forwarding
-
-config=""
-
 # Split host:port into parts
 port=$(ssh_port_part "$GHE_HOSTNAME")
 host=$(ssh_host_part "$GHE_HOSTNAME")
@@ -44,53 +41,55 @@ host=$(ssh_host_part "$GHE_HOSTNAME")
 user="${host%@*}"
 [ "$user" = "$host" ] && user="admin"
 
+tempdir=$(mktemp -d)
+ssh_config_file=$tempdir/ssh_config
+opts="$GHE_EXTRA_SSH_OPTS -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
+tmp_list=$tempdir/tmp_list
+to_restore=$tempdir/to_restore
+
 hostnames=$(ghe-ssh "$GHE_HOSTNAME" ghe-config --get-regexp cluster.*.hostname | cut -d ' ' -f 2)
 for hostname in $hostnames; do
-  config="$config
+  echo "
 Host $hostname
   ServerAliveInterval 60
-  ProxyCommand ssh -q $GHE_EXTRA_SSH_OPTS -p $port $user@$host nc.openbsd %h %p"
+  ProxyCommand ssh -q $GHE_EXTRA_SSH_OPTS -p $port $user@$host nc.openbsd %h %p" >> $ssh_config_file
 done
 
-config_file=$(mktemp -t cluster-backup-restore-XXXXXX)
-echo "$config" > "$config_file"
-
-opts="$GHE_EXTRA_SSH_OPTS -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
-tempdir=$(mktemp -d)
-tmp_list=$(mktemp -t cluster-backup-restore-XXXXXX)
-to_restore=$(mktemp -t cluster-backup-restore-XXXXXX)
-
 cleanup() {
-  rm -rf $tempdir $config_file
+  rm -rf $tempdir
 }
 
-trap 'cleanup' EXIT
+#trap cleanup EXIT
 
 # Find the routes (servers) for each gist available locally
 OLDIFS=$IFS; IFS=$'\n'
-for path in "$gist_paths"; do
-   echo $path | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'
+for path in $gist_paths; do
+   echo $path
 done > $tmp_list
 IFS=$OLDIFS
 
 cat $tmp_list | ghe-ssh "$GHE_HOSTNAME" github-env ./bin/gist-cluster-restore-routes \
  | while read route; do
-  for server in $(echo $route | cut -d ' ' -f2-); do
+  servers=$(echo $route | cut -d ' ' -f2-)
+  for server in $servers; do
     gist=$(echo $route | cut -d ' ' -f1)
-    ghe_verbose "Adding $route to $tempdir/$server.rsync"
+    ghe_verbose "Adding $gist to $tempdir/$server.rsync"
     echo "$gist" >> $tempdir/$server.rsync
  done
- echo "$route" >> $to_restore
+
+ gist_id=$(basename $(echo $route | cut -d ' ' -f 1) .git)
+ ghe_verbose "Route: $gist_id /data/repositories/$gist $servers"
+ echo "$gist_id /data/repositories/$gist $servers" >> $to_restore
 done
 
 # rsync all the gist repositories
 for route in $tempdir/*.rsync; do
   ghe-rsync -arHR --delete \
-    -e "ssh -q $opts -p $port -F $config_file -l $user" \
+    -e "ssh -q $opts -p $port -F $ssh_config_file -l $user" \
     --rsync-path="sudo -u git rsync" \
     --files-from=$route \
     "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/./" \
-    "$(basename $route .rsync):$GHE_REMOTE_DATA_USER_DIR/repositories"
+    "$(basename $route .rsync):$GHE_REMOTE_DATA_USER_DIR/repositories/"
 done
 
 cat $to_restore | ghe-ssh "$GHE_HOSTNAME" github-env ./bin/gist-cluster-restore-finalize
