Correctly sync repository/info and add to tests

diff --git a/share/github-backup-utils/ghe-restore-repositories-dgit-ng b/share/github-backup-utils/ghe-restore-repositories-dgit-ng
--- a/share/github-backup-utils/ghe-restore-repositories-dgit-ng
+++ b/share/github-backup-utils/ghe-restore-repositories-dgit-ng
@@ -1,22 +1,10 @@
 #!/usr/bin/env bash
 #/ Usage: ghe-restore-repositories-dgit-ng <host>
-#/ Restore repositories fron an rsync snapshot of all Git repository data to a GitHub cluster.
+#/ Restore repositories from an rsync snapshot of all Git repository data.
 #/
 #/ Note: This script typically isn't called directly. It's invoked by the
 #/ ghe-restore command when restoring into a cluster.
 set -e
-
-sync_repo_info() {
-  for uuid in `ghe-ssh "$GHE_HOSTNAME" ghe-cluster-each -r git -u`; do
-    if ! ghe-rsync -av --delete \
-        -e "ssh -q $opts -p $port $ssh_config_file_opt -l $user" \
-        --rsync-path="sudo -u git rsync" \
-        "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
-        "git-server-$uuid:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
-      echo "Error restoring /data/repositories/info to git-server-$uuid" 1>&2
-    fi
-  done
-}
 
 # Bring in the backup configuration
 . $( dirname "${BASH_SOURCE[0]}" )/ghe-backup-config
@@ -166,10 +154,22 @@ fi
 bm_start "$(basename $0) - Updating repository info data"
 if [ -d $GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info ]; then
   ghe_verbose "* Transferring repository info data"
-  sync_repo_info
+  for hostname in $hostnames; do
+    if ! ghe-rsync -av --delete \
+        -e "ssh -q $opts -p $port $ssh_config_file_opt -l $user" \
+        --rsync-path="sudo -u git rsync" \
+        "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
+        "$hostname:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
+      echo "Error restoring /data/repositories/info to $hostname" 1>&2
+    fi
+  done
 else
   ghe_verbose "* Removing repository info data"
-  ghe-ssh "$GHE_HOSTNAME" ghe-cluster-each -r git -- rm -f /data/repositories/info/*
+  if $CLUSTER; then
+    ghe-ssh "$GHE_HOSTNAME" ghe-cluster-each -r git -- rm -f /data/repositories/info/*
+  else
+    ghe-ssh "$GHE_HOSTNAME" -- sudo -u git rm -f /data/repositories/info/*
+  fi
 fi
 bm_end "$(basename $0) - Updating repository info data"
 
