update sync file creation mechanism for HA replica

diff --git a/share/github-backup-utils/ghe-backup-repositories b/share/github-backup-utils/ghe-backup-repositories
--- a/share/github-backup-utils/ghe-backup-repositories
+++ b/share/github-backup-utils/ghe-backup-repositories
@@ -78,11 +78,8 @@ if [ "$GHE_BACKUP_STRATEGY" = "cluster" ]; then
   ghe-ssh-config "$GHE_HOSTNAME" "$hostnames" > "$ssh_config_file"
 fi
 
-# hostnames for HA
-if ghe-ssh "$GHE_HOSTNAME" -- \
-  "[ -f '$GHE_REMOTE_ROOT_DIR/etc/github/cluster' ] && [ -f '$GHE_REMOTE_ROOT_DIR/etc/github/repl-state' ]"; then
-  hostnames=$(ghe-ssh "$GHE_HOSTNAME" ghe-cluster-nodes -i | cut -f 2)
-fi
+# Replica hostnames for HA
+ha_replica_hosts=$(ghe-ssh "$GHE_HOSTNAME" ghe-cluster-nodes --replica)
 
 # Make sure root backup dir exists if this is the first run
 mkdir -p "$backup_dir"
@@ -96,8 +93,15 @@ cleanup() {
 
   # Enable remote GC operations
   for hostname in $hostnames; do
-    ghe-gc-enable $ssh_config_file_opt $hostname:$port || { 
+    ghe-gc-enable $ssh_config_file_opt $hostname:$port || {
       echo "Re-enable gc on $hostname failed, please manually delete $SYNC_IN_PROGRESS_FILE" 1>&2
+    }
+  done
+
+  # Enable remote GC operations for HA replica
+  for replica_host in $ha_replica_hosts; do
+    echo "set -o pipefail; ssh $replica_host -- 'sudo rm -f $SYNC_IN_PROGRESS_FILE'" | ghe-ssh "$host" /bin/bash || {
+      echo "Re-enable gc on $replica_host failed, please manually delete $SYNC_IN_PROGRESS_FILE" 1>&2
     }
   done
 
@@ -109,6 +113,15 @@ trap 'cleanup' EXIT INT
 # Disable remote GC operations
 for hostname in $hostnames; do
   ghe-gc-disable $ssh_config_file_opt $hostname:$port
+done
+
+# Disable remote GC operations for HA replica
+# gc_disable is a function defined in ghe-backup-config
+# gc_disable is called on the replica node via the primary node, because replica node is not expected to be reachable from backup host. But replica node is expected to be reachable from primary node.
+for replica_host in $ha_replica_hosts; do
+  echo "set -o pipefail; ssh $replica_host -- '$(declare -f gc_disable); gc_disable \"$SYNC_IN_PROGRESS_FILE\" \"$GHE_GIT_COOLDOWN_PERIOD\"'" | ghe-ssh "$host" /bin/bash || {
+    echo "Disable gc on $replica_host failed" 1>&2
+  }
 done
 
 # If we have a previous increment, avoid transferring existing files via rsync's
