feat: update backup/restore mssql to always use mssql master hostname

diff --git a/share/github-backup-utils/ghe-backup-mssql b/share/github-backup-utils/ghe-backup-mssql
--- a/share/github-backup-utils/ghe-backup-mssql
+++ b/share/github-backup-utils/ghe-backup-mssql
@@ -22,17 +22,12 @@ tran_expire=
 # Check if the export tool is available in this version
 export_tool_available() {
   if [ -z "$GHE_TEST_REMOTE_VERSION" ]; then
-    ghe-ssh "$GHE_HOSTNAME" "test -e /usr/local/bin/ghe-export-mssql"
+    ghe-ssh "$1" "test -e /usr/local/bin/ghe-export-mssql"
   else
     # Always return available for test
     return 0
   fi
 }
-
-if ! export_tool_available; then
-  ghe_verbose "ghe-export-mssql is not available"
-  exit
-fi
 
 add_minute() {
   # Expect date string in the format of yyyymmddTHHMMSS
@@ -53,7 +48,7 @@ find_timestamp() {
 }
 
 actions_dbs() {
-  all_dbs=$(echo 'set -o pipefail; ghe-mssql-console -y -n -q "SET NOCOUNT ON; SELECT name FROM sys.databases"' | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
+  all_dbs=$(echo 'set -o pipefail; ghe-mssql-console -y -n -p -q "SET NOCOUNT ON; SELECT name FROM sys.databases"' | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
   for db in $all_dbs; do
     if [[ ! "$db" =~ ^(master|tempdb|model|msdb)$ ]] && [[ "$db" =~ ^[a-zA-Z0-9_-]+$ ]]; then
       echo "$db"
@@ -90,7 +85,7 @@ ensure_same_dbs() {
 }
 
 run_query() {
-  echo "set -o pipefail; ghe-mssql-console -y -n -q \"SET NOCOUNT ON; $1\"" | ghe-ssh "$GHE_HOSTNAME" /bin/bash | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
+  echo "set -o pipefail; ghe-mssql-console -y -n -p -q \"SET NOCOUNT ON; $1\"" | ghe-ssh "$GHE_HOSTNAME" /bin/bash | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
 }
 
 get_latest_backup_file() {
@@ -304,21 +299,28 @@ if [ -n "$backup_type" ]; then
   elif [ "$backup_type" = "transaction" ]; then
     backup_command='ghe-export-mssql -t'
   fi
-  GHE_HOSTNAME="$(ghe-config cluster.mssql-master)"
+  GHE_MSSQL_PRIMARY_NODE="$(ghe-ssh $GHE_HOSTNAME -- "ghe-config cluster.mssql-master" || true)"
+  GHE_MSSQL_PRIMARY_HOST="$(ghe-ssh $GHE_HOSTNAME -- "ghe-config cluster.$GHE_MSSQL_PRIMARY_NODE.hostname" || true)"
+
+  if ! export_tool_available "$GHE_MSSQL_PRIMARY_HOST"; then
+    ghe_verbose "ghe-export-mssql is not available"
+    exit
+  fi
+
   bm_start "$(basename $0)"
-  ghe-ssh "$GHE_HOSTNAME" -- "$backup_command" || failures="$failures mssql"
+  ghe-ssh "$GHE_MSSQL_PRIMARY_HOST" -- "$backup_command" || failures="$failures mssql"
   bm_end "$(basename $0)"
 
   # Configure the backup cadence on the appliance, which is used for diagnostics
-  ghe-ssh "$GHE_HOSTNAME" "ghe-config mssql.backup.cadence $GHE_MSSQL_BACKUP_CADENCE"
+  ghe-ssh "$GHE_MSSQL_PRIMARY_HOST" "ghe-config mssql.backup.cadence $GHE_MSSQL_BACKUP_CADENCE"
 
   # Transfer backup files from appliance to backup host
   appliance_dir="$GHE_REMOTE_DATA_DIR/user/mssql/backups"
   backups=$(echo "set -o pipefail; if sudo test -d \"$appliance_dir\"; then \
-    sudo ls \"$appliance_dir\"; fi" | ghe-ssh "$GHE_HOSTNAME" /bin/bash)
+    sudo ls \"$appliance_dir\"; fi" | ghe-ssh "$GHE_MSSQL_PRIMARY_HOST" /bin/bash)
   for b in $backups
   do
     ghe_verbose "Transferring to backup host $b"
-    ghe-ssh "$GHE_HOSTNAME" "sudo cat $appliance_dir/$b" > $backup_dir/$b
+    ghe-ssh "$GHE_MSSQL_PRIMARY_HOST" "sudo cat $appliance_dir/$b" > $backup_dir/$b
   done
 fi
