Remove old hostname/uuid method

diff --git a/share/github-backup-utils/ghe-restore-repositories-dgit-ng b/share/github-backup-utils/ghe-restore-repositories-dgit-ng
--- a/share/github-backup-utils/ghe-restore-repositories-dgit-ng
+++ b/share/github-backup-utils/ghe-restore-repositories-dgit-ng
@@ -7,29 +7,15 @@
 set -e
 
 sync_repo_info() {
-  # node names changed in 2.8 and `ghe-cluster-each -u` isn't available
-  # on GHE <= 2.7.X. We need to be backwards compatible.
-  if ghe-ssh "$GHE_HOSTNAME" test -f /data/user/common/uuid; then
-    for uuid in `ghe-ssh "$GHE_HOSTNAME" ghe-cluster-each -r git -u`; do
-      if ! ghe-rsync -av --delete \
-          -e "ssh -q $opts -p $port -F $ssh_config_file -l $user" \
-          --rsync-path="sudo -u git rsync" \
-          "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
-          "git-server-$uuid:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
-        echo "Error restoring /data/repositories/info to git-server-$uuid" 1>&2
-      fi
-    done
-  else
-    for route in `ghe-ssh "$GHE_HOSTNAME" ghe-cluster-each -r git -p`; do
-      if ! ghe-rsync -av --delete \
-          -e "ssh -q $opts -p $port -F $ssh_config_file -l $user" \
-          --rsync-path="sudo -u git rsync" \
-          "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
-          "$route:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
-        echo "Error restoring /data/repositories/info to $route" 1>&2
-      fi
-    done
-  fi
+  for uuid in `ghe-ssh "$GHE_HOSTNAME" ghe-cluster-each -r git -u`; do
+    if ! ghe-rsync -av --delete \
+        -e "ssh -q $opts -p $port -F $ssh_config_file -l $user" \
+        --rsync-path="sudo -u git rsync" \
+        "$GHE_DATA_DIR/$GHE_RESTORE_SNAPSHOT/repositories/info/" \
+        "git-server-$uuid:$GHE_REMOTE_DATA_USER_DIR/repositories/info" 1>&3; then
+      echo "Error restoring /data/repositories/info to git-server-$uuid" 1>&2
+    fi
+  done
 }
 
 # Bring in the backup configuration
