Tweak the fsck output and add some tests

diff --git a/share/github-backup-utils/ghe-backup-fsck b/share/github-backup-utils/ghe-backup-fsck
--- a/share/github-backup-utils/ghe-backup-fsck
+++ b/share/github-backup-utils/ghe-backup-fsck
@@ -1,11 +1,14 @@
 #!/usr/bin/env bash
-#/ Usage: ghe-backup-fsck [--print-nwo]
-#/ git fsck backed up repos
+#/ Usage: ghe-backup-fsck <snapshot-dir> [--print-nwo]
+#/
+#/ Run git fsck on backed up repositories.
 set -e
 
 # Bring in the backup configuration
 cd $(dirname "$0")/../..
 . share/github-backup-utils/ghe-backup-config
+
+echo "Running git fsck on repos..."
 
 # Verify git is available.
 if ! git --version 1>/dev/null 2>&1; then
@@ -13,12 +16,22 @@ if ! git --version 1>/dev/null 2>&1; then
   exit 1
 fi
 
+sdir=$1
 repos=0
 errors=0
-warnings=0
 log=$(mktemp)
+t_start=$(date +%s)
 
-for repo in $(find $GHE_SNAPSHOT_DIR/repositories/ -type d -name \*.git); do
+if [ -z "$sdir" ] || [ ! -d "$sdir" ]; then
+  print_usage
+fi
+
+if [ ! -d "$sdir/repositories" ]; then
+  echo "Error: $sdir is not a valid snapshot." >&2
+  exit 1
+fi
+
+for repo in $(find $sdir/repositories/ -type d -name \*.git); do
   repos=$(($repos+1))
   before_time=$(date +%s)
 
@@ -28,16 +41,16 @@ for repo in $(find $GHE_SNAPSHOT_DIR/repositories/ -type d -name \*.git); do
     cd $repo
 
     nwo="-"
-    if [ "$1" = "--print-nwo" ] && [ -f info/nwo ]; then
+    if [ "$2" = "--print-nwo" ] && [ -f info/nwo ]; then
       nwo="$(cat info/nwo)"
     fi
 
     if [ ! -f objects/info/alternates ] || grep -q '^\.\.' objects/info/alternates; then
-      git fsck --no-dangling >/dev/null 2>$log && {
+      git fsck --no-dangling >$log 2>&1 && {
         echo "OK $repo $nwo"; exit
       }
     else
-      GIT_ALTERNATE_OBJECT_DIRECTORIES=../network.git/objects git fsck --no-dangling >/dev/null 2>$log && {
+      GIT_ALTERNATE_OBJECT_DIRECTORIES=../network.git/objects git fsck --no-dangling >$log 2>&1 && {
         echo "WARN $repo $nwo (alternates absolute path)"; exit
       }
     fi
@@ -48,15 +61,12 @@ for repo in $(find $GHE_SNAPSHOT_DIR/repositories/ -type d -name \*.git); do
   elapsed_time=$(($(date +%s) - before_time))
 
   if [[ ! "$status" =~ ^OK ]] || [ $elapsed_time -gt 5 ]; then
-    echo "$status ${elapsed_time}s"
+    echo "$status ${elapsed_time}s" 1>&3
     [[ ! "$status" =~ ^OK ]] && cat $log
   fi
 
   case "$status" in
     OK*)
-      ;;
-    WARN*)
-      warnings=$(($warnings+1))
       ;;
     ERROR*)
       errors=$(($errors+1))
@@ -65,6 +75,4 @@ for repo in $(find $GHE_SNAPSHOT_DIR/repositories/ -type d -name \*.git); do
 
 done
 
-echo "* Total repos: $repos"
-echo "* Errors:      $errors"
-echo "* Warnings:    $warnings"
+echo "* Repos verified: $repos, Errors: $errors, Took: $(($(date +%s) - $t_start))s"
