Create hard links for backup files

diff --git a/share/github-backup-utils/ghe-backup-mssql b/share/github-backup-utils/ghe-backup-mssql
--- a/share/github-backup-utils/ghe-backup-mssql
+++ b/share/github-backup-utils/ghe-backup-mssql
@@ -13,23 +13,142 @@ set -e
 # Set up remote host and root backup snapshot directory based on config
 host="$GHE_HOSTNAME"
 backup_dir="$GHE_SNAPSHOT_DIR/mssql"
+last=
+last_mssql=
+backup_command=
+take_full=
+take_diff=
+full_expire=
+diff_expire=
+tran_expire=
+
+add_minute() {
+  # Expect date string in the format of yyyymmddTHHMMSS
+  # Here parse date differently depending on GNU Linux vs BSD MacOS
+  if date -v -1d > /dev/null 2>&1; then
+    echo $(date -v+$2M -ujf'%Y%m%dT%H%M%S' $1 +%Y%m%dT%H%M%S)
+  else
+    echo $(date '+%Y%m%dT%H%M%S' -d "${dt:0:8} ${dt:9:2}:${dt:11:2}:${dt:13:2} + $2 min")
+  fi
+}
+
+find_timestamp() {
+  filename="${1##*/}"
+  parts=(${filename//@/ })
+  datetime_part=${parts[1]:0:15}
+  echo $datetime_part
+}
+
+# Find last snapshot to create potential hard links
+count=$(ls $GHE_SNAPSHOT_DIR/.. | egrep '\d{8}T\d{6}' | sort | tail -2 | wc -l)
+if [ $count -gt 1 ]
+then
+  last=$(ls $GHE_SNAPSHOT_DIR/.. | egrep '\d{8}T\d{6}' | sort | tail -2 | head -1)
+else
+  unset last
+fi
+
+last_mssql=$GHE_SNAPSHOT_DIR/../$last/mssql
+
+if [ -z $last ] || [ ! -d $last_mssql ] || [ -z $(find $last_mssql -type f -name "*.bak") ]
+then
+  # Take initial full backup
+  take_full=1
+  backup_command='ghe-export-mssql'
+else
+  # Check schedule to determine backup type
+  cadence=(${GHE_MSSQL_BACKUP_CADENCE//,/ })
+
+  current=$(date -u +%Y%m%d%H%M%S)
+
+  full=$(find "$last_mssql" -type f -name "*.bak")
+  full=$(find_timestamp $full)
+  full_expire=$(add_minute $full ${cadence[0]})
+  full_expire="${full_expire//T}"
+
+  diff=$(find "$last_mssql" -type f -name "*.diff")
+  if [ ! -z $diff ]
+  then
+    diff=$(find_timestamp $diff)
+    diff_expire=$(add_minute $diff ${cadence[1]})
+    diff_expire="${diff_expire//T}"
+  else
+    diff_expire=$(add_minute $full ${cadence[1]})
+    diff_expire="${diff_expire//T}"
+  fi
+
+  tran=$(find "$last_mssql" -type f -name "*.log" | egrep '\d{8}T\d{6}' | sort | tail -1)
+  tran=$(find_timestamp $tran)
+  tran_expire=$(add_minute $tran ${cadence[2]})
+  tran_expire="${tran_expire//T}"
+
+  echo "current $current, full expire $full_expire, diff expire $diff_expire, tran expire $tran_expire"
+
+  # Determine the type of backup to take
+  if [ $current -gt $full_expire ]
+  then
+    echo "Taking full backup"
+    take_full=1
+    backup_command='ghe-export-mssql'
+  elif [ $current -gt $diff_expire ]
+  then
+    echo "Taking diff backup"
+    take_diff=1
+    backup_command='ghe-export-mssql -d'
+  elif [ $current -gt $tran_expire ]
+  then
+    echo "Taking transaction backup"
+    backup_command='ghe-export-mssql -t'
+  fi
+fi
 
 # Make sure root backup dir exists if this is the first run
 mkdir -p "$backup_dir"
 
-bm_start "$(basename $0)"
-ghe-ssh "$host" -- 'ghe-export-mssql' || failures="$failures mssql"
-bm_end "$(basename $0)"
+# Create hard links to save disk space and time
+if [ ! -z $last ]
+then
+  for p in $(ls $last_mssql)
+  do
+    filename="${p##*/}"
+    extension="${filename##*.}"
+    transfer=
 
-# Verify rsync is available.
-if ! rsync --version 1>/dev/null 2>&1; then
-  echo "Error: rsync not found." 1>&2
-  exit 1
+    if [ $extension = "bak" ] && [ -z $take_full ]
+    then
+      transfer=1
+    fi
+
+    if [ $extension = "diff" ] && [ -z $take_full ] && [ -z $take_diff ]
+    then
+      transfer=1
+    fi
+
+    if [ $extension = "log" ] && [ -z $take_full ] && [ -z $take_diff ]
+    then
+      transfer=1
+    fi
+
+    if [ ! -z $transfer ]
+    then
+      echo "Creating hard link to $p"
+      ln $last_mssql/$p $backup_dir/$p
+    fi
+  done
 fi
 
-appliance_dir="/data/user/mssql/backups"
-backups=$(ghe-ssh "$host" "sudo ls $appliance_dir")
-for b in $backups
-do
-  ghe-ssh "$host" "sudo cat $appliance_dir/$b" > $backup_dir/$b
-done
+if [ ! -z "$backup_command" ]
+then
+  bm_start "$(basename $0)"
+  ghe-ssh "$host" -- "$backup_command" || failures="$failures mssql"
+  bm_end "$(basename $0)"
+
+  # Transfer backup files from appliance to backup host
+  appliance_dir="/data/user/mssql/backups"
+  backups=$(echo "set -o pipefail; if sudo test -d \"$appliance_dir\"; then sudo ls \"$appliance_dir\"; fi" | ghe-ssh "$host" /bin/bash)
+  for b in $backups
+  do
+    echo "Transferring $b to backup host"
+    ghe-ssh "$host" "sudo cat $appliance_dir/$b" > $backup_dir/$b
+  done
+fi
